//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: game_pokerface_s2s.proto
namespace pokerface
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SRMsgPlayerInfo")]
  public partial class SRMsgPlayerInfo : global::ProtoBuf.IExtensible
  {
    public SRMsgPlayerInfo() {}
    
    private string _userID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"userID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string userID
    {
      get { return _userID; }
      set { _userID = value; }
    }
    private int _chairID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"chairID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int chairID
    {
      get { return _chairID; }
      set { _chairID = value; }
    }

    private string _nick = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"nick", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string nick
    {
      get { return _nick; }
      set { _nick = value; }
    }

    private uint _sex = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"sex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint sex
    {
      get { return _sex; }
      set { _sex = value; }
    }

    private string _headIconURI = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"headIconURI", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string headIconURI
    {
      get { return _headIconURI; }
      set { _headIconURI = value; }
    }

    private int _avatarID = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"avatarID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int avatarID
    {
      get { return _avatarID; }
      set { _avatarID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SRDealDetail")]
  public partial class SRDealDetail : global::ProtoBuf.IExtensible
  {
    public SRDealDetail() {}
    
    private int _chairID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"chairID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int chairID
    {
      get { return _chairID; }
      set { _chairID = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _cardsHand = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"cardsHand", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> cardsHand
    {
      get { return _cardsHand; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _cardsFlower = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(3, Name=@"cardsFlower", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> cardsFlower
    {
      get { return _cardsFlower; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SRAction")]
  public partial class SRAction : global::ProtoBuf.IExtensible
  {
    public SRAction() {}
    
    private int _action;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"action", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int action
    {
      get { return _action; }
      set { _action = value; }
    }
    private int _chairID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"chairID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int chairID
    {
      get { return _chairID; }
      set { _chairID = value; }
    }
    private int _qaIndex;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"qaIndex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int qaIndex
    {
      get { return _qaIndex; }
      set { _qaIndex = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _cards = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(4, Name=@"cards", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> cards
    {
      get { return _cards; }
    }
  
    private int _flags;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"flags", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int flags
    {
      get { return _flags; }
      set { _flags = value; }
    }

    private int _cardHandType = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"cardHandType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int cardHandType
    {
      get { return _cardHandType; }
      set { _cardHandType = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SRMsgHandRecorderExtra")]
  public partial class SRMsgHandRecorderExtra : global::ProtoBuf.IExtensible
  {
    public SRMsgHandRecorderExtra() {}
    

    private int _markup = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"markup", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int markup
    {
      get { return _markup; }
      set { _markup = value; }
    }

    private string _ownerUserID = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"ownerUserID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string ownerUserID
    {
      get { return _ownerUserID; }
      set { _ownerUserID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SRMsgHandRecorder")]
  public partial class SRMsgHandRecorder : global::ProtoBuf.IExtensible
  {
    public SRMsgHandRecorder() {}
    
    private int _bankerChairID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"bankerChairID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int bankerChairID
    {
      get { return _bankerChairID; }
      set { _bankerChairID = value; }
    }
    private int _windFlowerID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"windFlowerID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int windFlowerID
    {
      get { return _windFlowerID; }
      set { _windFlowerID = value; }
    }
    private readonly global::System.Collections.Generic.List<pokerface.SRMsgPlayerInfo> _players = new global::System.Collections.Generic.List<pokerface.SRMsgPlayerInfo>();
    [global::ProtoBuf.ProtoMember(3, Name=@"players", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pokerface.SRMsgPlayerInfo> players
    {
      get { return _players; }
    }
  
    private bool _isHandOver;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"isHandOver", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool isHandOver
    {
      get { return _isHandOver; }
      set { _isHandOver = value; }
    }
    private readonly global::System.Collections.Generic.List<pokerface.SRDealDetail> _deals = new global::System.Collections.Generic.List<pokerface.SRDealDetail>();
    [global::ProtoBuf.ProtoMember(5, Name=@"deals", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pokerface.SRDealDetail> deals
    {
      get { return _deals; }
    }
  
    private readonly global::System.Collections.Generic.List<pokerface.SRAction> _actions = new global::System.Collections.Generic.List<pokerface.SRAction>();
    [global::ProtoBuf.ProtoMember(6, Name=@"actions", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pokerface.SRAction> actions
    {
      get { return _actions; }
    }
  

    private byte[] _handScore = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"handScore", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] handScore
    {
      get { return _handScore; }
      set { _handScore = value; }
    }

    private string _roomConfigID = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"roomConfigID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string roomConfigID
    {
      get { return _roomConfigID; }
      set { _roomConfigID = value; }
    }

    private uint _startTime = default(uint);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"startTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint startTime
    {
      get { return _startTime; }
      set { _startTime = value; }
    }

    private uint _endTime = default(uint);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"endTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint endTime
    {
      get { return _endTime; }
      set { _endTime = value; }
    }

    private int _handNum = default(int);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"handNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int handNum
    {
      get { return _handNum; }
      set { _handNum = value; }
    }

    private string _shareAbleID = "";
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"shareAbleID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string shareAbleID
    {
      get { return _shareAbleID; }
      set { _shareAbleID = value; }
    }

    private bool _isContinuousBanker = default(bool);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"isContinuousBanker", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isContinuousBanker
    {
      get { return _isContinuousBanker; }
      set { _isContinuousBanker = value; }
    }

    private string _roomNumber = "";
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"roomNumber", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string roomNumber
    {
      get { return _roomNumber; }
      set { _roomNumber = value; }
    }

    private int _roomType = default(int);
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"roomType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int roomType
    {
      get { return _roomType; }
      set { _roomType = value; }
    }

    private pokerface.SRMsgHandRecorderExtra _extra = null;
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"extra", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public pokerface.SRMsgHandRecorderExtra extra
    {
      get { return _extra; }
      set { _extra = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"SRFlags")]
    public enum SRFlags
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SRNone", Value=0)]
      SRNone = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SRUserReplyOnly", Value=1)]
      SRUserReplyOnly = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SRRichi", Value=2)]
      SRRichi = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SRFlyRichi", Value=4)]
      SRFlyRichi = 4
    }
  
}