//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: game_pokerface_rf.proto
namespace pokerface
{
    [global::ProtoBuf.ProtoContract(Name=@"CardHandType")]
    public enum CardHandType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"None", Value=0)]
      None = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Flush", Value=1)]
      Flush = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Bomb", Value=2)]
      Bomb = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Single", Value=3)]
      Single = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Pair", Value=4)]
      Pair = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Pair2X", Value=5)]
      Pair2X = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Triplet", Value=6)]
      Triplet = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TripletPair", Value=7)]
      TripletPair = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Triplet2X", Value=8)]
      Triplet2X = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Triplet2X2Pair", Value=9)]
      Triplet2X2Pair = 9
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"HandOverType")]
    public enum HandOverType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"enumHandOverType_None", Value=0)]
      enumHandOverType_None = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"enumHandOverType_Win_SelfDrawn", Value=1)]
      enumHandOverType_Win_SelfDrawn = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"enumHandOverType_Win_Chuck", Value=2)]
      enumHandOverType_Win_Chuck = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"enumHandOverType_Chucker", Value=3)]
      enumHandOverType_Chucker = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"enumHandOverType_Konger", Value=4)]
      enumHandOverType_Konger = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"enumHandOverType_Win_RobKong", Value=5)]
      enumHandOverType_Win_RobKong = 5
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ActionType")]
    public enum ActionType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"enumActionType_None", Value=0)]
      enumActionType_None = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"enumActionType_SKIP", Value=1)]
      enumActionType_SKIP = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"enumActionType_DISCARD", Value=2)]
      enumActionType_DISCARD = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"enumActionType_DRAW", Value=3)]
      enumActionType_DRAW = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"enumActionType_Win_SelfDrawn", Value=4)]
      enumActionType_Win_SelfDrawn = 4
    }
  
}