// Code generated by protoc-gen-go. DO NOT EDIT.
// source: game_pokerface_s2s.proto

package pokerface

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 记录的动作的标志
type SRFlags int32

const (
	// 普通动作记录
	SRFlags_SRNone SRFlags = 0
	// 该动作仅表示玩家选择了操作
	// 但服务器不一定采纳
	SRFlags_SRUserReplyOnly SRFlags = 1
	// 表明动作伴随着听牌，主要用于庄家起手听牌
	SRFlags_SRRichi    SRFlags = 2
	SRFlags_SRFlyRichi SRFlags = 4
)

var SRFlags_name = map[int32]string{
	0: "SRNone",
	1: "SRUserReplyOnly",
	2: "SRRichi",
	4: "SRFlyRichi",
}

var SRFlags_value = map[string]int32{
	"SRNone":          0,
	"SRUserReplyOnly": 1,
	"SRRichi":         2,
	"SRFlyRichi":      4,
}

func (x SRFlags) Enum() *SRFlags {
	p := new(SRFlags)
	*p = x
	return p
}

func (x SRFlags) String() string {
	return proto.EnumName(SRFlags_name, int32(x))
}

func (x *SRFlags) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(SRFlags_value, data, "SRFlags")
	if err != nil {
		return err
	}
	*x = SRFlags(value)
	return nil
}

func (SRFlags) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0786ddba798afdac, []int{0}
}

// 手牌记录中的用户对象
type SRMsgPlayerInfo struct {
	UserID               *string  `protobuf:"bytes,1,req,name=userID" json:"userID,omitempty"`
	ChairID              *int32   `protobuf:"varint,2,req,name=chairID" json:"chairID,omitempty"`
	Nick                 *string  `protobuf:"bytes,3,opt,name=nick" json:"nick,omitempty"`
	Sex                  *uint32  `protobuf:"varint,4,opt,name=sex" json:"sex,omitempty"`
	HeadIconURI          *string  `protobuf:"bytes,5,opt,name=headIconURI" json:"headIconURI,omitempty"`
	AvatarID             *int32   `protobuf:"varint,6,opt,name=avatarID" json:"avatarID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SRMsgPlayerInfo) Reset()         { *m = SRMsgPlayerInfo{} }
func (m *SRMsgPlayerInfo) String() string { return proto.CompactTextString(m) }
func (*SRMsgPlayerInfo) ProtoMessage()    {}
func (*SRMsgPlayerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_0786ddba798afdac, []int{0}
}
func (m *SRMsgPlayerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SRMsgPlayerInfo.Unmarshal(m, b)
}
func (m *SRMsgPlayerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SRMsgPlayerInfo.Marshal(b, m, deterministic)
}
func (m *SRMsgPlayerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SRMsgPlayerInfo.Merge(m, src)
}
func (m *SRMsgPlayerInfo) XXX_Size() int {
	return xxx_messageInfo_SRMsgPlayerInfo.Size(m)
}
func (m *SRMsgPlayerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SRMsgPlayerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SRMsgPlayerInfo proto.InternalMessageInfo

func (m *SRMsgPlayerInfo) GetUserID() string {
	if m != nil && m.UserID != nil {
		return *m.UserID
	}
	return ""
}

func (m *SRMsgPlayerInfo) GetChairID() int32 {
	if m != nil && m.ChairID != nil {
		return *m.ChairID
	}
	return 0
}

func (m *SRMsgPlayerInfo) GetNick() string {
	if m != nil && m.Nick != nil {
		return *m.Nick
	}
	return ""
}

func (m *SRMsgPlayerInfo) GetSex() uint32 {
	if m != nil && m.Sex != nil {
		return *m.Sex
	}
	return 0
}

func (m *SRMsgPlayerInfo) GetHeadIconURI() string {
	if m != nil && m.HeadIconURI != nil {
		return *m.HeadIconURI
	}
	return ""
}

func (m *SRMsgPlayerInfo) GetAvatarID() int32 {
	if m != nil && m.AvatarID != nil {
		return *m.AvatarID
	}
	return 0
}

// 发牌记录
type SRDealDetail struct {
	ChairID              *int32   `protobuf:"varint,1,req,name=chairID" json:"chairID,omitempty"`
	CardsHand            []int32  `protobuf:"varint,2,rep,name=cardsHand" json:"cardsHand,omitempty"`
	CardsFlower          []int32  `protobuf:"varint,3,rep,name=cardsFlower" json:"cardsFlower,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SRDealDetail) Reset()         { *m = SRDealDetail{} }
func (m *SRDealDetail) String() string { return proto.CompactTextString(m) }
func (*SRDealDetail) ProtoMessage()    {}
func (*SRDealDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_0786ddba798afdac, []int{1}
}
func (m *SRDealDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SRDealDetail.Unmarshal(m, b)
}
func (m *SRDealDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SRDealDetail.Marshal(b, m, deterministic)
}
func (m *SRDealDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SRDealDetail.Merge(m, src)
}
func (m *SRDealDetail) XXX_Size() int {
	return xxx_messageInfo_SRDealDetail.Size(m)
}
func (m *SRDealDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_SRDealDetail.DiscardUnknown(m)
}

var xxx_messageInfo_SRDealDetail proto.InternalMessageInfo

func (m *SRDealDetail) GetChairID() int32 {
	if m != nil && m.ChairID != nil {
		return *m.ChairID
	}
	return 0
}

func (m *SRDealDetail) GetCardsHand() []int32 {
	if m != nil {
		return m.CardsHand
	}
	return nil
}

func (m *SRDealDetail) GetCardsFlower() []int32 {
	if m != nil {
		return m.CardsFlower
	}
	return nil
}

// 动作记录
type SRAction struct {
	Action  *int32 `protobuf:"varint,1,req,name=action" json:"action,omitempty"`
	ChairID *int32 `protobuf:"varint,2,req,name=chairID" json:"chairID,omitempty"`
	QaIndex *int32 `protobuf:"varint,3,req,name=qaIndex" json:"qaIndex,omitempty"`
	// 动作涉及到的牌列表，如果动作是发牌，列表包含花牌和非花牌；
	// 如果动作是出牌，则列表只有一个张牌；如果动作是吃椪杠、列表也只有一张牌，表示面子牌组的第一张牌
	// 对于吃牌，有两个card，一个是面子牌组的第一张牌，另一个是表示吃的哪张牌
	Cards                []int32  `protobuf:"varint,4,rep,name=cards" json:"cards,omitempty"`
	Flags                *int32   `protobuf:"varint,5,req,name=flags" json:"flags,omitempty"`
	CardHandType         *int32   `protobuf:"varint,6,opt,name=cardHandType" json:"cardHandType,omitempty"`
	AllowActions         *int32   `protobuf:"varint,7,opt,name=allowActions" json:"allowActions,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SRAction) Reset()         { *m = SRAction{} }
func (m *SRAction) String() string { return proto.CompactTextString(m) }
func (*SRAction) ProtoMessage()    {}
func (*SRAction) Descriptor() ([]byte, []int) {
	return fileDescriptor_0786ddba798afdac, []int{2}
}
func (m *SRAction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SRAction.Unmarshal(m, b)
}
func (m *SRAction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SRAction.Marshal(b, m, deterministic)
}
func (m *SRAction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SRAction.Merge(m, src)
}
func (m *SRAction) XXX_Size() int {
	return xxx_messageInfo_SRAction.Size(m)
}
func (m *SRAction) XXX_DiscardUnknown() {
	xxx_messageInfo_SRAction.DiscardUnknown(m)
}

var xxx_messageInfo_SRAction proto.InternalMessageInfo

func (m *SRAction) GetAction() int32 {
	if m != nil && m.Action != nil {
		return *m.Action
	}
	return 0
}

func (m *SRAction) GetChairID() int32 {
	if m != nil && m.ChairID != nil {
		return *m.ChairID
	}
	return 0
}

func (m *SRAction) GetQaIndex() int32 {
	if m != nil && m.QaIndex != nil {
		return *m.QaIndex
	}
	return 0
}

func (m *SRAction) GetCards() []int32 {
	if m != nil {
		return m.Cards
	}
	return nil
}

func (m *SRAction) GetFlags() int32 {
	if m != nil && m.Flags != nil {
		return *m.Flags
	}
	return 0
}

func (m *SRAction) GetCardHandType() int32 {
	if m != nil && m.CardHandType != nil {
		return *m.CardHandType
	}
	return 0
}

func (m *SRAction) GetAllowActions() int32 {
	if m != nil && m.AllowActions != nil {
		return *m.AllowActions
	}
	return 0
}

type SRMsgHandRecorderExtra struct {
	Markup               *int32   `protobuf:"varint,1,opt,name=markup" json:"markup,omitempty"`
	OwnerUserID          *string  `protobuf:"bytes,2,opt,name=ownerUserID" json:"ownerUserID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SRMsgHandRecorderExtra) Reset()         { *m = SRMsgHandRecorderExtra{} }
func (m *SRMsgHandRecorderExtra) String() string { return proto.CompactTextString(m) }
func (*SRMsgHandRecorderExtra) ProtoMessage()    {}
func (*SRMsgHandRecorderExtra) Descriptor() ([]byte, []int) {
	return fileDescriptor_0786ddba798afdac, []int{3}
}
func (m *SRMsgHandRecorderExtra) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SRMsgHandRecorderExtra.Unmarshal(m, b)
}
func (m *SRMsgHandRecorderExtra) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SRMsgHandRecorderExtra.Marshal(b, m, deterministic)
}
func (m *SRMsgHandRecorderExtra) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SRMsgHandRecorderExtra.Merge(m, src)
}
func (m *SRMsgHandRecorderExtra) XXX_Size() int {
	return xxx_messageInfo_SRMsgHandRecorderExtra.Size(m)
}
func (m *SRMsgHandRecorderExtra) XXX_DiscardUnknown() {
	xxx_messageInfo_SRMsgHandRecorderExtra.DiscardUnknown(m)
}

var xxx_messageInfo_SRMsgHandRecorderExtra proto.InternalMessageInfo

func (m *SRMsgHandRecorderExtra) GetMarkup() int32 {
	if m != nil && m.Markup != nil {
		return *m.Markup
	}
	return 0
}

func (m *SRMsgHandRecorderExtra) GetOwnerUserID() string {
	if m != nil && m.OwnerUserID != nil {
		return *m.OwnerUserID
	}
	return ""
}

// 一手牌记录器
// 消息用于客户端回播，以及bug定位等
// 用于记录发牌数据，以及听吃椪杠胡等动作
type SRMsgHandRecorder struct {
	BankerChairID        *int32                  `protobuf:"varint,1,req,name=bankerChairID" json:"bankerChairID,omitempty"`
	WindFlowerID         *int32                  `protobuf:"varint,2,req,name=windFlowerID" json:"windFlowerID,omitempty"`
	Players              []*SRMsgPlayerInfo      `protobuf:"bytes,3,rep,name=players" json:"players,omitempty"`
	IsHandOver           *bool                   `protobuf:"varint,4,req,name=isHandOver" json:"isHandOver,omitempty"`
	Deals                []*SRDealDetail         `protobuf:"bytes,5,rep,name=deals" json:"deals,omitempty"`
	Actions              []*SRAction             `protobuf:"bytes,6,rep,name=actions" json:"actions,omitempty"`
	HandScore            []byte                  `protobuf:"bytes,7,opt,name=handScore" json:"handScore,omitempty"`
	RoomConfigID         *string                 `protobuf:"bytes,8,opt,name=roomConfigID" json:"roomConfigID,omitempty"`
	StartTime            *uint32                 `protobuf:"varint,9,opt,name=startTime" json:"startTime,omitempty"`
	EndTime              *uint32                 `protobuf:"varint,10,opt,name=endTime" json:"endTime,omitempty"`
	HandNum              *int32                  `protobuf:"varint,11,opt,name=handNum" json:"handNum,omitempty"`
	ShareAbleID          *string                 `protobuf:"bytes,12,opt,name=shareAbleID" json:"shareAbleID,omitempty"`
	IsContinuousBanker   *bool                   `protobuf:"varint,13,opt,name=isContinuousBanker" json:"isContinuousBanker,omitempty"`
	RoomNumber           *string                 `protobuf:"bytes,14,opt,name=roomNumber" json:"roomNumber,omitempty"`
	RoomType             *int32                  `protobuf:"varint,15,opt,name=roomType" json:"roomType,omitempty"`
	Extra                *SRMsgHandRecorderExtra `protobuf:"bytes,16,opt,name=extra" json:"extra,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *SRMsgHandRecorder) Reset()         { *m = SRMsgHandRecorder{} }
func (m *SRMsgHandRecorder) String() string { return proto.CompactTextString(m) }
func (*SRMsgHandRecorder) ProtoMessage()    {}
func (*SRMsgHandRecorder) Descriptor() ([]byte, []int) {
	return fileDescriptor_0786ddba798afdac, []int{4}
}
func (m *SRMsgHandRecorder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SRMsgHandRecorder.Unmarshal(m, b)
}
func (m *SRMsgHandRecorder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SRMsgHandRecorder.Marshal(b, m, deterministic)
}
func (m *SRMsgHandRecorder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SRMsgHandRecorder.Merge(m, src)
}
func (m *SRMsgHandRecorder) XXX_Size() int {
	return xxx_messageInfo_SRMsgHandRecorder.Size(m)
}
func (m *SRMsgHandRecorder) XXX_DiscardUnknown() {
	xxx_messageInfo_SRMsgHandRecorder.DiscardUnknown(m)
}

var xxx_messageInfo_SRMsgHandRecorder proto.InternalMessageInfo

func (m *SRMsgHandRecorder) GetBankerChairID() int32 {
	if m != nil && m.BankerChairID != nil {
		return *m.BankerChairID
	}
	return 0
}

func (m *SRMsgHandRecorder) GetWindFlowerID() int32 {
	if m != nil && m.WindFlowerID != nil {
		return *m.WindFlowerID
	}
	return 0
}

func (m *SRMsgHandRecorder) GetPlayers() []*SRMsgPlayerInfo {
	if m != nil {
		return m.Players
	}
	return nil
}

func (m *SRMsgHandRecorder) GetIsHandOver() bool {
	if m != nil && m.IsHandOver != nil {
		return *m.IsHandOver
	}
	return false
}

func (m *SRMsgHandRecorder) GetDeals() []*SRDealDetail {
	if m != nil {
		return m.Deals
	}
	return nil
}

func (m *SRMsgHandRecorder) GetActions() []*SRAction {
	if m != nil {
		return m.Actions
	}
	return nil
}

func (m *SRMsgHandRecorder) GetHandScore() []byte {
	if m != nil {
		return m.HandScore
	}
	return nil
}

func (m *SRMsgHandRecorder) GetRoomConfigID() string {
	if m != nil && m.RoomConfigID != nil {
		return *m.RoomConfigID
	}
	return ""
}

func (m *SRMsgHandRecorder) GetStartTime() uint32 {
	if m != nil && m.StartTime != nil {
		return *m.StartTime
	}
	return 0
}

func (m *SRMsgHandRecorder) GetEndTime() uint32 {
	if m != nil && m.EndTime != nil {
		return *m.EndTime
	}
	return 0
}

func (m *SRMsgHandRecorder) GetHandNum() int32 {
	if m != nil && m.HandNum != nil {
		return *m.HandNum
	}
	return 0
}

func (m *SRMsgHandRecorder) GetShareAbleID() string {
	if m != nil && m.ShareAbleID != nil {
		return *m.ShareAbleID
	}
	return ""
}

func (m *SRMsgHandRecorder) GetIsContinuousBanker() bool {
	if m != nil && m.IsContinuousBanker != nil {
		return *m.IsContinuousBanker
	}
	return false
}

func (m *SRMsgHandRecorder) GetRoomNumber() string {
	if m != nil && m.RoomNumber != nil {
		return *m.RoomNumber
	}
	return ""
}

func (m *SRMsgHandRecorder) GetRoomType() int32 {
	if m != nil && m.RoomType != nil {
		return *m.RoomType
	}
	return 0
}

func (m *SRMsgHandRecorder) GetExtra() *SRMsgHandRecorderExtra {
	if m != nil {
		return m.Extra
	}
	return nil
}

func init() {
	proto.RegisterType((*SRMsgPlayerInfo)(nil), "pokerface.SRMsgPlayerInfo")
	proto.RegisterType((*SRDealDetail)(nil), "pokerface.SRDealDetail")
	proto.RegisterType((*SRAction)(nil), "pokerface.SRAction")
	proto.RegisterType((*SRMsgHandRecorderExtra)(nil), "pokerface.SRMsgHandRecorderExtra")
	proto.RegisterType((*SRMsgHandRecorder)(nil), "pokerface.SRMsgHandRecorder")
	proto.RegisterEnum("pokerface.SRFlags", SRFlags_name, SRFlags_value)
}

func init() { proto.RegisterFile("game_pokerface_s2s.proto", fileDescriptor_0786ddba798afdac) }

var fileDescriptor_0786ddba798afdac = []byte{
	// 579 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x53, 0x4d, 0x6f, 0xda, 0x40,
	0x10, 0xad, 0x0d, 0xc6, 0x78, 0x0c, 0x01, 0x96, 0xb4, 0x5d, 0xe5, 0xe4, 0xa2, 0xaa, 0xb2, 0x5a,
	0x29, 0xaa, 0x72, 0xef, 0x21, 0x0d, 0x4d, 0xea, 0x43, 0x93, 0xca, 0x24, 0xe7, 0x68, 0x63, 0x0f,
	0xb0, 0xc2, 0xec, 0xd2, 0x5d, 0x13, 0xc2, 0x1f, 0xe8, 0x4f, 0xea, 0xef, 0xab, 0x66, 0x49, 0xa2,
	0x7c, 0xdc, 0xe0, 0xed, 0xcc, 0x9b, 0x37, 0xef, 0x8d, 0x81, 0xcf, 0xc4, 0x12, 0xaf, 0x57, 0x7a,
	0x81, 0x66, 0x2a, 0x0a, 0xbc, 0xb6, 0x47, 0xf6, 0x70, 0x65, 0x74, 0xad, 0x59, 0xf4, 0x08, 0x8e,
	0x6a, 0xe8, 0x4d, 0xf2, 0x5f, 0x76, 0xf6, 0xbb, 0x12, 0x5b, 0x34, 0x99, 0x9a, 0x6a, 0xb6, 0x07,
	0xad, 0xb5, 0x45, 0x93, 0x8d, 0xb9, 0x97, 0xf8, 0x69, 0xc4, 0x7a, 0x10, 0x16, 0x73, 0x21, 0x09,
	0xf0, 0x13, 0x3f, 0x0d, 0x58, 0x07, 0x9a, 0x4a, 0x16, 0x0b, 0xde, 0x48, 0xbc, 0x34, 0x62, 0x31,
	0x34, 0x2c, 0xde, 0xf1, 0x66, 0xe2, 0xa5, 0x5d, 0x36, 0x84, 0x78, 0x8e, 0xa2, 0xcc, 0x0a, 0xad,
	0xae, 0xf2, 0x8c, 0x07, 0xae, 0xa2, 0x0f, 0x6d, 0x71, 0x2b, 0x6a, 0x41, 0x0c, 0xad, 0xc4, 0x4b,
	0x83, 0xd1, 0x19, 0x74, 0x26, 0xf9, 0x18, 0x45, 0x35, 0xc6, 0x5a, 0xc8, 0xea, 0xe9, 0x08, 0xcf,
	0x8d, 0x18, 0x40, 0x54, 0x08, 0x53, 0xda, 0x9f, 0x42, 0x95, 0xdc, 0x4f, 0x1a, 0x69, 0x40, 0xd4,
	0x0e, 0x3a, 0xad, 0xf4, 0x06, 0x0d, 0x6f, 0x10, 0x38, 0xfa, 0xeb, 0x41, 0x7b, 0x92, 0x1f, 0x17,
	0xb5, 0xd4, 0x8a, 0x84, 0x0b, 0xf7, 0xeb, 0x9e, 0xe4, 0x95, 0xf0, 0x1e, 0x84, 0x7f, 0x44, 0xa6,
	0x4a, 0xbc, 0xe3, 0x0d, 0x07, 0x74, 0x21, 0x70, 0x9c, 0xbc, 0xe9, 0x46, 0x74, 0x21, 0x98, 0x56,
	0x62, 0x66, 0x79, 0xe0, 0x5e, 0xf7, 0xa1, 0x43, 0xaf, 0xa4, 0xe1, 0x72, 0xbb, 0xc2, 0x9d, 0x76,
	0x42, 0x45, 0x55, 0xe9, 0xcd, 0x6e, 0xa8, 0xe5, 0xa1, 0xdb, 0xe8, 0x1b, 0xbc, 0x73, 0x3e, 0x52,
	0x71, 0x8e, 0x85, 0x36, 0x25, 0x9a, 0x1f, 0x77, 0xb5, 0x11, 0xa4, 0x6a, 0x29, 0xcc, 0x62, 0xbd,
	0xe2, 0x9e, 0xeb, 0x1f, 0x42, 0xac, 0x37, 0x0a, 0xcd, 0xd5, 0xce, 0x63, 0x9f, 0x2c, 0x1a, 0xfd,
	0x6b, 0xc0, 0xe0, 0x55, 0x3f, 0x7b, 0x0b, 0xdd, 0x1b, 0xa1, 0x16, 0x68, 0x4e, 0x9e, 0x99, 0xb3,
	0x0f, 0x9d, 0x8d, 0x54, 0xe5, 0xce, 0x88, 0xc7, 0xe5, 0xbe, 0x40, 0xb8, 0x72, 0x21, 0x5a, 0xe7,
	0x4d, 0x7c, 0x74, 0x70, 0xf8, 0x18, 0xf3, 0xe1, 0xcb, 0x8c, 0x19, 0x80, 0x74, 0xe6, 0x5e, 0xdc,
	0xa2, 0xe1, 0xcd, 0xc4, 0x4f, 0xdb, 0xec, 0x13, 0x04, 0x25, 0x8a, 0x8a, 0xb6, 0xa7, 0xf6, 0xf7,
	0xcf, 0xda, 0x9f, 0x84, 0xf5, 0x11, 0x42, 0x71, 0xbf, 0x7b, 0xcb, 0x55, 0x0e, 0x9f, 0x55, 0xde,
	0x87, 0x31, 0x80, 0x68, 0x2e, 0x54, 0x39, 0x29, 0xb4, 0x41, 0xe7, 0x51, 0x87, 0x74, 0x1b, 0xad,
	0x97, 0x27, 0x5a, 0x4d, 0xe5, 0x2c, 0x1b, 0xf3, 0xb6, 0xbb, 0x8e, 0x01, 0x44, 0xb6, 0x16, 0xa6,
	0xbe, 0x94, 0x4b, 0xe4, 0x91, 0xbb, 0xa2, 0x1e, 0x84, 0xa8, 0x4a, 0x07, 0xc0, 0x03, 0x40, 0x64,
	0xe7, 0xeb, 0x25, 0x8f, 0x1f, 0x4c, 0xb4, 0x73, 0x61, 0xf0, 0xf8, 0xa6, 0xc2, 0x6c, 0xcc, 0x3b,
	0x8e, 0xe9, 0x00, 0x98, 0xb4, 0x27, 0x5a, 0xd5, 0x52, 0xad, 0xf5, 0xda, 0x7e, 0x77, 0xd6, 0xf1,
	0x6e, 0xe2, 0xa5, 0x6d, 0x5a, 0x98, 0x66, 0x9f, 0xaf, 0x97, 0x37, 0x68, 0xf8, 0xde, 0xc3, 0x5d,
	0x12, 0xe6, 0xb2, 0xed, 0x39, 0xda, 0xaf, 0x10, 0x20, 0x85, 0xc6, 0xfb, 0x89, 0x97, 0xc6, 0x47,
	0x1f, 0x5e, 0x3a, 0xf8, 0x2a, 0xdd, 0xcf, 0x67, 0x10, 0x4e, 0xf2, 0x53, 0x3a, 0x1a, 0x06, 0xd0,
	0x9a, 0xe4, 0xe7, 0x5a, 0x61, 0xff, 0x0d, 0x1b, 0xd2, 0x67, 0x45, 0x09, 0xe7, 0xb8, 0xaa, 0xb6,
	0x17, 0xaa, 0xda, 0xf6, 0x3d, 0x16, 0x53, 0x6d, 0x2e, 0x8b, 0xb9, 0xec, 0xfb, 0x6c, 0x0f, 0x80,
	0x1a, 0xb7, 0xbb, 0xff, 0xcd, 0xff, 0x01, 0x00, 0x00, 0xff, 0xff, 0x1f, 0x7e, 0x05, 0x73, 0xae,
	0x03, 0x00, 0x00,
}
