//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: game_accessory.proto
namespace accessory
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AccessoryMessage")]
  public partial class AccessoryMessage : global::ProtoBuf.IExtensible
  {
    public AccessoryMessage() {}
    
    private int _Ops;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Ops", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Ops
    {
      get { return _Ops; }
      set { _Ops = value; }
    }

    private byte[] _Data = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] Data
    {
      get { return _Data; }
      set { _Data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgCreateRoomReq")]
  public partial class MsgCreateRoomReq : global::ProtoBuf.IExtensible
  {
    public MsgCreateRoomReq() {}
    
    private string _config;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"config", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string config
    {
      get { return _config; }
      set { _config = value; }
    }

    private int _exchangeId = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"exchangeId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int exchangeId
    {
      get { return _exchangeId; }
      set { _exchangeId = value; }
    }

    private int _roomType = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"roomType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int roomType
    {
      get { return _roomType; }
      set { _roomType = value; }
    }

    private int _openType = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"openType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int openType
    {
      get { return _openType; }
      set { _openType = value; }
    }

    private string _clubID = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"clubID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string clubID
    {
      get { return _clubID; }
      set { _clubID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UserProfile")]
  public partial class UserProfile : global::ProtoBuf.IExtensible
  {
    public UserProfile() {}
    
    private string _userID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"userID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string userID
    {
      get { return _userID; }
      set { _userID = value; }
    }

    private string _userName = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"userName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string userName
    {
      get { return _userName; }
      set { _userName = value; }
    }

    private string _nickName = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"nickName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string nickName
    {
      get { return _nickName; }
      set { _nickName = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RoomInfo")]
  public partial class RoomInfo : global::ProtoBuf.IExtensible
  {
    public RoomInfo() {}
    
    private string _roomID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roomID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string roomID
    {
      get { return _roomID; }
      set { _roomID = value; }
    }
    private string _roomNumber;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"roomNumber", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string roomNumber
    {
      get { return _roomNumber; }
      set { _roomNumber = value; }
    }
    private string _gameServerURL;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"gameServerURL", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string gameServerURL
    {
      get { return _gameServerURL; }
      set { _gameServerURL = value; }
    }

    private int _state = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int state
    {
      get { return _state; }
      set { _state = value; }
    }

    private string _config = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"config", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string config
    {
      get { return _config; }
      set { _config = value; }
    }

    private string _timeStamp = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"timeStamp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string timeStamp
    {
      get { return _timeStamp; }
      set { _timeStamp = value; }
    }
    private readonly global::System.Collections.Generic.List<accessory.UserProfile> _users = new global::System.Collections.Generic.List<accessory.UserProfile>();
    [global::ProtoBuf.ProtoMember(7, Name=@"users", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<accessory.UserProfile> users
    {
      get { return _users; }
    }
  

    private int _handStartted = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"handStartted", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int handStartted
    {
      get { return _handStartted; }
      set { _handStartted = value; }
    }

    private uint _lastActiveTime = default(uint);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"lastActiveTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint lastActiveTime
    {
      get { return _lastActiveTime; }
      set { _lastActiveTime = value; }
    }

    private string _propCfg = "";
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"propCfg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string propCfg
    {
      get { return _propCfg; }
      set { _propCfg = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgCreateRoomRsp")]
  public partial class MsgCreateRoomRsp : global::ProtoBuf.IExtensible
  {
    public MsgCreateRoomRsp() {}
    
    private int _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }

    private accessory.RoomInfo _roomInfo = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"roomInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public accessory.RoomInfo roomInfo
    {
      get { return _roomInfo; }
      set { _roomInfo = value; }
    }

    private int _openType = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"openType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int openType
    {
      get { return _openType; }
      set { _openType = value; }
    }

    private string _retMsg = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"retMsg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string retMsg
    {
      get { return _retMsg; }
      set { _retMsg = value; }
    }

    private int _roomType = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"roomType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int roomType
    {
      get { return _roomType; }
      set { _roomType = value; }
    }

    private int _diamond = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"diamond", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int diamond
    {
      get { return _diamond; }
      set { _diamond = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgReleaseRoomReq")]
  public partial class MsgReleaseRoomReq : global::ProtoBuf.IExtensible
  {
    public MsgReleaseRoomReq() {}
    
    private string _roomID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roomID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string roomID
    {
      get { return _roomID; }
      set { _roomID = value; }
    }

    private int _roomType = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"roomType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int roomType
    {
      get { return _roomType; }
      set { _roomType = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgReleaseRoomRsp")]
  public partial class MsgReleaseRoomRsp : global::ProtoBuf.IExtensible
  {
    public MsgReleaseRoomRsp() {}
    
    private int _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }

    private string _roomID = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"roomID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string roomID
    {
      get { return _roomID; }
      set { _roomID = value; }
    }

    private string _retMsg = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"retMsg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string retMsg
    {
      get { return _retMsg; }
      set { _retMsg = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgChat")]
  public partial class MsgChat : global::ProtoBuf.IExtensible
  {
    public MsgChat() {}
    
    private int _scope;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"scope", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int scope
    {
      get { return _scope; }
      set { _scope = value; }
    }

    private string _from = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"from", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string from
    {
      get { return _from; }
      set { _from = value; }
    }

    private string _to = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"to", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string to
    {
      get { return _to; }
      set { _to = value; }
    }
    private int _dataType;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"dataType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int dataType
    {
      get { return _dataType; }
      set { _dataType = value; }
    }
    private byte[] _data;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] data
    {
      get { return _data; }
      set { _data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RoomIDList")]
  public partial class RoomIDList : global::ProtoBuf.IExtensible
  {
    public RoomIDList() {}
    
    private readonly global::System.Collections.Generic.List<string> _roomIDs = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(1, Name=@"roomIDs", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> roomIDs
    {
      get { return _roomIDs; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgLoadRoomListRsp")]
  public partial class MsgLoadRoomListRsp : global::ProtoBuf.IExtensible
  {
    public MsgLoadRoomListRsp() {}
    
    private int _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private readonly global::System.Collections.Generic.List<accessory.RoomInfo> _roomInfos = new global::System.Collections.Generic.List<accessory.RoomInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"roomInfos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<accessory.RoomInfo> roomInfos
    {
      get { return _roomInfos; }
    }
  

    private string _retMsg = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"retMsg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string retMsg
    {
      get { return _retMsg; }
      set { _retMsg = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgUpdateUserInfo")]
  public partial class MsgUpdateUserInfo : global::ProtoBuf.IExtensible
  {
    public MsgUpdateUserInfo() {}
    
    private string _location;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"location", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string location
    {
      get { return _location; }
      set { _location = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RoomCost")]
  public partial class RoomCost : global::ProtoBuf.IExtensible
  {
    public RoomCost() {}
    
    private uint _handNum;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"handNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint handNum
    {
      get { return _handNum; }
      set { _handNum = value; }
    }
    private uint _pay;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"pay", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint pay
    {
      get { return _pay; }
      set { _pay = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgLoginReply")]
  public partial class MsgLoginReply : global::ProtoBuf.IExtensible
  {
    public MsgLoginReply() {}
    
    private int _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }

    private string _token = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"token", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string token
    {
      get { return _token; }
      set { _token = value; }
    }
    private readonly global::System.Collections.Generic.List<accessory.RoomInfo> _roomInfos = new global::System.Collections.Generic.List<accessory.RoomInfo>();
    [global::ProtoBuf.ProtoMember(3, Name=@"roomInfos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<accessory.RoomInfo> roomInfos
    {
      get { return _roomInfos; }
    }
  

    private string _retMsg = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"retMsg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string retMsg
    {
      get { return _retMsg; }
      set { _retMsg = value; }
    }

    private accessory.RoomInfo _lastRoomInfo = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"lastRoomInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public accessory.RoomInfo lastRoomInfo
    {
      get { return _lastRoomInfo; }
      set { _lastRoomInfo = value; }
    }

    private string _roomDiscount = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"roomDiscount", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string roomDiscount
    {
      get { return _roomDiscount; }
      set { _roomDiscount = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgRequestRoomInfo")]
  public partial class MsgRequestRoomInfo : global::ProtoBuf.IExtensible
  {
    public MsgRequestRoomInfo() {}
    
    private string _roomNumber;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roomNumber", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string roomNumber
    {
      get { return _roomNumber; }
      set { _roomNumber = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgRequestRoomInfoRsp")]
  public partial class MsgRequestRoomInfoRsp : global::ProtoBuf.IExtensible
  {
    public MsgRequestRoomInfoRsp() {}
    
    private int _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }

    private accessory.RoomInfo _roomInfo = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"roomInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public accessory.RoomInfo roomInfo
    {
      get { return _roomInfo; }
      set { _roomInfo = value; }
    }

    private string _retMsg = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"retMsg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string retMsg
    {
      get { return _retMsg; }
      set { _retMsg = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgUpdateRoomState")]
  public partial class MsgUpdateRoomState : global::ProtoBuf.IExtensible
  {
    public MsgUpdateRoomState() {}
    
    private int _state;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int state
    {
      get { return _state; }
      set { _state = value; }
    }
    private string _roomID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"roomID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string roomID
    {
      get { return _roomID; }
      set { _roomID = value; }
    }
    private readonly global::System.Collections.Generic.List<accessory.UserProfile> _users = new global::System.Collections.Generic.List<accessory.UserProfile>();
    [global::ProtoBuf.ProtoMember(3, Name=@"users", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<accessory.UserProfile> users
    {
      get { return _users; }
    }
  
    private int _handStartted;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"handStartted", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int handStartted
    {
      get { return _handStartted; }
      set { _handStartted = value; }
    }
    private uint _lastActiveTime;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"lastActiveTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint lastActiveTime
    {
      get { return _lastActiveTime; }
      set { _lastActiveTime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgUpdateRoomList")]
  public partial class MsgUpdateRoomList : global::ProtoBuf.IExtensible
  {
    public MsgUpdateRoomList() {}
    
    private readonly global::System.Collections.Generic.List<accessory.RoomInfo> _roomInfos = new global::System.Collections.Generic.List<accessory.RoomInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"roomInfos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<accessory.RoomInfo> roomInfos
    {
      get { return _roomInfos; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgRequestUserScoreInfo")]
  public partial class MsgRequestUserScoreInfo : global::ProtoBuf.IExtensible
  {
    public MsgRequestUserScoreInfo() {}
    
    private string _userID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"userID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string userID
    {
      get { return _userID; }
      set { _userID = value; }
    }

    private string _gameID = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"gameID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string gameID
    {
      get { return _gameID; }
      set { _gameID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgRequestUserScoreInfoRsp")]
  public partial class MsgRequestUserScoreInfoRsp : global::ProtoBuf.IExtensible
  {
    public MsgRequestUserScoreInfoRsp() {}
    
    private int _maxWinScore;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"maxWinScore", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int maxWinScore
    {
      get { return _maxWinScore; }
      set { _maxWinScore = value; }
    }
    private int _customCount;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"customCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int customCount
    {
      get { return _customCount; }
      set { _customCount = value; }
    }

    private int _maxWinMoney = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"maxWinMoney", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int maxWinMoney
    {
      get { return _maxWinMoney; }
      set { _maxWinMoney = value; }
    }

    private int _coinCount = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"coinCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int coinCount
    {
      get { return _coinCount; }
      set { _coinCount = value; }
    }

    private string _retMsg = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"retMsg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string retMsg
    {
      get { return _retMsg; }
      set { _retMsg = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgLoadUserHeadIconURI")]
  public partial class MsgLoadUserHeadIconURI : global::ProtoBuf.IExtensible
  {
    public MsgLoadUserHeadIconURI() {}
    
    private readonly global::System.Collections.Generic.List<string> _userIDs = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(1, Name=@"userIDs", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> userIDs
    {
      get { return _userIDs; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgHeadIconInfo")]
  public partial class MsgHeadIconInfo : global::ProtoBuf.IExtensible
  {
    public MsgHeadIconInfo() {}
    
    private string _userID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"userID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string userID
    {
      get { return _userID; }
      set { _userID = value; }
    }

    private uint _sex = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"sex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint sex
    {
      get { return _sex; }
      set { _sex = value; }
    }

    private string _headIconURI = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"headIconURI", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string headIconURI
    {
      get { return _headIconURI; }
      set { _headIconURI = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgLoadUserHeadIconURIReply")]
  public partial class MsgLoadUserHeadIconURIReply : global::ProtoBuf.IExtensible
  {
    public MsgLoadUserHeadIconURIReply() {}
    
    private int _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private readonly global::System.Collections.Generic.List<accessory.MsgHeadIconInfo> _headIconInfos = new global::System.Collections.Generic.List<accessory.MsgHeadIconInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"headIconInfos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<accessory.MsgHeadIconInfo> headIconInfos
    {
      get { return _headIconInfos; }
    }
  

    private string _retMsg = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"retMsg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string retMsg
    {
      get { return _retMsg; }
      set { _retMsg = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgUpdateUserMoney")]
  public partial class MsgUpdateUserMoney : global::ProtoBuf.IExtensible
  {
    public MsgUpdateUserMoney() {}
    
    private uint _diamond;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"diamond", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint diamond
    {
      get { return _diamond; }
      set { _diamond = value; }
    }

    private uint _activityType = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"activityType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint activityType
    {
      get { return _activityType; }
      set { _activityType = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgAccReplayRoom")]
  public partial class MsgAccReplayRoom : global::ProtoBuf.IExtensible
  {
    public MsgAccReplayRoom() {}
    
    private byte[] _replayRoomBytes;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"replayRoomBytes", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] replayRoomBytes
    {
      get { return _replayRoomBytes; }
      set { _replayRoomBytes = value; }
    }
    private int _recordRoomType;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"recordRoomType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int recordRoomType
    {
      get { return _recordRoomType; }
      set { _recordRoomType = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgAccLoadReplayRoomsReply")]
  public partial class MsgAccLoadReplayRoomsReply : global::ProtoBuf.IExtensible
  {
    public MsgAccLoadReplayRoomsReply() {}
    
    private readonly global::System.Collections.Generic.List<accessory.MsgAccReplayRoom> _replayRooms = new global::System.Collections.Generic.List<accessory.MsgAccReplayRoom>();
    [global::ProtoBuf.ProtoMember(1, Name=@"replayRooms", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<accessory.MsgAccReplayRoom> replayRooms
    {
      get { return _replayRooms; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgAccLoadReplayRecord")]
  public partial class MsgAccLoadReplayRecord : global::ProtoBuf.IExtensible
  {
    public MsgAccLoadReplayRecord() {}
    
    private byte[] _replayRecordBytes;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"replayRecordBytes", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] replayRecordBytes
    {
      get { return _replayRecordBytes; }
      set { _replayRecordBytes = value; }
    }
    private string _roomJSONConfig;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"roomJSONConfig", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string roomJSONConfig
    {
      get { return _roomJSONConfig; }
      set { _roomJSONConfig = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgUserInfo")]
  public partial class MsgUserInfo : global::ProtoBuf.IExtensible
  {
    public MsgUserInfo() {}
    
    private string _uid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private long _sex;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"sex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long sex
    {
      get { return _sex; }
      set { _sex = value; }
    }
    private string _protrait;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"protrait", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string protrait
    {
      get { return _protrait; }
      set { _protrait = value; }
    }
    private string _token;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"token", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string token
    {
      get { return _token; }
      set { _token = value; }
    }
    private long _diamond;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"diamond", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long diamond
    {
      get { return _diamond; }
      set { _diamond = value; }
    }
    private string _nick;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"nick", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string nick
    {
      get { return _nick; }
      set { _nick = value; }
    }
    private long _charm;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"charm", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long charm
    {
      get { return _charm; }
      set { _charm = value; }
    }
    private string _addr;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"addr", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string addr
    {
      get { return _addr; }
      set { _addr = value; }
    }
    private string _avatar;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"avatar", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string avatar
    {
      get { return _avatar; }
      set { _avatar = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgReplayRoom")]
  public partial class MsgReplayRoom : global::ProtoBuf.IExtensible
  {
    public MsgReplayRoom() {}
    
    private int _recordRoomType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"recordRoomType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int recordRoomType
    {
      get { return _recordRoomType; }
      set { _recordRoomType = value; }
    }
    private uint _startTime;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"startTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint startTime
    {
      get { return _startTime; }
      set { _startTime = value; }
    }
    private uint _endTime;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"endTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint endTime
    {
      get { return _endTime; }
      set { _endTime = value; }
    }
    private string _roomNumber;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"roomNumber", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string roomNumber
    {
      get { return _roomNumber; }
      set { _roomNumber = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"MsgError")]
    public enum MsgError
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrSuccess", Value=0)]
      ErrSuccess = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrDecode", Value=1)]
      ErrDecode = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrEncode", Value=2)]
      ErrEncode = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrRoomExist", Value=3)]
      ErrRoomExist = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrNoRoomConfig", Value=4)]
      ErrNoRoomConfig = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrServerIsFull", Value=5)]
      ErrServerIsFull = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrDecodeRoomConfig", Value=6)]
      ErrDecodeRoomConfig = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrRoomNotExist", Value=7)]
      ErrRoomNotExist = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrDatabase", Value=8)]
      ErrDatabase = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrRequestGameServerTimeOut", Value=9)]
      ErrRequestGameServerTimeOut = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrWaitGameServerSN", Value=10)]
      ErrWaitGameServerSN = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrRoomIDIsEmpty", Value=11)]
      ErrRoomIDIsEmpty = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrNotRoomCreater", Value=12)]
      ErrNotRoomCreater = 12,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrGameIsPlaying", Value=13)]
      ErrGameIsPlaying = 13,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrTokenIsEmpty", Value=14)]
      ErrTokenIsEmpty = 14,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrUserIdIsEmpty", Value=15)]
      ErrUserIdIsEmpty = 15,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrRoomNumberIsEmpty", Value=16)]
      ErrRoomNumberIsEmpty = 16,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrRoomNumberNotExist", Value=17)]
      ErrRoomNumberNotExist = 17,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrGameServerIDNotExist", Value=18)]
      ErrGameServerIDNotExist = 18,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrRoomCountIsOutOfLimit", Value=19)]
      ErrRoomCountIsOutOfLimit = 19,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrRequestInvalidParam", Value=20)]
      ErrRequestInvalidParam = 20,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrTakeoffDiamondFailedNotEnough", Value=21)]
      ErrTakeoffDiamondFailedNotEnough = 21,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrTakeoffDiamondFailedIO", Value=22)]
      ErrTakeoffDiamondFailedIO = 22,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrTakeoffDiamondFailedRepeat", Value=23)]
      ErrTakeoffDiamondFailedRepeat = 23,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrGameServerUnsupportRoomType", Value=24)]
      ErrGameServerUnsupportRoomType = 24,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrGameServerRoomExist", Value=25)]
      ErrGameServerRoomExist = 25,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrGameServerNoRoomConfig", Value=26)]
      ErrGameServerNoRoomConfig = 26,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrGameServerDecodeRoomConfig", Value=27)]
      ErrGameServerDecodeRoomConfig = 27,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrGameServerRoomNotExist", Value=28)]
      ErrGameServerRoomNotExist = 28,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrUserInOtherRoom", Value=29)]
      ErrUserInOtherRoom = 29,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrRoomIsFull", Value=30)]
      ErrRoomIsFull = 30,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrUserInBlacklist", Value=31)]
      ErrUserInBlacklist = 31,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrUserCanNotCreateCLubRoom", Value=32)]
      ErrUserCanNotCreateCLubRoom = 32,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrUserCanNotJoinCLubRoom", Value=33)]
      ErrUserCanNotJoinCLubRoom = 33,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrClubIDIsEmtpy", Value=34)]
      ErrClubIDIsEmtpy = 34,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrRoomPriceCfgNotExist", Value=35)]
      ErrRoomPriceCfgNotExist = 35,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrUserCreateRoomLock", Value=36)]
      ErrUserCreateRoomLock = 36,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrGenerateRoomNumber", Value=37)]
      ErrGenerateRoomNumber = 37
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"MessageCode")]
    public enum MessageCode
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"OPInvalid", Value=0)]
      OPInvalid = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OPCreateRoom", Value=1)]
      OPCreateRoom = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OPDeleteRoom", Value=2)]
      OPDeleteRoom = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OPChat", Value=3)]
      OPChat = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OPGetRooms", Value=4)]
      OPGetRooms = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OPLoginReply", Value=5)]
      OPLoginReply = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OPRequestRoomInfo", Value=6)]
      OPRequestRoomInfo = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OPLoadRooms", Value=7)]
      OPLoadRooms = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OPUpdateUserInfo", Value=8)]
      OPUpdateUserInfo = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OPUpdateRoomState", Value=9)]
      OPUpdateRoomState = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OPUpdateRoomList", Value=10)]
      OPUpdateRoomList = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OPVoiceData", Value=11)]
      OPVoiceData = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OPRequestUserScoreInfo", Value=12)]
      OPRequestUserScoreInfo = 12,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OPUpdateUserMoney", Value=13)]
      OPUpdateUserMoney = 13,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OPBroadcast", Value=14)]
      OPBroadcast = 14,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OPSendUserInfo", Value=15)]
      OPSendUserInfo = 15,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OPUnicast", Value=16)]
      OPUnicast = 16,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OPUpdateMail", Value=17)]
      OPUpdateMail = 17,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OPLoginGifts", Value=18)]
      OPLoginGifts = 18,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OPUpdateClubFun", Value=19)]
      OPUpdateClubFun = 19,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OPUpdateRoomPriceCfg", Value=20)]
      OPUpdateRoomPriceCfg = 20,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OPNotifyUserRoomIsFull", Value=21)]
      OPNotifyUserRoomIsFull = 21
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"RoomType")]
    public enum RoomType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"DafengMJ", Value=1)]
      DafengMJ = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GuanDang", Value=2)]
      GuanDang = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DongTaiMJ", Value=3)]
      DongTaiMJ = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"YanChengMJ", Value=4)]
      YanChengMJ = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ShaoGuanMJ", Value=5)]
      ShaoGuanMJ = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NingAnMJ", Value=6)]
      NingAnMJ = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"XinJiangGH", Value=7)]
      XinJiangGH = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DafengGZ", Value=8)]
      DafengGZ = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Dafeng7w523", Value=9)]
      Dafeng7w523 = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NiuNiu", Value=10)]
      NiuNiu = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DDZ", Value=11)]
      DDZ = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"XueLiuMJ", Value=12)]
      XueLiuMJ = 12,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LanZhouMJ", Value=13)]
      LanZhouMJ = 13,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LLanZouMJ", Value=14)]
      LLanZouMJ = 14,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZhangYeMJ", Value=15)]
      ZhangYeMJ = 15
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"OpenRoomType")]
    public enum OpenRoomType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"CreateAndEnter", Value=1)]
      CreateAndEnter = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CreateForOther", Value=2)]
      CreateForOther = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ChatDataType")]
    public enum ChatDataType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Text", Value=0)]
      Text = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Emoji", Value=1)]
      Emoji = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Voice", Value=2)]
      Voice = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Buildin", Value=3)]
      Buildin = 3
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ChatScopeType")]
    public enum ChatScopeType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"UniCast", Value=0)]
      UniCast = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"InRoom", Value=1)]
      InRoom = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"InServer", Value=2)]
      InServer = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"InAllServers", Value=3)]
      InAllServers = 3
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"LoginState")]
    public enum LoginState
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Faild", Value=0)]
      Faild = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Success", Value=1)]
      Success = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UserInBlacklist", Value=2)]
      UserInBlacklist = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ParseTokenError", Value=3)]
      ParseTokenError = 3
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ActivityType")]
    public enum ActivityType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Email", Value=1)]
      Email = 1
    }
  
}