// Code generated by protoc-gen-go. DO NOT EDIT.
// source: game_mahjong_replay.proto

package mahjong

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 回放房间中的玩家信息
type MsgReplayPlayerInfo struct {
	UserID               *string  `protobuf:"bytes,1,req,name=userID" json:"userID,omitempty"`
	Nick                 *string  `protobuf:"bytes,2,opt,name=nick" json:"nick,omitempty"`
	ChairID              *int32   `protobuf:"varint,3,req,name=chairID" json:"chairID,omitempty"`
	TotalScore           *int32   `protobuf:"varint,4,opt,name=totalScore" json:"totalScore,omitempty"`
	Gender               *uint32  `protobuf:"varint,5,opt,name=gender" json:"gender,omitempty"`
	HeadIconURI          *string  `protobuf:"bytes,6,opt,name=headIconURI" json:"headIconURI,omitempty"`
	AvatarID             *int32   `protobuf:"varint,7,opt,name=avatarID" json:"avatarID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgReplayPlayerInfo) Reset()         { *m = MsgReplayPlayerInfo{} }
func (m *MsgReplayPlayerInfo) String() string { return proto.CompactTextString(m) }
func (*MsgReplayPlayerInfo) ProtoMessage()    {}
func (*MsgReplayPlayerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae9f6c01cbb4a63c, []int{0}
}
func (m *MsgReplayPlayerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgReplayPlayerInfo.Unmarshal(m, b)
}
func (m *MsgReplayPlayerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgReplayPlayerInfo.Marshal(b, m, deterministic)
}
func (m *MsgReplayPlayerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgReplayPlayerInfo.Merge(m, src)
}
func (m *MsgReplayPlayerInfo) XXX_Size() int {
	return xxx_messageInfo_MsgReplayPlayerInfo.Size(m)
}
func (m *MsgReplayPlayerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgReplayPlayerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_MsgReplayPlayerInfo proto.InternalMessageInfo

func (m *MsgReplayPlayerInfo) GetUserID() string {
	if m != nil && m.UserID != nil {
		return *m.UserID
	}
	return ""
}

func (m *MsgReplayPlayerInfo) GetNick() string {
	if m != nil && m.Nick != nil {
		return *m.Nick
	}
	return ""
}

func (m *MsgReplayPlayerInfo) GetChairID() int32 {
	if m != nil && m.ChairID != nil {
		return *m.ChairID
	}
	return 0
}

func (m *MsgReplayPlayerInfo) GetTotalScore() int32 {
	if m != nil && m.TotalScore != nil {
		return *m.TotalScore
	}
	return 0
}

func (m *MsgReplayPlayerInfo) GetGender() uint32 {
	if m != nil && m.Gender != nil {
		return *m.Gender
	}
	return 0
}

func (m *MsgReplayPlayerInfo) GetHeadIconURI() string {
	if m != nil && m.HeadIconURI != nil {
		return *m.HeadIconURI
	}
	return ""
}

func (m *MsgReplayPlayerInfo) GetAvatarID() int32 {
	if m != nil && m.AvatarID != nil {
		return *m.AvatarID
	}
	return 0
}

// 回放记录中玩家的得分信息
type MsgReplayPlayerScoreSummary struct {
	ChairID              *int32   `protobuf:"varint,1,req,name=chairID" json:"chairID,omitempty"`
	Score                *int32   `protobuf:"varint,2,req,name=score" json:"score,omitempty"`
	WinType              *int32   `protobuf:"varint,3,req,name=winType" json:"winType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgReplayPlayerScoreSummary) Reset()         { *m = MsgReplayPlayerScoreSummary{} }
func (m *MsgReplayPlayerScoreSummary) String() string { return proto.CompactTextString(m) }
func (*MsgReplayPlayerScoreSummary) ProtoMessage()    {}
func (*MsgReplayPlayerScoreSummary) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae9f6c01cbb4a63c, []int{1}
}
func (m *MsgReplayPlayerScoreSummary) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgReplayPlayerScoreSummary.Unmarshal(m, b)
}
func (m *MsgReplayPlayerScoreSummary) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgReplayPlayerScoreSummary.Marshal(b, m, deterministic)
}
func (m *MsgReplayPlayerScoreSummary) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgReplayPlayerScoreSummary.Merge(m, src)
}
func (m *MsgReplayPlayerScoreSummary) XXX_Size() int {
	return xxx_messageInfo_MsgReplayPlayerScoreSummary.Size(m)
}
func (m *MsgReplayPlayerScoreSummary) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgReplayPlayerScoreSummary.DiscardUnknown(m)
}

var xxx_messageInfo_MsgReplayPlayerScoreSummary proto.InternalMessageInfo

func (m *MsgReplayPlayerScoreSummary) GetChairID() int32 {
	if m != nil && m.ChairID != nil {
		return *m.ChairID
	}
	return 0
}

func (m *MsgReplayPlayerScoreSummary) GetScore() int32 {
	if m != nil && m.Score != nil {
		return *m.Score
	}
	return 0
}

func (m *MsgReplayPlayerScoreSummary) GetWinType() int32 {
	if m != nil && m.WinType != nil {
		return *m.WinType
	}
	return 0
}

// 手牌回放记录概要
type MsgReplayRecordSummary struct {
	RecordUUID           *string                        `protobuf:"bytes,1,req,name=recordUUID" json:"recordUUID,omitempty"`
	PlayerScores         []*MsgReplayPlayerScoreSummary `protobuf:"bytes,2,rep,name=playerScores" json:"playerScores,omitempty"`
	EndTime              *uint32                        `protobuf:"varint,3,req,name=endTime" json:"endTime,omitempty"`
	ShareAbleID          *string                        `protobuf:"bytes,4,opt,name=shareAbleID" json:"shareAbleID,omitempty"`
	StartTime            *uint32                        `protobuf:"varint,5,opt,name=startTime" json:"startTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *MsgReplayRecordSummary) Reset()         { *m = MsgReplayRecordSummary{} }
func (m *MsgReplayRecordSummary) String() string { return proto.CompactTextString(m) }
func (*MsgReplayRecordSummary) ProtoMessage()    {}
func (*MsgReplayRecordSummary) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae9f6c01cbb4a63c, []int{2}
}
func (m *MsgReplayRecordSummary) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgReplayRecordSummary.Unmarshal(m, b)
}
func (m *MsgReplayRecordSummary) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgReplayRecordSummary.Marshal(b, m, deterministic)
}
func (m *MsgReplayRecordSummary) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgReplayRecordSummary.Merge(m, src)
}
func (m *MsgReplayRecordSummary) XXX_Size() int {
	return xxx_messageInfo_MsgReplayRecordSummary.Size(m)
}
func (m *MsgReplayRecordSummary) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgReplayRecordSummary.DiscardUnknown(m)
}

var xxx_messageInfo_MsgReplayRecordSummary proto.InternalMessageInfo

func (m *MsgReplayRecordSummary) GetRecordUUID() string {
	if m != nil && m.RecordUUID != nil {
		return *m.RecordUUID
	}
	return ""
}

func (m *MsgReplayRecordSummary) GetPlayerScores() []*MsgReplayPlayerScoreSummary {
	if m != nil {
		return m.PlayerScores
	}
	return nil
}

func (m *MsgReplayRecordSummary) GetEndTime() uint32 {
	if m != nil && m.EndTime != nil {
		return *m.EndTime
	}
	return 0
}

func (m *MsgReplayRecordSummary) GetShareAbleID() string {
	if m != nil && m.ShareAbleID != nil {
		return *m.ShareAbleID
	}
	return ""
}

func (m *MsgReplayRecordSummary) GetStartTime() uint32 {
	if m != nil && m.StartTime != nil {
		return *m.StartTime
	}
	return 0
}

// 回播房间记录
type MsgReplayRoom struct {
	RecordRoomType       *int32                    `protobuf:"varint,1,req,name=recordRoomType" json:"recordRoomType,omitempty"`
	StartTime            *uint32                   `protobuf:"varint,2,req,name=startTime" json:"startTime,omitempty"`
	EndTime              *uint32                   `protobuf:"varint,3,req,name=endTime" json:"endTime,omitempty"`
	RoomNumber           *string                   `protobuf:"bytes,4,req,name=roomNumber" json:"roomNumber,omitempty"`
	Players              []*MsgReplayPlayerInfo    `protobuf:"bytes,5,rep,name=players" json:"players,omitempty"`
	Records              []*MsgReplayRecordSummary `protobuf:"bytes,6,rep,name=records" json:"records,omitempty"`
	OwnerUserID          *string                   `protobuf:"bytes,7,opt,name=ownerUserID" json:"ownerUserID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *MsgReplayRoom) Reset()         { *m = MsgReplayRoom{} }
func (m *MsgReplayRoom) String() string { return proto.CompactTextString(m) }
func (*MsgReplayRoom) ProtoMessage()    {}
func (*MsgReplayRoom) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae9f6c01cbb4a63c, []int{3}
}
func (m *MsgReplayRoom) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgReplayRoom.Unmarshal(m, b)
}
func (m *MsgReplayRoom) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgReplayRoom.Marshal(b, m, deterministic)
}
func (m *MsgReplayRoom) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgReplayRoom.Merge(m, src)
}
func (m *MsgReplayRoom) XXX_Size() int {
	return xxx_messageInfo_MsgReplayRoom.Size(m)
}
func (m *MsgReplayRoom) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgReplayRoom.DiscardUnknown(m)
}

var xxx_messageInfo_MsgReplayRoom proto.InternalMessageInfo

func (m *MsgReplayRoom) GetRecordRoomType() int32 {
	if m != nil && m.RecordRoomType != nil {
		return *m.RecordRoomType
	}
	return 0
}

func (m *MsgReplayRoom) GetStartTime() uint32 {
	if m != nil && m.StartTime != nil {
		return *m.StartTime
	}
	return 0
}

func (m *MsgReplayRoom) GetEndTime() uint32 {
	if m != nil && m.EndTime != nil {
		return *m.EndTime
	}
	return 0
}

func (m *MsgReplayRoom) GetRoomNumber() string {
	if m != nil && m.RoomNumber != nil {
		return *m.RoomNumber
	}
	return ""
}

func (m *MsgReplayRoom) GetPlayers() []*MsgReplayPlayerInfo {
	if m != nil {
		return m.Players
	}
	return nil
}

func (m *MsgReplayRoom) GetRecords() []*MsgReplayRecordSummary {
	if m != nil {
		return m.Records
	}
	return nil
}

func (m *MsgReplayRoom) GetOwnerUserID() string {
	if m != nil && m.OwnerUserID != nil {
		return *m.OwnerUserID
	}
	return ""
}

func init() {
	proto.RegisterType((*MsgReplayPlayerInfo)(nil), "mahjong.MsgReplayPlayerInfo")
	proto.RegisterType((*MsgReplayPlayerScoreSummary)(nil), "mahjong.MsgReplayPlayerScoreSummary")
	proto.RegisterType((*MsgReplayRecordSummary)(nil), "mahjong.MsgReplayRecordSummary")
	proto.RegisterType((*MsgReplayRoom)(nil), "mahjong.MsgReplayRoom")
}

func init() { proto.RegisterFile("game_mahjong_replay.proto", fileDescriptor_ae9f6c01cbb4a63c) }

var fileDescriptor_ae9f6c01cbb4a63c = []byte{
	// 378 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0x4f, 0x0f, 0xd2, 0x30,
	0x18, 0xc6, 0xd3, 0xc1, 0x98, 0x7b, 0xf9, 0xa7, 0x25, 0x21, 0x35, 0x9a, 0xb8, 0x2c, 0x1e, 0x76,
	0x91, 0x18, 0x8f, 0xde, 0x4c, 0xb8, 0xec, 0x20, 0x31, 0xc0, 0xce, 0xa4, 0x6c, 0x75, 0x9b, 0xae,
	0xed, 0xd2, 0x0e, 0xc9, 0x3e, 0x85, 0x9f, 0xc1, 0x0f, 0xe5, 0xf7, 0x31, 0x7b, 0x87, 0x20, 0x12,
	0xe3, 0xb1, 0xed, 0xdb, 0xe7, 0x79, 0x7e, 0x4f, 0x0b, 0xcf, 0x73, 0x2e, 0xc5, 0x41, 0xf2, 0xe2,
	0x8b, 0x56, 0xf9, 0xc1, 0x88, 0xba, 0xe2, 0xed, 0xaa, 0x36, 0xba, 0xd1, 0xd4, 0xbb, 0xec, 0x86,
	0xdf, 0x09, 0x2c, 0x3e, 0xda, 0x7c, 0x8b, 0x87, 0x9f, 0x2a, 0xde, 0x0a, 0x13, 0xab, 0xcf, 0x9a,
	0xce, 0x60, 0x74, 0xb2, 0xc2, 0xc4, 0x6b, 0x46, 0x02, 0x27, 0xf2, 0xe9, 0x04, 0x86, 0xaa, 0x4c,
	0xbf, 0x32, 0x27, 0x20, 0x91, 0x4f, 0xe7, 0xe0, 0xa5, 0x05, 0x2f, 0xbb, 0xe3, 0x41, 0xe0, 0x44,
	0x2e, 0xa5, 0x00, 0x8d, 0x6e, 0x78, 0xb5, 0x4b, 0xb5, 0x11, 0x6c, 0x18, 0x90, 0xc8, 0xed, 0x24,
	0x72, 0xa1, 0x32, 0x61, 0x98, 0x1b, 0x90, 0x68, 0x4a, 0x17, 0x30, 0x2e, 0x04, 0xcf, 0xe2, 0x54,
	0xab, 0x64, 0x1b, 0xb3, 0x11, 0x2a, 0x3d, 0x85, 0x27, 0xfc, 0x1b, 0x6f, 0x78, 0x27, 0xe5, 0x75,
	0xd7, 0xc2, 0x0d, 0xbc, 0xf8, 0x2b, 0x10, 0x8a, 0xee, 0x4e, 0x52, 0x72, 0xd3, 0xfe, 0x69, 0x4d,
	0xd0, 0x7a, 0x0a, 0xae, 0x45, 0x57, 0x07, 0x97, 0x73, 0xf0, 0xce, 0xa5, 0xda, 0xb7, 0xb5, 0xe8,
	0xa3, 0x85, 0x3f, 0x08, 0x2c, 0xaf, 0x82, 0x5b, 0x91, 0x6a, 0x93, 0xfd, 0xd6, 0xa2, 0x00, 0x06,
	0x37, 0x92, 0xe4, 0x0a, 0xfa, 0x1e, 0x26, 0xf5, 0xcd, 0xd5, 0x32, 0x27, 0x18, 0x44, 0xe3, 0x77,
	0xaf, 0x57, 0x97, 0xc2, 0x56, 0xff, 0xc9, 0x26, 0x54, 0xb6, 0x2f, 0x65, 0xef, 0x8d, 0xc8, 0xb6,
	0xe0, 0x46, 0x7c, 0x38, 0x56, 0x22, 0x5e, 0x63, 0x2f, 0x3e, 0x7d, 0x06, 0xbe, 0x6d, 0xb8, 0x69,
	0x70, 0x0e, 0xab, 0x09, 0x7f, 0x12, 0x98, 0xde, 0x32, 0x6a, 0x2d, 0xe9, 0x12, 0x66, 0x7d, 0xb4,
	0x6e, 0x85, 0x34, 0x3d, 0xed, 0xdd, 0x65, 0x07, 0x4d, 0x1e, 0x5c, 0x3b, 0x2c, 0xad, 0xe5, 0xe6,
	0x24, 0x8f, 0xc2, 0xb0, 0x21, 0x62, 0xbd, 0x01, 0xaf, 0xc7, 0xb2, 0xcc, 0x45, 0xa2, 0x97, 0xff,
	0x22, 0xc2, 0xe7, 0x7f, 0x0b, 0x5e, 0x6f, 0x6f, 0xd9, 0x08, 0xc7, 0x5f, 0x3d, 0x8e, 0xdf, 0x77,
	0xb9, 0x80, 0xb1, 0x3e, 0x2b, 0x61, 0x92, 0xfe, 0xd7, 0x74, 0x6f, 0xe9, 0xff, 0x0a, 0x00, 0x00,
	0xff, 0xff, 0x18, 0x49, 0x9a, 0xfe, 0x82, 0x02, 0x00, 0x00,
}
