// Code generated by protoc-gen-go. DO NOT EDIT.
// source: game_mahjong.proto

package mahjong

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 牌的ID
// 万、筒、索东南西北白发中命名是从日本麻将copy过来的
// 日文主要是服务器的胡牌算法是日本人写的，以示感激
// 其余则是从英文copy过来的
// 英文:http://www.xqbase.com/other/mahjongg_english.htm
// 本文其余多数命名均参考上述英文对照表
type TileID int32

const (
	// enumTid_MAN = 0; // 万子
	TileID_enumTid_MAN1 TileID = 0
	TileID_enumTid_MAN2 TileID = 1
	TileID_enumTid_MAN3 TileID = 2
	TileID_enumTid_MAN4 TileID = 3
	TileID_enumTid_MAN5 TileID = 4
	TileID_enumTid_MAN6 TileID = 5
	TileID_enumTid_MAN7 TileID = 6
	TileID_enumTid_MAN8 TileID = 7
	TileID_enumTid_MAN9 TileID = 8
	// enumTid_PIN = 9;  // 筒子
	TileID_enumTid_PIN1 TileID = 9
	TileID_enumTid_PIN2 TileID = 10
	TileID_enumTid_PIN3 TileID = 11
	TileID_enumTid_PIN4 TileID = 12
	TileID_enumTid_PIN5 TileID = 13
	TileID_enumTid_PIN6 TileID = 14
	TileID_enumTid_PIN7 TileID = 15
	TileID_enumTid_PIN8 TileID = 16
	TileID_enumTid_PIN9 TileID = 17
	// enumTid_SOU = 18;  // 索子、条子
	TileID_enumTid_SOU1          TileID = 18
	TileID_enumTid_SOU2          TileID = 19
	TileID_enumTid_SOU3          TileID = 20
	TileID_enumTid_SOU4          TileID = 21
	TileID_enumTid_SOU5          TileID = 22
	TileID_enumTid_SOU6          TileID = 23
	TileID_enumTid_SOU7          TileID = 24
	TileID_enumTid_SOU8          TileID = 25
	TileID_enumTid_SOU9          TileID = 26
	TileID_enumTid_TON           TileID = 27
	TileID_enumTid_NAN           TileID = 28
	TileID_enumTid_SHA           TileID = 29
	TileID_enumTid_PEI           TileID = 30
	TileID_enumTid_HAK           TileID = 31
	TileID_enumTid_HAT           TileID = 32
	TileID_enumTid_CHU           TileID = 33
	TileID_enumTid_PLUM          TileID = 34
	TileID_enumTid_ORCHID        TileID = 35
	TileID_enumTid_BAMBOO        TileID = 36
	TileID_enumTid_CHRYSANTHEMUM TileID = 37
	TileID_enumTid_SPRING        TileID = 38
	TileID_enumTid_SUMMER        TileID = 39
	TileID_enumTid_AUTUMN        TileID = 40
	TileID_enumTid_WINTER        TileID = 41
	TileID_enumTid_MAX           TileID = 42
)

var TileID_name = map[int32]string{
	0:  "enumTid_MAN1",
	1:  "enumTid_MAN2",
	2:  "enumTid_MAN3",
	3:  "enumTid_MAN4",
	4:  "enumTid_MAN5",
	5:  "enumTid_MAN6",
	6:  "enumTid_MAN7",
	7:  "enumTid_MAN8",
	8:  "enumTid_MAN9",
	9:  "enumTid_PIN1",
	10: "enumTid_PIN2",
	11: "enumTid_PIN3",
	12: "enumTid_PIN4",
	13: "enumTid_PIN5",
	14: "enumTid_PIN6",
	15: "enumTid_PIN7",
	16: "enumTid_PIN8",
	17: "enumTid_PIN9",
	18: "enumTid_SOU1",
	19: "enumTid_SOU2",
	20: "enumTid_SOU3",
	21: "enumTid_SOU4",
	22: "enumTid_SOU5",
	23: "enumTid_SOU6",
	24: "enumTid_SOU7",
	25: "enumTid_SOU8",
	26: "enumTid_SOU9",
	27: "enumTid_TON",
	28: "enumTid_NAN",
	29: "enumTid_SHA",
	30: "enumTid_PEI",
	31: "enumTid_HAK",
	32: "enumTid_HAT",
	33: "enumTid_CHU",
	34: "enumTid_PLUM",
	35: "enumTid_ORCHID",
	36: "enumTid_BAMBOO",
	37: "enumTid_CHRYSANTHEMUM",
	38: "enumTid_SPRING",
	39: "enumTid_SUMMER",
	40: "enumTid_AUTUMN",
	41: "enumTid_WINTER",
	42: "enumTid_MAX",
}

var TileID_value = map[string]int32{
	"enumTid_MAN1":          0,
	"enumTid_MAN2":          1,
	"enumTid_MAN3":          2,
	"enumTid_MAN4":          3,
	"enumTid_MAN5":          4,
	"enumTid_MAN6":          5,
	"enumTid_MAN7":          6,
	"enumTid_MAN8":          7,
	"enumTid_MAN9":          8,
	"enumTid_PIN1":          9,
	"enumTid_PIN2":          10,
	"enumTid_PIN3":          11,
	"enumTid_PIN4":          12,
	"enumTid_PIN5":          13,
	"enumTid_PIN6":          14,
	"enumTid_PIN7":          15,
	"enumTid_PIN8":          16,
	"enumTid_PIN9":          17,
	"enumTid_SOU1":          18,
	"enumTid_SOU2":          19,
	"enumTid_SOU3":          20,
	"enumTid_SOU4":          21,
	"enumTid_SOU5":          22,
	"enumTid_SOU6":          23,
	"enumTid_SOU7":          24,
	"enumTid_SOU8":          25,
	"enumTid_SOU9":          26,
	"enumTid_TON":           27,
	"enumTid_NAN":           28,
	"enumTid_SHA":           29,
	"enumTid_PEI":           30,
	"enumTid_HAK":           31,
	"enumTid_HAT":           32,
	"enumTid_CHU":           33,
	"enumTid_PLUM":          34,
	"enumTid_ORCHID":        35,
	"enumTid_BAMBOO":        36,
	"enumTid_CHRYSANTHEMUM": 37,
	"enumTid_SPRING":        38,
	"enumTid_SUMMER":        39,
	"enumTid_AUTUMN":        40,
	"enumTid_WINTER":        41,
	"enumTid_MAX":           42,
}

func (x TileID) Enum() *TileID {
	p := new(TileID)
	*p = x
	return p
}

func (x TileID) String() string {
	return proto.EnumName(TileID_name, int32(x))
}

func (x *TileID) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(TileID_value, data, "TileID")
	if err != nil {
		return err
	}
	*x = TileID(value)
	return nil
}

func (TileID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_116d3ec96f90ca98, []int{0}
}

type MessageCode int32

const (
	MessageCode_OPInvalid            MessageCode = 0
	MessageCode_OPAction             MessageCode = 1
	MessageCode_OPActionResultNotify MessageCode = 2
	MessageCode_OPActionAllowed      MessageCode = 3
	MessageCode_OPReActionAllowed    MessageCode = 5
	MessageCode_OPDeal               MessageCode = 6
	MessageCode_OPHandOver           MessageCode = 7
	MessageCode_OPRestore            MessageCode = 8
	MessageCode_OPPlayerLeaveRoom    MessageCode = 9
	MessageCode_OPPlayerEnterRoom    MessageCode = 10
	MessageCode_OPDisbandRequest     MessageCode = 11
	MessageCode_OPDisbandNotify      MessageCode = 12
	MessageCode_OPDisbandAnswer      MessageCode = 13
	MessageCode_OPPlayerReady        MessageCode = 14
	MessageCode_OPRoomDeleted        MessageCode = 15
	MessageCode_OPRoomUpdate         MessageCode = 16
	MessageCode_OPRoomShowTips       MessageCode = 17
	MessageCode_OPGameOver           MessageCode = 18
	MessageCode_OPKickout            MessageCode = 19
	MessageCode_OPDonate             MessageCode = 20
	MessageCode_OPUpdateLocation     MessageCode = 21
	MessageCode_OP2Lobby             MessageCode = 22
	MessageCode_OPUpdatePropCfg      MessageCode = 23
	MessageCode_OPPing               MessageCode = 100
	MessageCode_OPPong               MessageCode = 101
)

var MessageCode_name = map[int32]string{
	0:   "OPInvalid",
	1:   "OPAction",
	2:   "OPActionResultNotify",
	3:   "OPActionAllowed",
	5:   "OPReActionAllowed",
	6:   "OPDeal",
	7:   "OPHandOver",
	8:   "OPRestore",
	9:   "OPPlayerLeaveRoom",
	10:  "OPPlayerEnterRoom",
	11:  "OPDisbandRequest",
	12:  "OPDisbandNotify",
	13:  "OPDisbandAnswer",
	14:  "OPPlayerReady",
	15:  "OPRoomDeleted",
	16:  "OPRoomUpdate",
	17:  "OPRoomShowTips",
	18:  "OPGameOver",
	19:  "OPKickout",
	20:  "OPDonate",
	21:  "OPUpdateLocation",
	22:  "OP2Lobby",
	23:  "OPUpdatePropCfg",
	100: "OPPing",
	101: "OPPong",
}

var MessageCode_value = map[string]int32{
	"OPInvalid":            0,
	"OPAction":             1,
	"OPActionResultNotify": 2,
	"OPActionAllowed":      3,
	"OPReActionAllowed":    5,
	"OPDeal":               6,
	"OPHandOver":           7,
	"OPRestore":            8,
	"OPPlayerLeaveRoom":    9,
	"OPPlayerEnterRoom":    10,
	"OPDisbandRequest":     11,
	"OPDisbandNotify":      12,
	"OPDisbandAnswer":      13,
	"OPPlayerReady":        14,
	"OPRoomDeleted":        15,
	"OPRoomUpdate":         16,
	"OPRoomShowTips":       17,
	"OPGameOver":           18,
	"OPKickout":            19,
	"OPDonate":             20,
	"OPUpdateLocation":     21,
	"OP2Lobby":             22,
	"OPUpdatePropCfg":      23,
	"OPPing":               100,
	"OPPong":               101,
}

func (x MessageCode) Enum() *MessageCode {
	p := new(MessageCode)
	*p = x
	return p
}

func (x MessageCode) String() string {
	return proto.EnumName(MessageCode_name, int32(x))
}

func (x *MessageCode) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(MessageCode_value, data, "MessageCode")
	if err != nil {
		return err
	}
	*x = MessageCode(value)
	return nil
}

func (MessageCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_116d3ec96f90ca98, []int{1}
}

// 牌组（面子）类型
// 例如顺子，刻子，明杠，暗杠
type MeldType int32

const (
	MeldType_enumMeldTypeSequence      MeldType = 0
	MeldType_enumMeldTypeTriplet       MeldType = 1
	MeldType_enumMeldTypeExposedKong   MeldType = 2
	MeldType_enumMeldTypeTriplet2Kong  MeldType = 3
	MeldType_enumMeldTypeConcealedKong MeldType = 4
	MeldType_enumMeldTypeSelfMeld      MeldType = 5
	MeldType_enumMeldTypeChuHH         MeldType = 6
	MeldType_enumMeldTypeChuHH1        MeldType = 7
	MeldType_enumMeldTypeWind          MeldType = 8
	MeldType_enumMeldTypePairKong      MeldType = 9
)

var MeldType_name = map[int32]string{
	0: "enumMeldTypeSequence",
	1: "enumMeldTypeTriplet",
	2: "enumMeldTypeExposedKong",
	3: "enumMeldTypeTriplet2Kong",
	4: "enumMeldTypeConcealedKong",
	5: "enumMeldTypeSelfMeld",
	6: "enumMeldTypeChuHH",
	7: "enumMeldTypeChuHH1",
	8: "enumMeldTypeWind",
	9: "enumMeldTypePairKong",
}

var MeldType_value = map[string]int32{
	"enumMeldTypeSequence":      0,
	"enumMeldTypeTriplet":       1,
	"enumMeldTypeExposedKong":   2,
	"enumMeldTypeTriplet2Kong":  3,
	"enumMeldTypeConcealedKong": 4,
	"enumMeldTypeSelfMeld":      5,
	"enumMeldTypeChuHH":         6,
	"enumMeldTypeChuHH1":        7,
	"enumMeldTypeWind":          8,
	"enumMeldTypePairKong":      9,
}

func (x MeldType) Enum() *MeldType {
	p := new(MeldType)
	*p = x
	return p
}

func (x MeldType) String() string {
	return proto.EnumName(MeldType_name, int32(x))
}

func (x *MeldType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(MeldType_value, data, "MeldType")
	if err != nil {
		return err
	}
	*x = MeldType(value)
	return nil
}

func (MeldType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_116d3ec96f90ca98, []int{2}
}

// 动作类型
// 注意为了能够用一个int合并多个动作
// 因此所有动作的值均为二进制bit field独立
type ActionType int32

const (
	ActionType_enumActionType_SKIP           ActionType = 1
	ActionType_enumActionType_DISCARD        ActionType = 2
	ActionType_enumActionType_DRAW           ActionType = 4
	ActionType_enumActionType_CHOW           ActionType = 8
	ActionType_enumActionType_PONG           ActionType = 16
	ActionType_enumActionType_KONG_Exposed   ActionType = 32
	ActionType_enumActionType_KONG_Concealed ActionType = 64
	ActionType_enumActionType_WIN_Chuck      ActionType = 128
	ActionType_enumActionType_WIN_SelfDrawn  ActionType = 256
	ActionType_enumActionType_KONG_Triplet2  ActionType = 512
	ActionType_enumActionType_FirstReadyHand ActionType = 1024
	ActionType_enumActionType_ReadyHand      ActionType = 2048
	ActionType_enumActionType_CustomA        ActionType = 4096
	ActionType_enumActionType_CustomB        ActionType = 8192
	ActionType_enumActionType_CustomC        ActionType = 16384
	ActionType_enumActionType_CustomD        ActionType = 32768
)

var ActionType_name = map[int32]string{
	1:     "enumActionType_SKIP",
	2:     "enumActionType_DISCARD",
	4:     "enumActionType_DRAW",
	8:     "enumActionType_CHOW",
	16:    "enumActionType_PONG",
	32:    "enumActionType_KONG_Exposed",
	64:    "enumActionType_KONG_Concealed",
	128:   "enumActionType_WIN_Chuck",
	256:   "enumActionType_WIN_SelfDrawn",
	512:   "enumActionType_KONG_Triplet2",
	1024:  "enumActionType_FirstReadyHand",
	2048:  "enumActionType_ReadyHand",
	4096:  "enumActionType_CustomA",
	8192:  "enumActionType_CustomB",
	16384: "enumActionType_CustomC",
	32768: "enumActionType_CustomD",
}

var ActionType_value = map[string]int32{
	"enumActionType_SKIP":           1,
	"enumActionType_DISCARD":        2,
	"enumActionType_DRAW":           4,
	"enumActionType_CHOW":           8,
	"enumActionType_PONG":           16,
	"enumActionType_KONG_Exposed":   32,
	"enumActionType_KONG_Concealed": 64,
	"enumActionType_WIN_Chuck":      128,
	"enumActionType_WIN_SelfDrawn":  256,
	"enumActionType_KONG_Triplet2":  512,
	"enumActionType_FirstReadyHand": 1024,
	"enumActionType_ReadyHand":      2048,
	"enumActionType_CustomA":        4096,
	"enumActionType_CustomB":        8192,
	"enumActionType_CustomC":        16384,
	"enumActionType_CustomD":        32768,
}

func (x ActionType) Enum() *ActionType {
	p := new(ActionType)
	*p = x
	return p
}

func (x ActionType) String() string {
	return proto.EnumName(ActionType_name, int32(x))
}

func (x *ActionType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ActionType_value, data, "ActionType")
	if err != nil {
		return err
	}
	*x = ActionType(value)
	return nil
}

func (ActionType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_116d3ec96f90ca98, []int{3}
}

// 一手牌局结束
// 可能的结果是：流局、有人自摸胡牌、有人放铳其他人胡牌
type HandOverType int32

const (
	HandOverType_enumHandOverType_None          HandOverType = 0
	HandOverType_enumHandOverType_Win_SelfDrawn HandOverType = 1
	HandOverType_enumHandOverType_Win_Chuck     HandOverType = 2
	HandOverType_enumHandOverType_Chucker       HandOverType = 3
	HandOverType_enumHandOverType_Konger        HandOverType = 4
	HandOverType_enumHandOverType_Win_RobKong   HandOverType = 5
)

var HandOverType_name = map[int32]string{
	0: "enumHandOverType_None",
	1: "enumHandOverType_Win_SelfDrawn",
	2: "enumHandOverType_Win_Chuck",
	3: "enumHandOverType_Chucker",
	4: "enumHandOverType_Konger",
	5: "enumHandOverType_Win_RobKong",
}

var HandOverType_value = map[string]int32{
	"enumHandOverType_None":          0,
	"enumHandOverType_Win_SelfDrawn": 1,
	"enumHandOverType_Win_Chuck":     2,
	"enumHandOverType_Chucker":       3,
	"enumHandOverType_Konger":        4,
	"enumHandOverType_Win_RobKong":   5,
}

func (x HandOverType) Enum() *HandOverType {
	p := new(HandOverType)
	*p = x
	return p
}

func (x HandOverType) String() string {
	return proto.EnumName(HandOverType_name, int32(x))
}

func (x *HandOverType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(HandOverType_value, data, "HandOverType")
	if err != nil {
		return err
	}
	*x = HandOverType(value)
	return nil
}

func (HandOverType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_116d3ec96f90ca98, []int{4}
}

// 消息包装，把其他消息体格式化为byte array，
// 加上消息码构成一个GameMessage，便于解析
type GameMessage struct {
	Ops                  *int32   `protobuf:"varint,1,req,name=Ops" json:"Ops,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=Data" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameMessage) Reset()         { *m = GameMessage{} }
func (m *GameMessage) String() string { return proto.CompactTextString(m) }
func (*GameMessage) ProtoMessage()    {}
func (*GameMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_116d3ec96f90ca98, []int{0}
}
func (m *GameMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameMessage.Unmarshal(m, b)
}
func (m *GameMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameMessage.Marshal(b, m, deterministic)
}
func (m *GameMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameMessage.Merge(m, src)
}
func (m *GameMessage) XXX_Size() int {
	return xxx_messageInfo_GameMessage.Size(m)
}
func (m *GameMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_GameMessage.DiscardUnknown(m)
}

var xxx_messageInfo_GameMessage proto.InternalMessageInfo

func (m *GameMessage) GetOps() int32 {
	if m != nil && m.Ops != nil {
		return *m.Ops
	}
	return 0
}

func (m *GameMessage) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

// 牌组
type MsgMeldTile struct {
	MeldType             *int32   `protobuf:"varint,1,req,name=meldType" json:"meldType,omitempty"`
	Tile1                *int32   `protobuf:"varint,2,req,name=tile1" json:"tile1,omitempty"`
	Contributor          *int32   `protobuf:"varint,3,opt,name=contributor" json:"contributor,omitempty"`
	ChowTile             *int32   `protobuf:"varint,4,opt,name=chowTile" json:"chowTile,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgMeldTile) Reset()         { *m = MsgMeldTile{} }
func (m *MsgMeldTile) String() string { return proto.CompactTextString(m) }
func (*MsgMeldTile) ProtoMessage()    {}
func (*MsgMeldTile) Descriptor() ([]byte, []int) {
	return fileDescriptor_116d3ec96f90ca98, []int{1}
}
func (m *MsgMeldTile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgMeldTile.Unmarshal(m, b)
}
func (m *MsgMeldTile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgMeldTile.Marshal(b, m, deterministic)
}
func (m *MsgMeldTile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgMeldTile.Merge(m, src)
}
func (m *MsgMeldTile) XXX_Size() int {
	return xxx_messageInfo_MsgMeldTile.Size(m)
}
func (m *MsgMeldTile) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgMeldTile.DiscardUnknown(m)
}

var xxx_messageInfo_MsgMeldTile proto.InternalMessageInfo

func (m *MsgMeldTile) GetMeldType() int32 {
	if m != nil && m.MeldType != nil {
		return *m.MeldType
	}
	return 0
}

func (m *MsgMeldTile) GetTile1() int32 {
	if m != nil && m.Tile1 != nil {
		return *m.Tile1
	}
	return 0
}

func (m *MsgMeldTile) GetContributor() int32 {
	if m != nil && m.Contributor != nil {
		return *m.Contributor
	}
	return 0
}

func (m *MsgMeldTile) GetChowTile() int32 {
	if m != nil && m.ChowTile != nil {
		return *m.ChowTile
	}
	return 0
}

// 玩家麻将牌列表
// 包含了所有客户端需要用于展示的列表
// 客户端根据需要读取对应的列表进行展示
// 对于自己，所有列表都有数据
// 别人的牌，则只有部分列表有数据（例如花牌列表）
type MsgPlayerTileList struct {
	ChairID         *int32  `protobuf:"varint,1,req,name=chairID" json:"chairID,omitempty"`
	TileCountInHand *int32  `protobuf:"varint,2,req,name=tileCountInHand" json:"tileCountInHand,omitempty"`
	TilesHand       []int32 `protobuf:"varint,3,rep,name=tilesHand" json:"tilesHand,omitempty"`
	TilesFlower     []int32 `protobuf:"varint,4,rep,name=tilesFlower" json:"tilesFlower,omitempty"`
	TilesDiscard    []int32 `protobuf:"varint,5,rep,name=tilesDiscard" json:"tilesDiscard,omitempty"`
	// 牌组（顺子，刻子，杠牌）列表，需要明牌示人
	// 对于暗杠牌，客户端需要暗牌示人
	// 落地牌组（也即是吃椪杠牌组，需要显示给所有人看到，注意暗杠仅需要一个标记）
	Melds                []*MsgMeldTile `protobuf:"bytes,6,rep,name=melds" json:"melds,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *MsgPlayerTileList) Reset()         { *m = MsgPlayerTileList{} }
func (m *MsgPlayerTileList) String() string { return proto.CompactTextString(m) }
func (*MsgPlayerTileList) ProtoMessage()    {}
func (*MsgPlayerTileList) Descriptor() ([]byte, []int) {
	return fileDescriptor_116d3ec96f90ca98, []int{2}
}
func (m *MsgPlayerTileList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgPlayerTileList.Unmarshal(m, b)
}
func (m *MsgPlayerTileList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgPlayerTileList.Marshal(b, m, deterministic)
}
func (m *MsgPlayerTileList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgPlayerTileList.Merge(m, src)
}
func (m *MsgPlayerTileList) XXX_Size() int {
	return xxx_messageInfo_MsgPlayerTileList.Size(m)
}
func (m *MsgPlayerTileList) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgPlayerTileList.DiscardUnknown(m)
}

var xxx_messageInfo_MsgPlayerTileList proto.InternalMessageInfo

func (m *MsgPlayerTileList) GetChairID() int32 {
	if m != nil && m.ChairID != nil {
		return *m.ChairID
	}
	return 0
}

func (m *MsgPlayerTileList) GetTileCountInHand() int32 {
	if m != nil && m.TileCountInHand != nil {
		return *m.TileCountInHand
	}
	return 0
}

func (m *MsgPlayerTileList) GetTilesHand() []int32 {
	if m != nil {
		return m.TilesHand
	}
	return nil
}

func (m *MsgPlayerTileList) GetTilesFlower() []int32 {
	if m != nil {
		return m.TilesFlower
	}
	return nil
}

func (m *MsgPlayerTileList) GetTilesDiscard() []int32 {
	if m != nil {
		return m.TilesDiscard
	}
	return nil
}

func (m *MsgPlayerTileList) GetMelds() []*MsgMeldTile {
	if m != nil {
		return m.Melds
	}
	return nil
}

// 发牌
// 服务器下发给客户端
// 客户端收到消息后，做如下处理：
// 1. 显示自己的牌
// 2. 显示其他人的牌（暗牌，庄家14张）
// 3. 显示庄家
// 4. 显示所有人的花牌
type MsgDeal struct {
	BankerChairID        *int32               `protobuf:"varint,1,req,name=bankerChairID" json:"bankerChairID,omitempty"`
	WindFlowerID         *int32               `protobuf:"varint,2,req,name=windFlowerID" json:"windFlowerID,omitempty"`
	PlayerTileLists      []*MsgPlayerTileList `protobuf:"bytes,3,rep,name=playerTileLists" json:"playerTileLists,omitempty"`
	TilesInWall          *int32               `protobuf:"varint,4,req,name=tilesInWall" json:"tilesInWall,omitempty"`
	Dice1                *int32               `protobuf:"varint,5,opt,name=dice1" json:"dice1,omitempty"`
	Dice2                *int32               `protobuf:"varint,6,opt,name=dice2" json:"dice2,omitempty"`
	IsContinuousBanker   *bool                `protobuf:"varint,7,opt,name=isContinuousBanker" json:"isContinuousBanker,omitempty"`
	Markup               *int32               `protobuf:"varint,8,opt,name=markup" json:"markup,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *MsgDeal) Reset()         { *m = MsgDeal{} }
func (m *MsgDeal) String() string { return proto.CompactTextString(m) }
func (*MsgDeal) ProtoMessage()    {}
func (*MsgDeal) Descriptor() ([]byte, []int) {
	return fileDescriptor_116d3ec96f90ca98, []int{3}
}
func (m *MsgDeal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgDeal.Unmarshal(m, b)
}
func (m *MsgDeal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgDeal.Marshal(b, m, deterministic)
}
func (m *MsgDeal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDeal.Merge(m, src)
}
func (m *MsgDeal) XXX_Size() int {
	return xxx_messageInfo_MsgDeal.Size(m)
}
func (m *MsgDeal) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDeal.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDeal proto.InternalMessageInfo

func (m *MsgDeal) GetBankerChairID() int32 {
	if m != nil && m.BankerChairID != nil {
		return *m.BankerChairID
	}
	return 0
}

func (m *MsgDeal) GetWindFlowerID() int32 {
	if m != nil && m.WindFlowerID != nil {
		return *m.WindFlowerID
	}
	return 0
}

func (m *MsgDeal) GetPlayerTileLists() []*MsgPlayerTileList {
	if m != nil {
		return m.PlayerTileLists
	}
	return nil
}

func (m *MsgDeal) GetTilesInWall() int32 {
	if m != nil && m.TilesInWall != nil {
		return *m.TilesInWall
	}
	return 0
}

func (m *MsgDeal) GetDice1() int32 {
	if m != nil && m.Dice1 != nil {
		return *m.Dice1
	}
	return 0
}

func (m *MsgDeal) GetDice2() int32 {
	if m != nil && m.Dice2 != nil {
		return *m.Dice2
	}
	return 0
}

func (m *MsgDeal) GetIsContinuousBanker() bool {
	if m != nil && m.IsContinuousBanker != nil {
		return *m.IsContinuousBanker
	}
	return false
}

func (m *MsgDeal) GetMarkup() int32 {
	if m != nil && m.Markup != nil {
		return *m.Markup
	}
	return 0
}

// 听牌提示
type MsgReadyHandTips struct {
	TargetTile           *int32   `protobuf:"varint,1,req,name=targetTile" json:"targetTile,omitempty"`
	ReadyHandList        []int32  `protobuf:"varint,2,rep,name=readyHandList" json:"readyHandList,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgReadyHandTips) Reset()         { *m = MsgReadyHandTips{} }
func (m *MsgReadyHandTips) String() string { return proto.CompactTextString(m) }
func (*MsgReadyHandTips) ProtoMessage()    {}
func (*MsgReadyHandTips) Descriptor() ([]byte, []int) {
	return fileDescriptor_116d3ec96f90ca98, []int{4}
}
func (m *MsgReadyHandTips) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgReadyHandTips.Unmarshal(m, b)
}
func (m *MsgReadyHandTips) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgReadyHandTips.Marshal(b, m, deterministic)
}
func (m *MsgReadyHandTips) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgReadyHandTips.Merge(m, src)
}
func (m *MsgReadyHandTips) XXX_Size() int {
	return xxx_messageInfo_MsgReadyHandTips.Size(m)
}
func (m *MsgReadyHandTips) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgReadyHandTips.DiscardUnknown(m)
}

var xxx_messageInfo_MsgReadyHandTips proto.InternalMessageInfo

func (m *MsgReadyHandTips) GetTargetTile() int32 {
	if m != nil && m.TargetTile != nil {
		return *m.TargetTile
	}
	return 0
}

func (m *MsgReadyHandTips) GetReadyHandList() []int32 {
	if m != nil {
		return m.ReadyHandList
	}
	return nil
}

// 服务器准许客户端做游戏动作
// 服务器发送给客户端
// 客户端收到本消息后，于界面上提示或者允许用户操作
// 在用户操作完成后（或者超时），发送MsgPlayerAction消息给服务器
type MsgAllowPlayerAction struct {
	QaIndex              *int32              `protobuf:"varint,1,req,name=qaIndex" json:"qaIndex,omitempty"`
	ActionChairID        *int32              `protobuf:"varint,2,req,name=actionChairID" json:"actionChairID,omitempty"`
	AllowedActions       *int32              `protobuf:"varint,3,req,name=allowedActions" json:"allowedActions,omitempty"`
	TimeoutInSeconds     *int32              `protobuf:"varint,4,opt,name=timeoutInSeconds" json:"timeoutInSeconds,omitempty"`
	TipsForAction        []*MsgReadyHandTips `protobuf:"bytes,5,rep,name=tipsForAction" json:"tipsForAction,omitempty"`
	MeldsForAction       []*MsgMeldTile      `protobuf:"bytes,6,rep,name=meldsForAction" json:"meldsForAction,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *MsgAllowPlayerAction) Reset()         { *m = MsgAllowPlayerAction{} }
func (m *MsgAllowPlayerAction) String() string { return proto.CompactTextString(m) }
func (*MsgAllowPlayerAction) ProtoMessage()    {}
func (*MsgAllowPlayerAction) Descriptor() ([]byte, []int) {
	return fileDescriptor_116d3ec96f90ca98, []int{5}
}
func (m *MsgAllowPlayerAction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgAllowPlayerAction.Unmarshal(m, b)
}
func (m *MsgAllowPlayerAction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgAllowPlayerAction.Marshal(b, m, deterministic)
}
func (m *MsgAllowPlayerAction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAllowPlayerAction.Merge(m, src)
}
func (m *MsgAllowPlayerAction) XXX_Size() int {
	return xxx_messageInfo_MsgAllowPlayerAction.Size(m)
}
func (m *MsgAllowPlayerAction) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAllowPlayerAction.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAllowPlayerAction proto.InternalMessageInfo

func (m *MsgAllowPlayerAction) GetQaIndex() int32 {
	if m != nil && m.QaIndex != nil {
		return *m.QaIndex
	}
	return 0
}

func (m *MsgAllowPlayerAction) GetActionChairID() int32 {
	if m != nil && m.ActionChairID != nil {
		return *m.ActionChairID
	}
	return 0
}

func (m *MsgAllowPlayerAction) GetAllowedActions() int32 {
	if m != nil && m.AllowedActions != nil {
		return *m.AllowedActions
	}
	return 0
}

func (m *MsgAllowPlayerAction) GetTimeoutInSeconds() int32 {
	if m != nil && m.TimeoutInSeconds != nil {
		return *m.TimeoutInSeconds
	}
	return 0
}

func (m *MsgAllowPlayerAction) GetTipsForAction() []*MsgReadyHandTips {
	if m != nil {
		return m.TipsForAction
	}
	return nil
}

func (m *MsgAllowPlayerAction) GetMeldsForAction() []*MsgMeldTile {
	if m != nil {
		return m.MeldsForAction
	}
	return nil
}

// 服务器准许客户端做游戏动作
// 服务器发送给客户端
// 客户端收到本消息后，于界面上提示或者允许用户操作
// 在用户操作完成后（或者超时），发送MsgPlayerAction消息给服务器
type MsgAllowPlayerReAction struct {
	QaIndex              *int32         `protobuf:"varint,1,req,name=qaIndex" json:"qaIndex,omitempty"`
	ActionChairID        *int32         `protobuf:"varint,2,req,name=actionChairID" json:"actionChairID,omitempty"`
	AllowedActions       *int32         `protobuf:"varint,3,req,name=allowedActions" json:"allowedActions,omitempty"`
	TimeoutInSeconds     *int32         `protobuf:"varint,4,opt,name=timeoutInSeconds" json:"timeoutInSeconds,omitempty"`
	MeldsForAction       []*MsgMeldTile `protobuf:"bytes,5,rep,name=meldsForAction" json:"meldsForAction,omitempty"`
	VictimTileID         *int32         `protobuf:"varint,6,req,name=victimTileID" json:"victimTileID,omitempty"`
	VictimChairID        *int32         `protobuf:"varint,7,req,name=victimChairID" json:"victimChairID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *MsgAllowPlayerReAction) Reset()         { *m = MsgAllowPlayerReAction{} }
func (m *MsgAllowPlayerReAction) String() string { return proto.CompactTextString(m) }
func (*MsgAllowPlayerReAction) ProtoMessage()    {}
func (*MsgAllowPlayerReAction) Descriptor() ([]byte, []int) {
	return fileDescriptor_116d3ec96f90ca98, []int{6}
}
func (m *MsgAllowPlayerReAction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgAllowPlayerReAction.Unmarshal(m, b)
}
func (m *MsgAllowPlayerReAction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgAllowPlayerReAction.Marshal(b, m, deterministic)
}
func (m *MsgAllowPlayerReAction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAllowPlayerReAction.Merge(m, src)
}
func (m *MsgAllowPlayerReAction) XXX_Size() int {
	return xxx_messageInfo_MsgAllowPlayerReAction.Size(m)
}
func (m *MsgAllowPlayerReAction) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAllowPlayerReAction.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAllowPlayerReAction proto.InternalMessageInfo

func (m *MsgAllowPlayerReAction) GetQaIndex() int32 {
	if m != nil && m.QaIndex != nil {
		return *m.QaIndex
	}
	return 0
}

func (m *MsgAllowPlayerReAction) GetActionChairID() int32 {
	if m != nil && m.ActionChairID != nil {
		return *m.ActionChairID
	}
	return 0
}

func (m *MsgAllowPlayerReAction) GetAllowedActions() int32 {
	if m != nil && m.AllowedActions != nil {
		return *m.AllowedActions
	}
	return 0
}

func (m *MsgAllowPlayerReAction) GetTimeoutInSeconds() int32 {
	if m != nil && m.TimeoutInSeconds != nil {
		return *m.TimeoutInSeconds
	}
	return 0
}

func (m *MsgAllowPlayerReAction) GetMeldsForAction() []*MsgMeldTile {
	if m != nil {
		return m.MeldsForAction
	}
	return nil
}

func (m *MsgAllowPlayerReAction) GetVictimTileID() int32 {
	if m != nil && m.VictimTileID != nil {
		return *m.VictimTileID
	}
	return 0
}

func (m *MsgAllowPlayerReAction) GetVictimChairID() int32 {
	if m != nil && m.VictimChairID != nil {
		return *m.VictimChairID
	}
	return 0
}

// 玩家执行动作
// 客户端必须是收到服务器允许动作消息并
// 通过界面让玩家完成操作之后，通过该消息通知服务器用户执行了动作
// 客户端需要填写正确的qaIndex，以及action（这两个参数都是从服务器下发）
type MsgPlayerAction struct {
	// QA索引，该索引是服务器通过出牌许可消息下发的，客户端需要回填于此
	// QA索引的目的是为了服务器对消息的控制：服务器对于新收到的消息如果其QA索引
	// 不等于服务器当前期待的QA索引，服务器将会抛弃该消息
	// QA索引就是流水号，QA代表Question&Answer
	// 本文档其余处QA索引意义与此一致
	QaIndex              *int32   `protobuf:"varint,1,req,name=qaIndex" json:"qaIndex,omitempty"`
	Action               *int32   `protobuf:"varint,2,req,name=action" json:"action,omitempty"`
	Flags                *int32   `protobuf:"varint,3,opt,name=flags" json:"flags,omitempty"`
	Tile                 *int32   `protobuf:"varint,4,opt,name=tile" json:"tile,omitempty"`
	MeldType             *int32   `protobuf:"varint,5,opt,name=meldType" json:"meldType,omitempty"`
	MeldTile1            *int32   `protobuf:"varint,6,opt,name=meldTile1" json:"meldTile1,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgPlayerAction) Reset()         { *m = MsgPlayerAction{} }
func (m *MsgPlayerAction) String() string { return proto.CompactTextString(m) }
func (*MsgPlayerAction) ProtoMessage()    {}
func (*MsgPlayerAction) Descriptor() ([]byte, []int) {
	return fileDescriptor_116d3ec96f90ca98, []int{7}
}
func (m *MsgPlayerAction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgPlayerAction.Unmarshal(m, b)
}
func (m *MsgPlayerAction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgPlayerAction.Marshal(b, m, deterministic)
}
func (m *MsgPlayerAction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgPlayerAction.Merge(m, src)
}
func (m *MsgPlayerAction) XXX_Size() int {
	return xxx_messageInfo_MsgPlayerAction.Size(m)
}
func (m *MsgPlayerAction) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgPlayerAction.DiscardUnknown(m)
}

var xxx_messageInfo_MsgPlayerAction proto.InternalMessageInfo

func (m *MsgPlayerAction) GetQaIndex() int32 {
	if m != nil && m.QaIndex != nil {
		return *m.QaIndex
	}
	return 0
}

func (m *MsgPlayerAction) GetAction() int32 {
	if m != nil && m.Action != nil {
		return *m.Action
	}
	return 0
}

func (m *MsgPlayerAction) GetFlags() int32 {
	if m != nil && m.Flags != nil {
		return *m.Flags
	}
	return 0
}

func (m *MsgPlayerAction) GetTile() int32 {
	if m != nil && m.Tile != nil {
		return *m.Tile
	}
	return 0
}

func (m *MsgPlayerAction) GetMeldType() int32 {
	if m != nil && m.MeldType != nil {
		return *m.MeldType
	}
	return 0
}

func (m *MsgPlayerAction) GetMeldTile1() int32 {
	if m != nil && m.MeldTile1 != nil {
		return *m.MeldTile1
	}
	return 0
}

// 服务器通知所有玩家某个玩家进行了何种动作
// 客户端收到消息后，对界面进行更新或者播放对应动作动画
type MsgActionResultNotify struct {
	TargetChairID        *int32       `protobuf:"varint,1,req,name=targetChairID" json:"targetChairID,omitempty"`
	Action               *int32       `protobuf:"varint,2,req,name=action" json:"action,omitempty"`
	ActionTile           *int32       `protobuf:"varint,3,opt,name=actionTile" json:"actionTile,omitempty"`
	ActionMeld           *MsgMeldTile `protobuf:"bytes,4,opt,name=actionMeld" json:"actionMeld,omitempty"`
	NewFlowers           []int32      `protobuf:"varint,5,rep,name=newFlowers" json:"newFlowers,omitempty"`
	TilesInWall          *int32       `protobuf:"varint,6,opt,name=tilesInWall" json:"tilesInWall,omitempty"`
	WaitDiscardReAction  *bool        `protobuf:"varint,7,opt,name=waitDiscardReAction" json:"waitDiscardReAction,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *MsgActionResultNotify) Reset()         { *m = MsgActionResultNotify{} }
func (m *MsgActionResultNotify) String() string { return proto.CompactTextString(m) }
func (*MsgActionResultNotify) ProtoMessage()    {}
func (*MsgActionResultNotify) Descriptor() ([]byte, []int) {
	return fileDescriptor_116d3ec96f90ca98, []int{8}
}
func (m *MsgActionResultNotify) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgActionResultNotify.Unmarshal(m, b)
}
func (m *MsgActionResultNotify) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgActionResultNotify.Marshal(b, m, deterministic)
}
func (m *MsgActionResultNotify) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgActionResultNotify.Merge(m, src)
}
func (m *MsgActionResultNotify) XXX_Size() int {
	return xxx_messageInfo_MsgActionResultNotify.Size(m)
}
func (m *MsgActionResultNotify) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgActionResultNotify.DiscardUnknown(m)
}

var xxx_messageInfo_MsgActionResultNotify proto.InternalMessageInfo

func (m *MsgActionResultNotify) GetTargetChairID() int32 {
	if m != nil && m.TargetChairID != nil {
		return *m.TargetChairID
	}
	return 0
}

func (m *MsgActionResultNotify) GetAction() int32 {
	if m != nil && m.Action != nil {
		return *m.Action
	}
	return 0
}

func (m *MsgActionResultNotify) GetActionTile() int32 {
	if m != nil && m.ActionTile != nil {
		return *m.ActionTile
	}
	return 0
}

func (m *MsgActionResultNotify) GetActionMeld() *MsgMeldTile {
	if m != nil {
		return m.ActionMeld
	}
	return nil
}

func (m *MsgActionResultNotify) GetNewFlowers() []int32 {
	if m != nil {
		return m.NewFlowers
	}
	return nil
}

func (m *MsgActionResultNotify) GetTilesInWall() int32 {
	if m != nil && m.TilesInWall != nil {
		return *m.TilesInWall
	}
	return 0
}

func (m *MsgActionResultNotify) GetWaitDiscardReAction() bool {
	if m != nil && m.WaitDiscardReAction != nil {
		return *m.WaitDiscardReAction
	}
	return false
}

// 掉线恢复
type MsgRestore struct {
	MsgDeal              *MsgDeal `protobuf:"bytes,1,req,name=msgDeal" json:"msgDeal,omitempty"`
	ReadyHandChairs      []int32  `protobuf:"varint,2,rep,name=readyHandChairs" json:"readyHandChairs,omitempty"`
	LastDiscaredChairID  *int32   `protobuf:"varint,3,opt,name=lastDiscaredChairID" json:"lastDiscaredChairID,omitempty"`
	IsMeNewDraw          *bool    `protobuf:"varint,4,opt,name=isMeNewDraw" json:"isMeNewDraw,omitempty"`
	WaitDiscardReAction  *bool    `protobuf:"varint,5,opt,name=waitDiscardReAction" json:"waitDiscardReAction,omitempty"`
	FlyReadyHandChairs   []int32  `protobuf:"varint,6,rep,name=flyReadyHandChairs" json:"flyReadyHandChairs,omitempty"`
	Extra                []byte   `protobuf:"bytes,7,opt,name=extra" json:"extra,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgRestore) Reset()         { *m = MsgRestore{} }
func (m *MsgRestore) String() string { return proto.CompactTextString(m) }
func (*MsgRestore) ProtoMessage()    {}
func (*MsgRestore) Descriptor() ([]byte, []int) {
	return fileDescriptor_116d3ec96f90ca98, []int{9}
}
func (m *MsgRestore) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgRestore.Unmarshal(m, b)
}
func (m *MsgRestore) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgRestore.Marshal(b, m, deterministic)
}
func (m *MsgRestore) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRestore.Merge(m, src)
}
func (m *MsgRestore) XXX_Size() int {
	return xxx_messageInfo_MsgRestore.Size(m)
}
func (m *MsgRestore) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRestore.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRestore proto.InternalMessageInfo

func (m *MsgRestore) GetMsgDeal() *MsgDeal {
	if m != nil {
		return m.MsgDeal
	}
	return nil
}

func (m *MsgRestore) GetReadyHandChairs() []int32 {
	if m != nil {
		return m.ReadyHandChairs
	}
	return nil
}

func (m *MsgRestore) GetLastDiscaredChairID() int32 {
	if m != nil && m.LastDiscaredChairID != nil {
		return *m.LastDiscaredChairID
	}
	return 0
}

func (m *MsgRestore) GetIsMeNewDraw() bool {
	if m != nil && m.IsMeNewDraw != nil {
		return *m.IsMeNewDraw
	}
	return false
}

func (m *MsgRestore) GetWaitDiscardReAction() bool {
	if m != nil && m.WaitDiscardReAction != nil {
		return *m.WaitDiscardReAction
	}
	return false
}

func (m *MsgRestore) GetFlyReadyHandChairs() []int32 {
	if m != nil {
		return m.FlyReadyHandChairs
	}
	return nil
}

func (m *MsgRestore) GetExtra() []byte {
	if m != nil {
		return m.Extra
	}
	return nil
}

// 大胡者的计分
type MsgPlayerScoreGreatWin struct {
	BaseWinScore          *int32   `protobuf:"varint,1,req,name=baseWinScore" json:"baseWinScore,omitempty"`
	GreatWinType          *int32   `protobuf:"varint,2,req,name=greatWinType" json:"greatWinType,omitempty"`
	GreatWinPoints        *int32   `protobuf:"varint,3,req,name=greatWinPoints" json:"greatWinPoints,omitempty"`
	TrimGreatWinPoints    *int32   `protobuf:"varint,4,req,name=trimGreatWinPoints" json:"trimGreatWinPoints,omitempty"`
	ContinuousBankerExtra *int32   `protobuf:"varint,5,opt,name=continuousBankerExtra" json:"continuousBankerExtra,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *MsgPlayerScoreGreatWin) Reset()         { *m = MsgPlayerScoreGreatWin{} }
func (m *MsgPlayerScoreGreatWin) String() string { return proto.CompactTextString(m) }
func (*MsgPlayerScoreGreatWin) ProtoMessage()    {}
func (*MsgPlayerScoreGreatWin) Descriptor() ([]byte, []int) {
	return fileDescriptor_116d3ec96f90ca98, []int{10}
}
func (m *MsgPlayerScoreGreatWin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgPlayerScoreGreatWin.Unmarshal(m, b)
}
func (m *MsgPlayerScoreGreatWin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgPlayerScoreGreatWin.Marshal(b, m, deterministic)
}
func (m *MsgPlayerScoreGreatWin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgPlayerScoreGreatWin.Merge(m, src)
}
func (m *MsgPlayerScoreGreatWin) XXX_Size() int {
	return xxx_messageInfo_MsgPlayerScoreGreatWin.Size(m)
}
func (m *MsgPlayerScoreGreatWin) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgPlayerScoreGreatWin.DiscardUnknown(m)
}

var xxx_messageInfo_MsgPlayerScoreGreatWin proto.InternalMessageInfo

func (m *MsgPlayerScoreGreatWin) GetBaseWinScore() int32 {
	if m != nil && m.BaseWinScore != nil {
		return *m.BaseWinScore
	}
	return 0
}

func (m *MsgPlayerScoreGreatWin) GetGreatWinType() int32 {
	if m != nil && m.GreatWinType != nil {
		return *m.GreatWinType
	}
	return 0
}

func (m *MsgPlayerScoreGreatWin) GetGreatWinPoints() int32 {
	if m != nil && m.GreatWinPoints != nil {
		return *m.GreatWinPoints
	}
	return 0
}

func (m *MsgPlayerScoreGreatWin) GetTrimGreatWinPoints() int32 {
	if m != nil && m.TrimGreatWinPoints != nil {
		return *m.TrimGreatWinPoints
	}
	return 0
}

func (m *MsgPlayerScoreGreatWin) GetContinuousBankerExtra() int32 {
	if m != nil && m.ContinuousBankerExtra != nil {
		return *m.ContinuousBankerExtra
	}
	return 0
}

// 小胡者的计分
type MsgPlayerScoreMiniWin struct {
	MiniWinType           *int32   `protobuf:"varint,1,req,name=miniWinType" json:"miniWinType,omitempty"`
	MiniWinBasicScore     *int32   `protobuf:"varint,2,req,name=miniWinBasicScore" json:"miniWinBasicScore,omitempty"`
	MiniWinFlowerScore    *int32   `protobuf:"varint,3,req,name=miniWinFlowerScore" json:"miniWinFlowerScore,omitempty"`
	MiniMultiple          *int32   `protobuf:"varint,4,req,name=miniMultiple" json:"miniMultiple,omitempty"`
	MiniWinTrimScore      *int32   `protobuf:"varint,5,req,name=miniWinTrimScore" json:"miniWinTrimScore,omitempty"`
	ContinuousBankerExtra *int32   `protobuf:"varint,6,opt,name=continuousBankerExtra" json:"continuousBankerExtra,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *MsgPlayerScoreMiniWin) Reset()         { *m = MsgPlayerScoreMiniWin{} }
func (m *MsgPlayerScoreMiniWin) String() string { return proto.CompactTextString(m) }
func (*MsgPlayerScoreMiniWin) ProtoMessage()    {}
func (*MsgPlayerScoreMiniWin) Descriptor() ([]byte, []int) {
	return fileDescriptor_116d3ec96f90ca98, []int{11}
}
func (m *MsgPlayerScoreMiniWin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgPlayerScoreMiniWin.Unmarshal(m, b)
}
func (m *MsgPlayerScoreMiniWin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgPlayerScoreMiniWin.Marshal(b, m, deterministic)
}
func (m *MsgPlayerScoreMiniWin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgPlayerScoreMiniWin.Merge(m, src)
}
func (m *MsgPlayerScoreMiniWin) XXX_Size() int {
	return xxx_messageInfo_MsgPlayerScoreMiniWin.Size(m)
}
func (m *MsgPlayerScoreMiniWin) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgPlayerScoreMiniWin.DiscardUnknown(m)
}

var xxx_messageInfo_MsgPlayerScoreMiniWin proto.InternalMessageInfo

func (m *MsgPlayerScoreMiniWin) GetMiniWinType() int32 {
	if m != nil && m.MiniWinType != nil {
		return *m.MiniWinType
	}
	return 0
}

func (m *MsgPlayerScoreMiniWin) GetMiniWinBasicScore() int32 {
	if m != nil && m.MiniWinBasicScore != nil {
		return *m.MiniWinBasicScore
	}
	return 0
}

func (m *MsgPlayerScoreMiniWin) GetMiniWinFlowerScore() int32 {
	if m != nil && m.MiniWinFlowerScore != nil {
		return *m.MiniWinFlowerScore
	}
	return 0
}

func (m *MsgPlayerScoreMiniWin) GetMiniMultiple() int32 {
	if m != nil && m.MiniMultiple != nil {
		return *m.MiniMultiple
	}
	return 0
}

func (m *MsgPlayerScoreMiniWin) GetMiniWinTrimScore() int32 {
	if m != nil && m.MiniWinTrimScore != nil {
		return *m.MiniWinTrimScore
	}
	return 0
}

func (m *MsgPlayerScoreMiniWin) GetContinuousBankerExtra() int32 {
	if m != nil && m.ContinuousBankerExtra != nil {
		return *m.ContinuousBankerExtra
	}
	return 0
}

// 一手牌结束后每个玩家的计分
type MsgPlayerScore struct {
	TargetChairID            *int32                  `protobuf:"varint,1,req,name=targetChairID" json:"targetChairID,omitempty"`
	WinType                  *int32                  `protobuf:"varint,2,req,name=winType" json:"winType,omitempty"`
	Score                    *int32                  `protobuf:"varint,3,req,name=score" json:"score,omitempty"`
	SpecialScore             *int32                  `protobuf:"varint,4,req,name=specialScore" json:"specialScore,omitempty"`
	GreatWin                 *MsgPlayerScoreGreatWin `protobuf:"bytes,5,opt,name=greatWin" json:"greatWin,omitempty"`
	MiniWin                  *MsgPlayerScoreMiniWin  `protobuf:"bytes,6,opt,name=miniWin" json:"miniWin,omitempty"`
	FakeWinScore             *int32                  `protobuf:"varint,7,opt,name=fakeWinScore" json:"fakeWinScore,omitempty"`
	FakeList                 []int32                 `protobuf:"varint,8,rep,name=fakeList" json:"fakeList,omitempty"`
	IsContinuousBanker       *bool                   `protobuf:"varint,9,opt,name=isContinuousBanker" json:"isContinuousBanker,omitempty"`
	ContinuousBankerMultiple *int32                  `protobuf:"varint,10,opt,name=continuousBankerMultiple" json:"continuousBankerMultiple,omitempty"`
	XXX_NoUnkeyedLiteral     struct{}                `json:"-"`
	XXX_unrecognized         []byte                  `json:"-"`
	XXX_sizecache            int32                   `json:"-"`
}

func (m *MsgPlayerScore) Reset()         { *m = MsgPlayerScore{} }
func (m *MsgPlayerScore) String() string { return proto.CompactTextString(m) }
func (*MsgPlayerScore) ProtoMessage()    {}
func (*MsgPlayerScore) Descriptor() ([]byte, []int) {
	return fileDescriptor_116d3ec96f90ca98, []int{12}
}
func (m *MsgPlayerScore) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgPlayerScore.Unmarshal(m, b)
}
func (m *MsgPlayerScore) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgPlayerScore.Marshal(b, m, deterministic)
}
func (m *MsgPlayerScore) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgPlayerScore.Merge(m, src)
}
func (m *MsgPlayerScore) XXX_Size() int {
	return xxx_messageInfo_MsgPlayerScore.Size(m)
}
func (m *MsgPlayerScore) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgPlayerScore.DiscardUnknown(m)
}

var xxx_messageInfo_MsgPlayerScore proto.InternalMessageInfo

func (m *MsgPlayerScore) GetTargetChairID() int32 {
	if m != nil && m.TargetChairID != nil {
		return *m.TargetChairID
	}
	return 0
}

func (m *MsgPlayerScore) GetWinType() int32 {
	if m != nil && m.WinType != nil {
		return *m.WinType
	}
	return 0
}

func (m *MsgPlayerScore) GetScore() int32 {
	if m != nil && m.Score != nil {
		return *m.Score
	}
	return 0
}

func (m *MsgPlayerScore) GetSpecialScore() int32 {
	if m != nil && m.SpecialScore != nil {
		return *m.SpecialScore
	}
	return 0
}

func (m *MsgPlayerScore) GetGreatWin() *MsgPlayerScoreGreatWin {
	if m != nil {
		return m.GreatWin
	}
	return nil
}

func (m *MsgPlayerScore) GetMiniWin() *MsgPlayerScoreMiniWin {
	if m != nil {
		return m.MiniWin
	}
	return nil
}

func (m *MsgPlayerScore) GetFakeWinScore() int32 {
	if m != nil && m.FakeWinScore != nil {
		return *m.FakeWinScore
	}
	return 0
}

func (m *MsgPlayerScore) GetFakeList() []int32 {
	if m != nil {
		return m.FakeList
	}
	return nil
}

func (m *MsgPlayerScore) GetIsContinuousBanker() bool {
	if m != nil && m.IsContinuousBanker != nil {
		return *m.IsContinuousBanker
	}
	return false
}

func (m *MsgPlayerScore) GetContinuousBankerMultiple() int32 {
	if m != nil && m.ContinuousBankerMultiple != nil {
		return *m.ContinuousBankerMultiple
	}
	return 0
}

// 一手牌结束后计分
type MsgHandScore struct {
	PlayerScores         []*MsgPlayerScore `protobuf:"bytes,1,rep,name=playerScores" json:"playerScores,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *MsgHandScore) Reset()         { *m = MsgHandScore{} }
func (m *MsgHandScore) String() string { return proto.CompactTextString(m) }
func (*MsgHandScore) ProtoMessage()    {}
func (*MsgHandScore) Descriptor() ([]byte, []int) {
	return fileDescriptor_116d3ec96f90ca98, []int{13}
}
func (m *MsgHandScore) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgHandScore.Unmarshal(m, b)
}
func (m *MsgHandScore) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgHandScore.Marshal(b, m, deterministic)
}
func (m *MsgHandScore) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgHandScore.Merge(m, src)
}
func (m *MsgHandScore) XXX_Size() int {
	return xxx_messageInfo_MsgHandScore.Size(m)
}
func (m *MsgHandScore) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgHandScore.DiscardUnknown(m)
}

var xxx_messageInfo_MsgHandScore proto.InternalMessageInfo

func (m *MsgHandScore) GetPlayerScores() []*MsgPlayerScore {
	if m != nil {
		return m.PlayerScores
	}
	return nil
}

// 一手牌结束通知
type MsgHandOver struct {
	EndType              *int32               `protobuf:"varint,1,req,name=endType" json:"endType,omitempty"`
	PlayerTileLists      []*MsgPlayerTileList `protobuf:"bytes,2,rep,name=playerTileLists" json:"playerTileLists,omitempty"`
	Scores               *MsgHandScore        `protobuf:"bytes,3,opt,name=scores" json:"scores,omitempty"`
	ContinueAble         *bool                `protobuf:"varint,4,opt,name=continueAble" json:"continueAble,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *MsgHandOver) Reset()         { *m = MsgHandOver{} }
func (m *MsgHandOver) String() string { return proto.CompactTextString(m) }
func (*MsgHandOver) ProtoMessage()    {}
func (*MsgHandOver) Descriptor() ([]byte, []int) {
	return fileDescriptor_116d3ec96f90ca98, []int{14}
}
func (m *MsgHandOver) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgHandOver.Unmarshal(m, b)
}
func (m *MsgHandOver) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgHandOver.Marshal(b, m, deterministic)
}
func (m *MsgHandOver) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgHandOver.Merge(m, src)
}
func (m *MsgHandOver) XXX_Size() int {
	return xxx_messageInfo_MsgHandOver.Size(m)
}
func (m *MsgHandOver) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgHandOver.DiscardUnknown(m)
}

var xxx_messageInfo_MsgHandOver proto.InternalMessageInfo

func (m *MsgHandOver) GetEndType() int32 {
	if m != nil && m.EndType != nil {
		return *m.EndType
	}
	return 0
}

func (m *MsgHandOver) GetPlayerTileLists() []*MsgPlayerTileList {
	if m != nil {
		return m.PlayerTileLists
	}
	return nil
}

func (m *MsgHandOver) GetScores() *MsgHandScore {
	if m != nil {
		return m.Scores
	}
	return nil
}

func (m *MsgHandOver) GetContinueAble() bool {
	if m != nil && m.ContinueAble != nil {
		return *m.ContinueAble
	}
	return false
}

// 更新玩家的GPS定位信息
type MsgUpdateLocation struct {
	UserID               *string  `protobuf:"bytes,1,req,name=userID" json:"userID,omitempty"`
	Location             *string  `protobuf:"bytes,2,req,name=location" json:"location,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgUpdateLocation) Reset()         { *m = MsgUpdateLocation{} }
func (m *MsgUpdateLocation) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateLocation) ProtoMessage()    {}
func (*MsgUpdateLocation) Descriptor() ([]byte, []int) {
	return fileDescriptor_116d3ec96f90ca98, []int{15}
}
func (m *MsgUpdateLocation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgUpdateLocation.Unmarshal(m, b)
}
func (m *MsgUpdateLocation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgUpdateLocation.Marshal(b, m, deterministic)
}
func (m *MsgUpdateLocation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateLocation.Merge(m, src)
}
func (m *MsgUpdateLocation) XXX_Size() int {
	return xxx_messageInfo_MsgUpdateLocation.Size(m)
}
func (m *MsgUpdateLocation) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateLocation.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateLocation proto.InternalMessageInfo

func (m *MsgUpdateLocation) GetUserID() string {
	if m != nil && m.UserID != nil {
		return *m.UserID
	}
	return ""
}

func (m *MsgUpdateLocation) GetLocation() string {
	if m != nil && m.Location != nil {
		return *m.Location
	}
	return ""
}

// 更新牌局内的道具配置
type MsgUpdatePropCfg struct {
	PropCfg              *string  `protobuf:"bytes,1,req,name=propCfg" json:"propCfg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgUpdatePropCfg) Reset()         { *m = MsgUpdatePropCfg{} }
func (m *MsgUpdatePropCfg) String() string { return proto.CompactTextString(m) }
func (*MsgUpdatePropCfg) ProtoMessage()    {}
func (*MsgUpdatePropCfg) Descriptor() ([]byte, []int) {
	return fileDescriptor_116d3ec96f90ca98, []int{16}
}
func (m *MsgUpdatePropCfg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgUpdatePropCfg.Unmarshal(m, b)
}
func (m *MsgUpdatePropCfg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgUpdatePropCfg.Marshal(b, m, deterministic)
}
func (m *MsgUpdatePropCfg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdatePropCfg.Merge(m, src)
}
func (m *MsgUpdatePropCfg) XXX_Size() int {
	return xxx_messageInfo_MsgUpdatePropCfg.Size(m)
}
func (m *MsgUpdatePropCfg) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdatePropCfg.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdatePropCfg proto.InternalMessageInfo

func (m *MsgUpdatePropCfg) GetPropCfg() string {
	if m != nil && m.PropCfg != nil {
		return *m.PropCfg
	}
	return ""
}

func init() {
	proto.RegisterType((*GameMessage)(nil), "mahjong.GameMessage")
	proto.RegisterType((*MsgMeldTile)(nil), "mahjong.MsgMeldTile")
	proto.RegisterType((*MsgPlayerTileList)(nil), "mahjong.MsgPlayerTileList")
	proto.RegisterType((*MsgDeal)(nil), "mahjong.MsgDeal")
	proto.RegisterType((*MsgReadyHandTips)(nil), "mahjong.MsgReadyHandTips")
	proto.RegisterType((*MsgAllowPlayerAction)(nil), "mahjong.MsgAllowPlayerAction")
	proto.RegisterType((*MsgAllowPlayerReAction)(nil), "mahjong.MsgAllowPlayerReAction")
	proto.RegisterType((*MsgPlayerAction)(nil), "mahjong.MsgPlayerAction")
	proto.RegisterType((*MsgActionResultNotify)(nil), "mahjong.MsgActionResultNotify")
	proto.RegisterType((*MsgRestore)(nil), "mahjong.MsgRestore")
	proto.RegisterType((*MsgPlayerScoreGreatWin)(nil), "mahjong.MsgPlayerScoreGreatWin")
	proto.RegisterType((*MsgPlayerScoreMiniWin)(nil), "mahjong.MsgPlayerScoreMiniWin")
	proto.RegisterType((*MsgPlayerScore)(nil), "mahjong.MsgPlayerScore")
	proto.RegisterType((*MsgHandScore)(nil), "mahjong.MsgHandScore")
	proto.RegisterType((*MsgHandOver)(nil), "mahjong.MsgHandOver")
	proto.RegisterType((*MsgUpdateLocation)(nil), "mahjong.MsgUpdateLocation")
	proto.RegisterType((*MsgUpdatePropCfg)(nil), "mahjong.MsgUpdatePropCfg")
	proto.RegisterEnum("mahjong.TileID", TileID_name, TileID_value)
	proto.RegisterEnum("mahjong.MessageCode", MessageCode_name, MessageCode_value)
	proto.RegisterEnum("mahjong.MeldType", MeldType_name, MeldType_value)
	proto.RegisterEnum("mahjong.ActionType", ActionType_name, ActionType_value)
	proto.RegisterEnum("mahjong.HandOverType", HandOverType_name, HandOverType_value)
}

func init() { proto.RegisterFile("game_mahjong.proto", fileDescriptor_116d3ec96f90ca98) }

var fileDescriptor_116d3ec96f90ca98 = []byte{
	// 1903 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x57, 0xcd, 0x52, 0xe3, 0xca,
	0x15, 0x1e, 0xff, 0x9b, 0xe3, 0x1f, 0x0e, 0x8d, 0x01, 0x0d, 0x33, 0xcc, 0x78, 0x3c, 0xb9, 0x09,
	0xa1, 0x92, 0x9b, 0xe0, 0xf9, 0x5f, 0xa4, 0xea, 0x1a, 0x9b, 0x01, 0x17, 0xc8, 0x76, 0xd9, 0x50,
	0x24, 0x2b, 0x4a, 0x58, 0x8d, 0xe9, 0x20, 0x4b, 0xbe, 0x6a, 0x79, 0x3c, 0xec, 0xfc, 0x08, 0x77,
	0x97, 0x45, 0x36, 0xd9, 0x65, 0x9f, 0x47, 0xc8, 0xf2, 0x56, 0xa5, 0x2a, 0x55, 0x79, 0x8f, 0x3c,
	0x43, 0xaa, 0xbb, 0x25, 0x90, 0x84, 0x7d, 0xb3, 0xba, 0x3b, 0xeb, 0x3b, 0xdd, 0x7d, 0xbe, 0xf3,
	0x9d, 0x9f, 0x6e, 0x03, 0x19, 0x19, 0x63, 0x7a, 0x39, 0x36, 0x6e, 0xfe, 0xec, 0xd8, 0xa3, 0x6f,
	0x27, 0xae, 0xe3, 0x39, 0x24, 0xe7, 0x7f, 0xd6, 0x76, 0xa1, 0x70, 0x64, 0x8c, 0xa9, 0x4e, 0x39,
	0x37, 0x46, 0x94, 0x14, 0x20, 0xd5, 0x9d, 0x70, 0x2d, 0x51, 0x4d, 0xee, 0x66, 0x48, 0x11, 0xd2,
	0x2d, 0xc3, 0x33, 0xb4, 0x64, 0x35, 0xb1, 0x5b, 0xac, 0x9d, 0x43, 0x41, 0xe7, 0x23, 0x9d, 0x5a,
	0xe6, 0x19, 0xb3, 0x28, 0x41, 0xc8, 0x8f, 0xc5, 0xef, 0xbb, 0x09, 0xf5, 0x97, 0x97, 0x20, 0xe3,
	0x31, 0x8b, 0xee, 0x6b, 0x49, 0xf9, 0xb9, 0x0e, 0x85, 0xa1, 0x63, 0x7b, 0x2e, 0xbb, 0x9a, 0x7a,
	0x8e, 0xab, 0xa5, 0xaa, 0x89, 0xdd, 0x8c, 0xd8, 0x35, 0xbc, 0x71, 0x66, 0xe2, 0x04, 0x2d, 0x2d,
	0x90, 0xda, 0xdf, 0x12, 0xb0, 0xa6, 0xf3, 0x51, 0xcf, 0x32, 0xee, 0xa8, 0x2b, 0xf0, 0x53, 0xc6,
	0x3d, 0xb2, 0x0a, 0xb9, 0xe1, 0x8d, 0xc1, 0xdc, 0x76, 0xcb, 0x3f, 0x7c, 0x0b, 0x56, 0xc5, 0xe1,
	0x4d, 0x67, 0x6a, 0x7b, 0x6d, 0xfb, 0xd8, 0xb0, 0x4d, 0xdf, 0xcd, 0x1a, 0xac, 0x08, 0x03, 0x97,
	0x50, 0xaa, 0x9a, 0x52, 0x9e, 0x25, 0xf4, 0xd9, 0x72, 0x66, 0xd4, 0xd5, 0xd2, 0x12, 0xac, 0x40,
	0x51, 0x82, 0x2d, 0xc6, 0x87, 0x86, 0x6b, 0x6a, 0x19, 0x89, 0xbe, 0x86, 0x8c, 0x88, 0x82, 0x6b,
	0xd9, 0x6a, 0x6a, 0xb7, 0x50, 0xaf, 0x7c, 0x1b, 0xc8, 0x14, 0x0a, 0xb5, 0xf6, 0x63, 0x02, 0x72,
	0x3a, 0x1f, 0xb5, 0xa8, 0x61, 0x91, 0x0d, 0x28, 0x5d, 0x19, 0xf6, 0x2d, 0x75, 0x9b, 0x11, 0x7a,
	0x15, 0x28, 0xce, 0x98, 0x6d, 0x2a, 0x8f, 0xed, 0x96, 0xcf, 0xed, 0x0d, 0xac, 0x4e, 0x22, 0x71,
	0x71, 0xc9, 0xb0, 0x50, 0xdf, 0x0e, 0xfb, 0x89, 0x85, 0x1e, 0xb0, 0x6f, 0xdb, 0x17, 0x86, 0x65,
	0x69, 0xe9, 0x40, 0x5b, 0x93, 0x0d, 0xe9, 0xbe, 0x96, 0x91, 0x32, 0xfa, 0x9f, 0x75, 0x2d, 0x2b,
	0x3f, 0xb7, 0x81, 0x30, 0xde, 0x74, 0x6c, 0x8f, 0xd9, 0x53, 0x67, 0xca, 0x0f, 0x24, 0x41, 0x2d,
	0x57, 0x4d, 0xec, 0xe6, 0x49, 0x19, 0xb2, 0x63, 0xc3, 0xbd, 0x9d, 0x4e, 0xb4, 0xbc, 0xd4, 0xfb,
	0x0f, 0x80, 0x3a, 0x1f, 0xf5, 0xa9, 0x61, 0xde, 0x09, 0xc9, 0xce, 0xd8, 0x84, 0x13, 0x02, 0xe0,
	0x19, 0xee, 0x88, 0x7a, 0x32, 0x2f, 0x2a, 0xa2, 0x0d, 0x28, 0xb9, 0xc1, 0x22, 0xc1, 0x4b, 0x4b,
	0x0a, 0xc1, 0x6a, 0xff, 0x4e, 0x40, 0x45, 0xe7, 0xa3, 0x86, 0x65, 0x39, 0x33, 0x45, 0xbc, 0x31,
	0xf4, 0x98, 0x63, 0x8b, 0x8c, 0x7d, 0x6f, 0xb4, 0x6d, 0x93, 0x7e, 0x7d, 0x38, 0xc0, 0x90, 0xa6,
	0x40, 0x29, 0xa5, 0xc9, 0x26, 0x94, 0x0d, 0xb1, 0x99, 0x9a, 0x6a, 0xa3, 0x90, 0x44, 0xe0, 0x1a,
	0xa0, 0xc7, 0xc6, 0xd4, 0x99, 0x7a, 0x6d, 0x7b, 0x40, 0x87, 0x8e, 0x6d, 0x72, 0x55, 0x21, 0xe4,
	0xf7, 0x50, 0xf2, 0xd8, 0x84, 0x7f, 0x76, 0x7c, 0x57, 0x32, 0x75, 0x85, 0xfa, 0xd3, 0xb0, 0x86,
	0xd1, 0x78, 0x7e, 0x03, 0x65, 0x99, 0xd5, 0x87, 0x2d, 0x3f, 0x95, 0xde, 0x7f, 0x25, 0x60, 0x33,
	0x1a, 0x52, 0x9f, 0xfe, 0xec, 0x41, 0x3d, 0xa6, 0x98, 0x59, 0x4e, 0x51, 0x94, 0xd7, 0x17, 0x36,
	0xf4, 0xd8, 0x58, 0x7c, 0xb5, 0x5b, 0x5a, 0x36, 0x20, 0xa3, 0xd0, 0x80, 0x4c, 0x4e, 0xc0, 0x35,
	0x0f, 0x56, 0xef, 0xab, 0x6a, 0x59, 0x1c, 0x65, 0xc8, 0xaa, 0x38, 0xfc, 0x00, 0x4a, 0x90, 0xb9,
	0xb6, 0x8c, 0x11, 0xf7, 0xdb, 0xb4, 0x08, 0x69, 0xef, 0xbe, 0x45, 0x23, 0xad, 0xae, 0xea, 0x6f,
	0x0d, 0x56, 0xc6, 0x3e, 0xb7, 0x7d, 0x55, 0x83, 0xb5, 0x7f, 0x26, 0x60, 0x43, 0xa8, 0x28, 0x4f,
	0xed, 0x53, 0x3e, 0xb5, 0xbc, 0x8e, 0xe3, 0xb1, 0xeb, 0x3b, 0x41, 0x53, 0x55, 0x57, 0xb4, 0x65,
	0xe2, 0x14, 0x08, 0x80, 0xfa, 0x96, 0x45, 0xa8, 0x78, 0xec, 0x06, 0x98, 0x50, 0x42, 0xb2, 0x59,
	0xa6, 0x10, 0x01, 0xb0, 0xe9, 0x4c, 0xf5, 0x1f, 0xf7, 0x9b, 0x3b, 0xd6, 0x49, 0xaa, 0x57, 0x9e,
	0xc1, 0xfa, 0xcc, 0x60, 0x9e, 0x3f, 0x06, 0x82, 0x4c, 0xab, 0x66, 0x11, 0x41, 0x80, 0xac, 0x26,
	0xee, 0x39, 0x2e, 0x25, 0xaf, 0x20, 0x37, 0x56, 0x7d, 0x2f, 0x39, 0x17, 0xea, 0x18, 0xf6, 0x2d,
	0xe7, 0xc1, 0x16, 0xac, 0xde, 0xb7, 0x89, 0x8c, 0x8f, 0xab, 0x46, 0x11, 0x7e, 0x2c, 0x83, 0xfb,
	0x7e, 0xa8, 0x19, 0xc4, 0xae, 0xe2, 0x5a, 0x87, 0x02, 0xe3, 0x3a, 0xed, 0xd0, 0x59, 0xcb, 0x35,
	0x66, 0x32, 0xb0, 0xfc, 0x32, 0x66, 0x19, 0x69, 0xdc, 0x06, 0x72, 0x6d, 0xdd, 0xf5, 0x63, 0xae,
	0xb2, 0xd2, 0x55, 0x09, 0x32, 0xf4, 0xab, 0xe7, 0x1a, 0x32, 0x88, 0x62, 0xed, 0x2f, 0xaa, 0x9e,
	0x55, 0x01, 0x0c, 0x86, 0x8e, 0x4b, 0x8f, 0x5c, 0x6a, 0x78, 0x17, 0xcc, 0x16, 0x75, 0x74, 0x65,
	0x70, 0x7a, 0xc1, 0x6c, 0x89, 0x3f, 0x0c, 0xaf, 0x91, 0xbf, 0x42, 0xe6, 0xf8, 0xbe, 0xa6, 0x03,
	0xb4, 0xe7, 0x30, 0xdb, 0x0b, 0x6a, 0x7a, 0x1b, 0x88, 0xe7, 0xb2, 0xf1, 0x51, 0xd4, 0xa6, 0xc6,
	0xd4, 0x0e, 0x6c, 0x0c, 0x63, 0x63, 0xe8, 0x50, 0x32, 0x93, 0x65, 0x53, 0xfb, 0x87, 0xaa, 0x91,
	0x10, 0x33, 0x9d, 0xd9, 0x4c, 0x10, 0x5b, 0x87, 0xc2, 0x58, 0xfd, 0x0c, 0x5d, 0x28, 0x4f, 0x61,
	0xcd, 0x07, 0x0f, 0x0c, 0xce, 0x86, 0x8a, 0x72, 0x32, 0x20, 0xe1, 0x9b, 0x54, 0xca, 0x95, 0x2d,
	0x15, 0x84, 0x23, 0x6c, 0xfa, 0xd4, 0xf2, 0xd8, 0x44, 0x16, 0xb1, 0xdf, 0x8a, 0x81, 0x07, 0x97,
	0x8d, 0xd5, 0xfa, 0xcc, 0x4f, 0x93, 0x56, 0x85, 0xfd, 0xf7, 0x24, 0x94, 0xa3, 0xa4, 0x97, 0x55,
	0xf4, 0x2a, 0xe4, 0x66, 0x11, 0x09, 0x4b, 0x90, 0xe1, 0x51, 0x62, 0x7c, 0x42, 0x87, 0xcc, 0xb0,
	0x94, 0x7b, 0x45, 0x6c, 0x1f, 0xf2, 0x81, 0xce, 0x52, 0xa6, 0x42, 0xfd, 0xe5, 0xe3, 0xdb, 0x21,
	0x9a, 0xc6, 0xdf, 0x41, 0xce, 0x8f, 0x45, 0x72, 0x2c, 0xd4, 0x5f, 0x2c, 0xd9, 0x11, 0xc8, 0x5b,
	0x81, 0xe2, 0xb5, 0x71, 0xfb, 0x90, 0xf7, 0x5c, 0xd0, 0xd7, 0x02, 0x95, 0xd3, 0x3d, 0x2f, 0x2b,
	0x69, 0xf1, 0x45, 0xb2, 0x22, 0x2b, 0xb0, 0x0a, 0x5a, 0x5c, 0xa6, 0x7b, 0x89, 0xc1, 0xbf, 0x5a,
	0x8a, 0x3a, 0x1f, 0x89, 0xf2, 0x54, 0x32, 0xfd, 0x16, 0x8a, 0x93, 0x07, 0x2e, 0xe2, 0x55, 0x21,
	0x26, 0xdc, 0xd6, 0x12, 0xae, 0xb5, 0x1f, 0x12, 0xf2, 0x85, 0x21, 0xf6, 0x77, 0xbf, 0x50, 0x57,
	0xc8, 0x49, 0xed, 0xf0, 0x03, 0x63, 0xc1, 0x75, 0x9a, 0xfc, 0xbf, 0xd7, 0xe9, 0x37, 0x90, 0xe5,
	0xca, 0x7d, 0x4a, 0x4a, 0xb5, 0x11, 0x5e, 0xfb, 0xc0, 0xb5, 0x02, 0x45, 0x3f, 0x3a, 0xda, 0xb8,
	0xf2, 0x27, 0x5f, 0xbe, 0xf6, 0x4e, 0xbe, 0x4d, 0xce, 0x27, 0xa6, 0xe1, 0xd1, 0x53, 0x67, 0x68,
	0xc8, 0x61, 0x5a, 0x86, 0xec, 0x94, 0xd3, 0x20, 0xed, 0x2b, 0x42, 0x46, 0xcb, 0xb7, 0xc9, 0xbc,
	0xaf, 0xd4, 0x5e, 0xcb, 0x3b, 0x56, 0x6d, 0xeb, 0xb9, 0xce, 0xa4, 0x79, 0x3d, 0x12, 0xd1, 0x4c,
	0xd4, 0x4f, 0xb5, 0x6d, 0xef, 0xaf, 0x59, 0xc8, 0xaa, 0x71, 0x4e, 0x10, 0x8a, 0xd4, 0x9e, 0x8e,
	0xcf, 0x98, 0x79, 0xa9, 0x37, 0x3a, 0xfb, 0xf8, 0x24, 0x86, 0xd4, 0x31, 0x11, 0x43, 0xde, 0x60,
	0x32, 0x86, 0xbc, 0xc5, 0x54, 0x0c, 0x79, 0x87, 0xe9, 0x18, 0xf2, 0x1e, 0x33, 0x31, 0xe4, 0x03,
	0x66, 0x63, 0xc8, 0x47, 0xcc, 0xc5, 0x90, 0x4f, 0x98, 0x0f, 0x23, 0xbd, 0x76, 0x67, 0x1f, 0x57,
	0x62, 0x48, 0x1d, 0x21, 0x86, 0xbc, 0xc1, 0x42, 0x0c, 0x79, 0x8b, 0xc5, 0x18, 0xf2, 0x0e, 0x4b,
	0x31, 0xe4, 0x3d, 0x96, 0x63, 0xc8, 0x07, 0x5c, 0x8d, 0x21, 0x1f, 0x11, 0x63, 0xc8, 0x27, 0x5c,
	0x0b, 0x23, 0x83, 0xee, 0xf9, 0x3e, 0x92, 0x18, 0x52, 0xc7, 0xf5, 0x18, 0xf2, 0x06, 0x2b, 0x31,
	0xe4, 0x2d, 0x6e, 0xc4, 0x90, 0x77, 0xb8, 0x19, 0x43, 0xde, 0xe3, 0x56, 0x0c, 0xf9, 0x80, 0x5a,
	0x0c, 0xf9, 0x88, 0x4f, 0x63, 0xc8, 0x27, 0xdc, 0x26, 0xab, 0x50, 0x08, 0x90, 0xb3, 0x6e, 0x07,
	0x9f, 0x85, 0x81, 0x4e, 0xa3, 0x83, 0xcf, 0xc3, 0xc0, 0xe0, 0xb8, 0x81, 0x3b, 0x61, 0xa0, 0x77,
	0xd8, 0xc6, 0x17, 0x61, 0xe0, 0xb8, 0x71, 0x82, 0x2f, 0xa3, 0xc0, 0x19, 0x56, 0xc3, 0x40, 0xf3,
	0xf8, 0x1c, 0x5f, 0x45, 0xa4, 0x3a, 0x3d, 0xd7, 0xb1, 0x46, 0x08, 0x94, 0x03, 0xa4, 0xdb, 0x6f,
	0x1e, 0xb7, 0x5b, 0xf8, 0x3a, 0x8c, 0x1d, 0x34, 0xf4, 0x83, 0x6e, 0x17, 0x7f, 0x41, 0x9e, 0xc2,
	0xc6, 0xc3, 0x51, 0xfd, 0x3f, 0x0d, 0x1a, 0x9d, 0xb3, 0xe3, 0x43, 0xfd, 0x5c, 0xc7, 0x6f, 0xc2,
	0xcb, 0x07, 0xbd, 0x7e, 0xbb, 0x73, 0x84, 0xbf, 0x8c, 0x60, 0xe7, 0xba, 0x7e, 0xd8, 0xc7, 0x5f,
	0x85, 0xb1, 0xc6, 0xf9, 0xd9, 0xb9, 0xde, 0xc1, 0xdd, 0x30, 0x76, 0xd1, 0xee, 0x9c, 0x1d, 0xf6,
	0xf1, 0xd7, 0x61, 0xd6, 0x7a, 0xe3, 0x8f, 0xb8, 0xb7, 0xf7, 0x9f, 0x14, 0x14, 0xfc, 0x3f, 0x25,
	0x4d, 0xc7, 0xa4, 0xa4, 0x04, 0x2b, 0xdd, 0x5e, 0xdb, 0xfe, 0x62, 0x58, 0xcc, 0xc4, 0x27, 0xa4,
	0x08, 0xf9, 0x6e, 0x4f, 0x5d, 0x90, 0x98, 0x20, 0x1a, 0x54, 0x82, 0xaf, 0xf0, 0xcb, 0x03, 0x93,
	0x64, 0x1d, 0x56, 0x03, 0x4b, 0x43, 0x3d, 0xd0, 0x30, 0x45, 0x36, 0x60, 0xad, 0xdb, 0x0b, 0xee,
	0xd7, 0x00, 0xce, 0x10, 0x80, 0x6c, 0xb7, 0x27, 0x2e, 0x75, 0xcc, 0x92, 0x32, 0x40, 0xb7, 0x17,
	0x4c, 0x22, 0xcc, 0x29, 0xf7, 0xfe, 0xb3, 0x00, 0xf3, 0xea, 0x04, 0x35, 0x68, 0x4e, 0xa9, 0xf1,
	0x85, 0xf6, 0x1d, 0x67, 0x8c, 0x2b, 0x61, 0xf8, 0xd0, 0xf6, 0xa8, 0x2b, 0x61, 0x20, 0x15, 0xc0,
	0x6e, 0xaf, 0xc5, 0xf8, 0x95, 0x61, 0x9b, 0x7d, 0xfa, 0xfd, 0x94, 0x72, 0x0f, 0x0b, 0x8a, 0x9a,
	0x8f, 0xfa, 0x7c, 0x8b, 0x11, 0xb0, 0x61, 0xf3, 0x19, 0x75, 0xb1, 0x44, 0xd6, 0xa0, 0x14, 0x1c,
	0x2b, 0x1f, 0x00, 0x58, 0x56, 0x90, 0x38, 0xbe, 0x45, 0x2d, 0xea, 0x51, 0x53, 0x35, 0x89, 0x82,
	0xd4, 0xdc, 0x41, 0x14, 0x42, 0x2b, 0x64, 0x20, 0xff, 0x72, 0x4d, 0x38, 0xae, 0xa9, 0xc0, 0xc4,
	0x3f, 0x3e, 0x19, 0x18, 0x51, 0x81, 0x9d, 0xb0, 0xe1, 0xad, 0x33, 0xf5, 0x70, 0x5d, 0xe9, 0xda,
	0x72, 0x6c, 0x71, 0x40, 0x45, 0x11, 0x8f, 0x4e, 0x3f, 0xdc, 0x50, 0x6b, 0xea, 0xa7, 0xce, 0xd5,
	0xd5, 0x1d, 0x6e, 0x2a, 0xc6, 0x91, 0x51, 0x87, 0x5b, 0x4a, 0xca, 0x1e, 0xb3, 0x47, 0x68, 0xfa,
	0xbf, 0x1d, 0x7b, 0x84, 0x74, 0xef, 0x87, 0x24, 0xe4, 0x75, 0xff, 0x29, 0x29, 0xb2, 0x26, 0x72,
	0x1e, 0x7c, 0x0f, 0x84, 0x32, 0xf6, 0x90, 0xe2, 0x13, 0xb2, 0x05, 0xeb, 0x61, 0xcb, 0x99, 0x2b,
	0x2e, 0x19, 0x0f, 0x13, 0xe4, 0x19, 0x6c, 0x85, 0x0d, 0x87, 0x5f, 0x27, 0x0e, 0xa7, 0xe6, 0x89,
	0x38, 0x3c, 0x49, 0x9e, 0x83, 0xb6, 0x60, 0x57, 0x5d, 0x5a, 0x53, 0x64, 0x07, 0x9e, 0x86, 0xad,
	0x4d, 0xc7, 0x1e, 0x52, 0xc3, 0xf2, 0x37, 0xa7, 0x1f, 0x93, 0xb1, 0xae, 0xc5, 0x6f, 0x14, 0xaf,
	0xec, 0xb5, 0xc8, 0xc6, 0x9b, 0xe9, 0xf1, 0x31, 0x66, 0xc9, 0x26, 0x90, 0x47, 0xf0, 0x3e, 0xe6,
	0x84, 0x66, 0x61, 0xfc, 0x82, 0xd9, 0x26, 0xe6, 0xe3, 0xc7, 0xf7, 0x0c, 0xe6, 0x4a, 0xc7, 0x2b,
	0x7b, 0xff, 0x4d, 0x01, 0xa8, 0x4a, 0x94, 0xa2, 0xf8, 0xa1, 0x3f, 0x20, 0x97, 0x83, 0x93, 0x76,
	0x0f, 0x13, 0x64, 0x1b, 0x36, 0x63, 0x86, 0x56, 0x7b, 0xd0, 0x6c, 0xf4, 0x5b, 0x98, 0x5c, 0xb0,
	0xa9, 0xd5, 0x6f, 0x5c, 0x60, 0x7a, 0x81, 0xa1, 0x79, 0xdc, 0xbd, 0xc0, 0xfc, 0x02, 0x43, 0xaf,
	0xdb, 0x39, 0x42, 0x24, 0x2f, 0xe1, 0x59, 0xcc, 0x70, 0xd2, 0xed, 0x1c, 0x5d, 0xfa, 0x4a, 0x63,
	0x95, 0xbc, 0x82, 0x9d, 0x45, 0x0b, 0xee, 0xf5, 0xc4, 0xef, 0xc8, 0x8e, 0x4a, 0x44, 0x68, 0xc9,
	0x45, 0xbb, 0x73, 0xd9, 0xbc, 0x99, 0x0e, 0x6f, 0x71, 0x9e, 0x20, 0xaf, 0xe0, 0xf9, 0x02, 0xb3,
	0x50, 0x5c, 0x3c, 0x86, 0x6d, 0x9c, 0x27, 0x17, 0x2c, 0x91, 0x4e, 0x82, 0x94, 0xe2, 0x3c, 0x4d,
	0x6a, 0x8f, 0x78, 0x7c, 0x66, 0x2e, 0xf7, 0xee, 0x5f, 0xc8, 0x38, 0xcf, 0x2f, 0x20, 0x12, 0x32,
	0x23, 0x79, 0xf6, 0x48, 0xd2, 0xe6, 0x94, 0x7b, 0xce, 0xb8, 0x81, 0xf3, 0xea, 0x52, 0xe3, 0x01,
	0xce, 0xbf, 0x23, 0xcf, 0x97, 0x18, 0x9b, 0x38, 0x9f, 0x27, 0x96, 0x5a, 0x5b, 0x38, 0x9f, 0x27,
	0xf7, 0x7e, 0x4c, 0x40, 0x31, 0x98, 0x2c, 0x32, 0xe5, 0xfe, 0x98, 0x0d, 0x63, 0x97, 0x1d, 0xc7,
	0x16, 0x8d, 0x50, 0x83, 0x17, 0x8f, 0x4c, 0x17, 0xcc, 0x0e, 0x89, 0x95, 0x20, 0x2f, 0x60, 0x7b,
	0xe1, 0x1a, 0xa5, 0xf7, 0x7d, 0x5b, 0x44, 0xec, 0xd2, 0x46, 0x5d, 0x4c, 0x05, 0x1d, 0x15, 0xb1,
	0x8a, 0xca, 0xa4, 0x2e, 0xa6, 0x49, 0x55, 0xa5, 0xe1, 0xd1, 0xd1, 0x7d, 0xe7, 0x4a, 0x56, 0x6f,
	0xe6, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xdf, 0x35, 0xf9, 0x45, 0x5c, 0x12, 0x00, 0x00,
}
