// Code generated by protoc-gen-go. DO NOT EDIT.
// source: game_mahjong_df.proto

package dfmahjong

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 大胡
// 大胡类型，一手牌可以有多种大胡类型
type GreatWinType int32

const (
	GreatWinType_enumGreatWinType_None                     GreatWinType = 0
	GreatWinType_enumGreatWinType_ChowPongKong             GreatWinType = 1
	GreatWinType_enumGreatWinType_FinalDraw                GreatWinType = 2
	GreatWinType_enumGreatWinType_PongKong                 GreatWinType = 4
	GreatWinType_enumGreatWinType_PureSame                 GreatWinType = 8
	GreatWinType_enumGreatWinType_MixedSame                GreatWinType = 16
	GreatWinType_enumGreatWinType_ClearFront               GreatWinType = 32
	GreatWinType_enumGreatWinType_SevenPair                GreatWinType = 64
	GreatWinType_enumGreatWinType_GreatSevenPair           GreatWinType = 128
	GreatWinType_enumGreatWinType_Heaven                   GreatWinType = 256
	GreatWinType_enumGreatWinType_AfterConcealedKong       GreatWinType = 512
	GreatWinType_enumGreatWinType_AfterExposedKong         GreatWinType = 1024
	GreatWinType_enumGreatWinType_Richi                    GreatWinType = 2048
	GreatWinType_enumGreatWinType_PongKongWithFlowerNoMeld GreatWinType = 4096
	GreatWinType_enumGreatWinType_PureSameWithFlowerNoMeld GreatWinType = 8192
	GreatWinType_enumGreatWinType_MixSameWithFlowerNoMeld  GreatWinType = 16384
	GreatWinType_enumGreatWinType_PureSameWithMeld         GreatWinType = 32768
	GreatWinType_enumGreatWinType_MixSameWithMeld          GreatWinType = 65536
	GreatWinType_enumGreatWinType_RobKong                  GreatWinType = 131072
	GreatWinType_enumGreatWinType_OpponentsRichi           GreatWinType = 262144
)

var GreatWinType_name = map[int32]string{
	0:      "enumGreatWinType_None",
	1:      "enumGreatWinType_ChowPongKong",
	2:      "enumGreatWinType_FinalDraw",
	4:      "enumGreatWinType_PongKong",
	8:      "enumGreatWinType_PureSame",
	16:     "enumGreatWinType_MixedSame",
	32:     "enumGreatWinType_ClearFront",
	64:     "enumGreatWinType_SevenPair",
	128:    "enumGreatWinType_GreatSevenPair",
	256:    "enumGreatWinType_Heaven",
	512:    "enumGreatWinType_AfterConcealedKong",
	1024:   "enumGreatWinType_AfterExposedKong",
	2048:   "enumGreatWinType_Richi",
	4096:   "enumGreatWinType_PongKongWithFlowerNoMeld",
	8192:   "enumGreatWinType_PureSameWithFlowerNoMeld",
	16384:  "enumGreatWinType_MixSameWithFlowerNoMeld",
	32768:  "enumGreatWinType_PureSameWithMeld",
	65536:  "enumGreatWinType_MixSameWithMeld",
	131072: "enumGreatWinType_RobKong",
	262144: "enumGreatWinType_OpponentsRichi",
}

var GreatWinType_value = map[string]int32{
	"enumGreatWinType_None":                     0,
	"enumGreatWinType_ChowPongKong":             1,
	"enumGreatWinType_FinalDraw":                2,
	"enumGreatWinType_PongKong":                 4,
	"enumGreatWinType_PureSame":                 8,
	"enumGreatWinType_MixedSame":                16,
	"enumGreatWinType_ClearFront":               32,
	"enumGreatWinType_SevenPair":                64,
	"enumGreatWinType_GreatSevenPair":           128,
	"enumGreatWinType_Heaven":                   256,
	"enumGreatWinType_AfterConcealedKong":       512,
	"enumGreatWinType_AfterExposedKong":         1024,
	"enumGreatWinType_Richi":                    2048,
	"enumGreatWinType_PongKongWithFlowerNoMeld": 4096,
	"enumGreatWinType_PureSameWithFlowerNoMeld": 8192,
	"enumGreatWinType_MixSameWithFlowerNoMeld":  16384,
	"enumGreatWinType_PureSameWithMeld":         32768,
	"enumGreatWinType_MixSameWithMeld":          65536,
	"enumGreatWinType_RobKong":                  131072,
	"enumGreatWinType_OpponentsRichi":           262144,
}

func (x GreatWinType) Enum() *GreatWinType {
	p := new(GreatWinType)
	*p = x
	return p
}

func (x GreatWinType) String() string {
	return proto.EnumName(GreatWinType_name, int32(x))
}

func (x *GreatWinType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(GreatWinType_value, data, "GreatWinType")
	if err != nil {
		return err
	}
	*x = GreatWinType(value)
	return nil
}

func (GreatWinType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_808dfe8173d1b9cc, []int{0}
}

// 小胡
// 小胡类型，一手牌可以有多种小胡类型
type MiniWinType int32

const (
	MiniWinType_enumMiniWinType_None              MiniWinType = 0
	MiniWinType_enumMiniWinType_Continuous_Banker MiniWinType = 1
	MiniWinType_enumMiniWinType_SelfDraw          MiniWinType = 2
	MiniWinType_enumMiniWinType_NoFlowers         MiniWinType = 4
	MiniWinType_enumMiniWinType_Kong2Discard      MiniWinType = 8
	MiniWinType_enumMiniWinType_Kong2SelfDraw     MiniWinType = 16
	MiniWinType_enumMiniWinType_SecondFrontClear  MiniWinType = 32
	MiniWinType_enumMiniWinType_PongSelfDrawn     MiniWinType = 64
	MiniWinType_enumMiniWinType_ChowPongkong      MiniWinType = 128
	MiniWinType_enumMiniWinType_Richi             MiniWinType = 256
	MiniWinType_enumMiniWinType_SevenPair         MiniWinType = 512
	MiniWinType_enumMiniWinType_PureSameWithMeld  MiniWinType = 1024
	MiniWinType_enumMiniWinType_MixSameWithMeld   MiniWinType = 2048
)

var MiniWinType_name = map[int32]string{
	0:    "enumMiniWinType_None",
	1:    "enumMiniWinType_Continuous_Banker",
	2:    "enumMiniWinType_SelfDraw",
	4:    "enumMiniWinType_NoFlowers",
	8:    "enumMiniWinType_Kong2Discard",
	16:   "enumMiniWinType_Kong2SelfDraw",
	32:   "enumMiniWinType_SecondFrontClear",
	64:   "enumMiniWinType_PongSelfDrawn",
	128:  "enumMiniWinType_ChowPongkong",
	256:  "enumMiniWinType_Richi",
	512:  "enumMiniWinType_SevenPair",
	1024: "enumMiniWinType_PureSameWithMeld",
	2048: "enumMiniWinType_MixSameWithMeld",
}

var MiniWinType_value = map[string]int32{
	"enumMiniWinType_None":              0,
	"enumMiniWinType_Continuous_Banker": 1,
	"enumMiniWinType_SelfDraw":          2,
	"enumMiniWinType_NoFlowers":         4,
	"enumMiniWinType_Kong2Discard":      8,
	"enumMiniWinType_Kong2SelfDraw":     16,
	"enumMiniWinType_SecondFrontClear":  32,
	"enumMiniWinType_PongSelfDrawn":     64,
	"enumMiniWinType_ChowPongkong":      128,
	"enumMiniWinType_Richi":             256,
	"enumMiniWinType_SevenPair":         512,
	"enumMiniWinType_PureSameWithMeld":  1024,
	"enumMiniWinType_MixSameWithMeld":   2048,
}

func (x MiniWinType) Enum() *MiniWinType {
	p := new(MiniWinType)
	*p = x
	return p
}

func (x MiniWinType) String() string {
	return proto.EnumName(MiniWinType_name, int32(x))
}

func (x *MiniWinType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(MiniWinType_value, data, "MiniWinType")
	if err != nil {
		return err
	}
	*x = MiniWinType(value)
	return nil
}

func (MiniWinType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_808dfe8173d1b9cc, []int{1}
}

func init() {
	proto.RegisterEnum("mahjong.GreatWinType", GreatWinType_name, GreatWinType_value)
	proto.RegisterEnum("mahjong.MiniWinType", MiniWinType_name, MiniWinType_value)
}

func init() { proto.RegisterFile("game_mahjong_df.proto", fileDescriptor_808dfe8173d1b9cc) }

var fileDescriptor_808dfe8173d1b9cc = []byte{
	// 478 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x94, 0xcf, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0x49, 0x30, 0xc2, 0x5a, 0x38, 0x8c, 0x46, 0x14, 0xd2, 0x7f, 0xa9, 0x23, 0x9a, 0x52,
	0x7a, 0xc8, 0x81, 0x27, 0x08, 0xa4, 0x04, 0x24, 0x94, 0x52, 0x11, 0xa4, 0x1e, 0xa3, 0x25, 0x9e,
	0x24, 0x4b, 0x9d, 0x59, 0x6b, 0xed, 0x34, 0xe5, 0xe6, 0x97, 0xe3, 0x55, 0x78, 0x0e, 0x14, 0xff,
	0x29, 0x4e, 0x77, 0xe9, 0xd1, 0xfb, 0xfd, 0x76, 0x3c, 0xf3, 0xf9, 0x1b, 0x8b, 0x9d, 0xb9, 0x5c,
	0xd2, 0x64, 0x29, 0x17, 0x3f, 0x35, 0xcf, 0x27, 0xe1, 0xac, 0x17, 0x1b, 0x9d, 0x6a, 0x7c, 0x5a,
	0x9e, 0x9c, 0xfd, 0x79, 0x22, 0x9e, 0x7f, 0x32, 0x24, 0xd3, 0x2b, 0xc5, 0xdf, 0x7f, 0xc5, 0x84,
	0xbb, 0x62, 0x87, 0x78, 0xb5, 0xac, 0x9f, 0x4d, 0x2e, 0x34, 0x13, 0x3c, 0xc2, 0x8e, 0x38, 0xb4,
	0xa4, 0xc1, 0x42, 0xaf, 0x2f, 0x35, 0xcf, 0xbf, 0x68, 0x9e, 0x43, 0x03, 0xdb, 0x62, 0xcf, 0x42,
	0x86, 0x8a, 0x65, 0x74, 0x6e, 0xe4, 0x1a, 0x9a, 0x78, 0x28, 0x76, 0x2d, 0xfd, 0xee, 0xba, 0xe7,
	0x96, 0x57, 0x86, 0xc6, 0x72, 0x49, 0xe0, 0x3b, 0xab, 0x8f, 0xd4, 0x2d, 0x85, 0xb9, 0x0e, 0x78,
	0x24, 0xf6, 0xed, 0x06, 0x23, 0x92, 0x66, 0x68, 0x34, 0xa7, 0x10, 0x38, 0x0b, 0x8c, 0xe9, 0x86,
	0xf8, 0x52, 0x2a, 0x03, 0x7d, 0x3c, 0x16, 0x47, 0x96, 0x9e, 0x3f, 0xfc, 0x83, 0xb2, 0x06, 0x1e,
	0x88, 0x57, 0x16, 0xf5, 0x99, 0xe4, 0x0d, 0x31, 0x64, 0x4d, 0x3c, 0x15, 0xaf, 0x2d, 0xf5, 0xfd,
	0x2c, 0x25, 0x33, 0xd0, 0x3c, 0x25, 0x19, 0x51, 0x98, 0x0f, 0x9b, 0x79, 0x78, 0x22, 0x3a, 0x6e,
	0xf2, 0xe3, 0x6d, 0xac, 0x93, 0x8a, 0xf3, 0x71, 0x5f, 0xbc, 0xb4, 0xb8, 0x6f, 0x6a, 0xba, 0x50,
	0x90, 0x01, 0xf6, 0xc4, 0xdb, 0xff, 0x3a, 0x7a, 0xa5, 0xd2, 0xc5, 0x30, 0xd2, 0x6b, 0x32, 0x17,
	0x7a, 0x44, 0x51, 0x08, 0x59, 0xe0, 0xe6, 0x4b, 0x8b, 0x6d, 0xbe, 0x8f, 0x3d, 0x71, 0xea, 0xf2,
	0xdc, 0x8d, 0x67, 0x0d, 0x7c, 0xe3, 0x18, 0xaa, 0x5e, 0xbf, 0x04, 0x9b, 0x78, 0x22, 0x82, 0x87,
	0x0a, 0x97, 0x9c, 0x87, 0x6d, 0xd1, 0xb2, 0xa7, 0xd7, 0x3f, 0x0a, 0x73, 0x32, 0x1f, 0xbb, 0x8e,
	0x6f, 0xf6, 0x35, 0x8e, 0x35, 0x13, 0xa7, 0x49, 0x69, 0x53, 0x06, 0x67, 0xbf, 0x1f, 0x8b, 0x67,
	0x23, 0xc5, 0xaa, 0xca, 0x79, 0x4b, 0xbc, 0xd8, 0x5c, 0xab, 0x1d, 0x55, 0x31, 0xef, 0x16, 0x13,
	0xd4, 0x95, 0x81, 0xe6, 0x54, 0xf1, 0x4a, 0xaf, 0x92, 0xc9, 0x07, 0xc9, 0xd7, 0x64, 0x60, 0x93,
	0x82, 0xd6, 0x7d, 0x6c, 0x4c, 0xd1, 0x6c, 0x3b, 0xe8, 0xdb, 0xe5, 0x0b, 0xb3, 0x12, 0xf0, 0x30,
	0x10, 0x07, 0xf7, 0xe5, 0xcd, 0x40, 0xef, 0xce, 0x55, 0x32, 0x95, 0x26, 0x04, 0xbf, 0x5a, 0x36,
	0x8b, 0xb8, 0x7b, 0x07, 0xe0, 0x71, 0xe1, 0xe0, 0x76, 0x07, 0x53, 0xcd, 0x61, 0x1e, 0xf7, 0x3c,
	0xf8, 0x10, 0xb8, 0x0a, 0x6d, 0xf2, 0x51, 0xd5, 0x61, 0xe8, 0x63, 0xc7, 0xee, 0xa6, 0xda, 0xeb,
	0xeb, 0xdc, 0xe6, 0x06, 0xee, 0x15, 0xbf, 0x85, 0x3a, 0x52, 0x7a, 0xdb, 0xc4, 0xb6, 0x3d, 0x6b,
	0x6d, 0x5f, 0x3c, 0xec, 0xda, 0x7d, 0xda, 0x89, 0xf0, 0xab, 0xe5, 0xab, 0x63, 0x56, 0x1e, 0xe0,
	0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa8, 0x20, 0x03, 0xeb, 0xd1, 0x04, 0x00, 0x00,
}
