// Code generated by protoc-gen-go. DO NOT EDIT.
// source: lobby_club.proto

/*
Package club is a generated protocol buffer package.

It is generated from these files:
	lobby_club.proto

It has these top-level messages:
	MsgClubReply
	MsgClubDisplayInfo
	MsgClubMemberInfo
	MsgClubBaseInfo
	MsgCubOperGenericReply
	MsgClubInfo
	MsgClubLoadMyClubsReply
	MsgClubLoadUpdateReply
	MsgClubLoadMembersReply
	MsgCreateClubReply
	MsgClubEvent
	MsgClubLoadEventsReply
	MsgClubRoomInfo
	MsgClubLoadRoomsReply
	MsgClubFundEvent
	MsgClubLoadFundEventsReply
	MsgClubLoadReplayRoomsReply
*/
package club

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MsgClubReply struct {
	ReplyCode        *int32 `protobuf:"varint,1,req,name=replyCode" json:"replyCode,omitempty"`
	Content          []byte `protobuf:"bytes,2,opt,name=content" json:"content,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *MsgClubReply) Reset()                    { *m = MsgClubReply{} }
func (m *MsgClubReply) String() string            { return proto.CompactTextString(m) }
func (*MsgClubReply) ProtoMessage()               {}
func (*MsgClubReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *MsgClubReply) GetReplyCode() int32 {
	if m != nil && m.ReplyCode != nil {
		return *m.ReplyCode
	}
	return 0
}

func (m *MsgClubReply) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

type MsgClubDisplayInfo struct {
	Nick             *string `protobuf:"bytes,1,req,name=nick" json:"nick,omitempty"`
	Sex              *uint32 `protobuf:"varint,2,opt,name=sex" json:"sex,omitempty"`
	HeadIconURL      *string `protobuf:"bytes,3,opt,name=headIconURL" json:"headIconURL,omitempty"`
	AvatarID         *int32  `protobuf:"varint,4,opt,name=avatarID" json:"avatarID,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MsgClubDisplayInfo) Reset()                    { *m = MsgClubDisplayInfo{} }
func (m *MsgClubDisplayInfo) String() string            { return proto.CompactTextString(m) }
func (*MsgClubDisplayInfo) ProtoMessage()               {}
func (*MsgClubDisplayInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *MsgClubDisplayInfo) GetNick() string {
	if m != nil && m.Nick != nil {
		return *m.Nick
	}
	return ""
}

func (m *MsgClubDisplayInfo) GetSex() uint32 {
	if m != nil && m.Sex != nil {
		return *m.Sex
	}
	return 0
}

func (m *MsgClubDisplayInfo) GetHeadIconURL() string {
	if m != nil && m.HeadIconURL != nil {
		return *m.HeadIconURL
	}
	return ""
}

func (m *MsgClubDisplayInfo) GetAvatarID() int32 {
	if m != nil && m.AvatarID != nil {
		return *m.AvatarID
	}
	return 0
}

// 俱乐部成员信息
type MsgClubMemberInfo struct {
	UserID           *string             `protobuf:"bytes,1,req,name=userID" json:"userID,omitempty"`
	DisplayInfo      *MsgClubDisplayInfo `protobuf:"bytes,2,opt,name=displayInfo" json:"displayInfo,omitempty"`
	Online           *bool               `protobuf:"varint,3,opt,name=online" json:"online,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *MsgClubMemberInfo) Reset()                    { *m = MsgClubMemberInfo{} }
func (m *MsgClubMemberInfo) String() string            { return proto.CompactTextString(m) }
func (*MsgClubMemberInfo) ProtoMessage()               {}
func (*MsgClubMemberInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *MsgClubMemberInfo) GetUserID() string {
	if m != nil && m.UserID != nil {
		return *m.UserID
	}
	return ""
}

func (m *MsgClubMemberInfo) GetDisplayInfo() *MsgClubDisplayInfo {
	if m != nil {
		return m.DisplayInfo
	}
	return nil
}

func (m *MsgClubMemberInfo) GetOnline() bool {
	if m != nil && m.Online != nil {
		return *m.Online
	}
	return false
}

// 俱乐部的基本信息
type MsgClubBaseInfo struct {
	ClubNumber       *string `protobuf:"bytes,1,req,name=clubNumber" json:"clubNumber,omitempty"`
	ClubName         *string `protobuf:"bytes,2,opt,name=clubName" json:"clubName,omitempty"`
	ClubID           *string `protobuf:"bytes,3,opt,name=clubID" json:"clubID,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MsgClubBaseInfo) Reset()                    { *m = MsgClubBaseInfo{} }
func (m *MsgClubBaseInfo) String() string            { return proto.CompactTextString(m) }
func (*MsgClubBaseInfo) ProtoMessage()               {}
func (*MsgClubBaseInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *MsgClubBaseInfo) GetClubNumber() string {
	if m != nil && m.ClubNumber != nil {
		return *m.ClubNumber
	}
	return ""
}

func (m *MsgClubBaseInfo) GetClubName() string {
	if m != nil && m.ClubName != nil {
		return *m.ClubName
	}
	return ""
}

func (m *MsgClubBaseInfo) GetClubID() string {
	if m != nil && m.ClubID != nil {
		return *m.ClubID
	}
	return ""
}

// 俱乐部操作通用回复，免得定义太多消息体
type MsgCubOperGenericReply struct {
	ErrorCode        *int32  `protobuf:"varint,1,req,name=errorCode" json:"errorCode,omitempty"`
	Extra            *string `protobuf:"bytes,2,opt,name=extra" json:"extra,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MsgCubOperGenericReply) Reset()                    { *m = MsgCubOperGenericReply{} }
func (m *MsgCubOperGenericReply) String() string            { return proto.CompactTextString(m) }
func (*MsgCubOperGenericReply) ProtoMessage()               {}
func (*MsgCubOperGenericReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *MsgCubOperGenericReply) GetErrorCode() int32 {
	if m != nil && m.ErrorCode != nil {
		return *m.ErrorCode
	}
	return 0
}

func (m *MsgCubOperGenericReply) GetExtra() string {
	if m != nil && m.Extra != nil {
		return *m.Extra
	}
	return ""
}

// 俱乐部信息
type MsgClubInfo struct {
	BaseInfo         *MsgClubBaseInfo `protobuf:"bytes,1,opt,name=baseInfo" json:"baseInfo,omitempty"`
	CreatorUserID    *string          `protobuf:"bytes,2,opt,name=creatorUserID" json:"creatorUserID,omitempty"`
	ClubLevel        *int32           `protobuf:"varint,3,opt,name=clubLevel" json:"clubLevel,omitempty"`
	Wanka            *int32           `protobuf:"varint,4,opt,name=wanka" json:"wanka,omitempty"`
	Candy            *int32           `protobuf:"varint,5,opt,name=candy" json:"candy,omitempty"`
	MaxMember        *int32           `protobuf:"varint,6,opt,name=maxMember" json:"maxMember,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *MsgClubInfo) Reset()                    { *m = MsgClubInfo{} }
func (m *MsgClubInfo) String() string            { return proto.CompactTextString(m) }
func (*MsgClubInfo) ProtoMessage()               {}
func (*MsgClubInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *MsgClubInfo) GetBaseInfo() *MsgClubBaseInfo {
	if m != nil {
		return m.BaseInfo
	}
	return nil
}

func (m *MsgClubInfo) GetCreatorUserID() string {
	if m != nil && m.CreatorUserID != nil {
		return *m.CreatorUserID
	}
	return ""
}

func (m *MsgClubInfo) GetClubLevel() int32 {
	if m != nil && m.ClubLevel != nil {
		return *m.ClubLevel
	}
	return 0
}

func (m *MsgClubInfo) GetWanka() int32 {
	if m != nil && m.Wanka != nil {
		return *m.Wanka
	}
	return 0
}

func (m *MsgClubInfo) GetCandy() int32 {
	if m != nil && m.Candy != nil {
		return *m.Candy
	}
	return 0
}

func (m *MsgClubInfo) GetMaxMember() int32 {
	if m != nil && m.MaxMember != nil {
		return *m.MaxMember
	}
	return 0
}

// 加载自己的俱乐部
type MsgClubLoadMyClubsReply struct {
	Clubs            []*MsgClubInfo `protobuf:"bytes,1,rep,name=clubs" json:"clubs,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *MsgClubLoadMyClubsReply) Reset()                    { *m = MsgClubLoadMyClubsReply{} }
func (m *MsgClubLoadMyClubsReply) String() string            { return proto.CompactTextString(m) }
func (*MsgClubLoadMyClubsReply) ProtoMessage()               {}
func (*MsgClubLoadMyClubsReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *MsgClubLoadMyClubsReply) GetClubs() []*MsgClubInfo {
	if m != nil {
		return m.Clubs
	}
	return nil
}

// 加载俱乐部更新回复
type MsgClubLoadUpdateReply struct {
	ClubsUpdated     []*MsgClubInfo `protobuf:"bytes,1,rep,name=clubsUpdated" json:"clubsUpdated,omitempty"`
	ClubIDsRemoved   []string       `protobuf:"bytes,2,rep,name=clubIDsRemoved" json:"clubIDsRemoved,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *MsgClubLoadUpdateReply) Reset()                    { *m = MsgClubLoadUpdateReply{} }
func (m *MsgClubLoadUpdateReply) String() string            { return proto.CompactTextString(m) }
func (*MsgClubLoadUpdateReply) ProtoMessage()               {}
func (*MsgClubLoadUpdateReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *MsgClubLoadUpdateReply) GetClubsUpdated() []*MsgClubInfo {
	if m != nil {
		return m.ClubsUpdated
	}
	return nil
}

func (m *MsgClubLoadUpdateReply) GetClubIDsRemoved() []string {
	if m != nil {
		return m.ClubIDsRemoved
	}
	return nil
}

// 服务器回复请求成员列表
type MsgClubLoadMembersReply struct {
	Members          []*MsgClubMemberInfo `protobuf:"bytes,1,rep,name=members" json:"members,omitempty"`
	Cursor           *int32               `protobuf:"varint,2,opt,name=cursor" json:"cursor,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *MsgClubLoadMembersReply) Reset()                    { *m = MsgClubLoadMembersReply{} }
func (m *MsgClubLoadMembersReply) String() string            { return proto.CompactTextString(m) }
func (*MsgClubLoadMembersReply) ProtoMessage()               {}
func (*MsgClubLoadMembersReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *MsgClubLoadMembersReply) GetMembers() []*MsgClubMemberInfo {
	if m != nil {
		return m.Members
	}
	return nil
}

func (m *MsgClubLoadMembersReply) GetCursor() int32 {
	if m != nil && m.Cursor != nil {
		return *m.Cursor
	}
	return 0
}

// 创建俱乐部服务器给客户端的回复
type MsgCreateClubReply struct {
	ClubInfo         *MsgClubInfo `protobuf:"bytes,1,opt,name=clubInfo" json:"clubInfo,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *MsgCreateClubReply) Reset()                    { *m = MsgCreateClubReply{} }
func (m *MsgCreateClubReply) String() string            { return proto.CompactTextString(m) }
func (*MsgCreateClubReply) ProtoMessage()               {}
func (*MsgCreateClubReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *MsgCreateClubReply) GetClubInfo() *MsgClubInfo {
	if m != nil {
		return m.ClubInfo
	}
	return nil
}

// 俱乐部事件，注意和MsgClubNotification不同，事件是系统生成，不可设置
type MsgClubEvent struct {
	EvtType          *int32              `protobuf:"varint,1,req,name=evtType" json:"evtType,omitempty"`
	Id               *uint32             `protobuf:"varint,2,req,name=Id" json:"Id,omitempty"`
	GeneratedTime    *uint32             `protobuf:"varint,3,req,name=generatedTime" json:"generatedTime,omitempty"`
	To               *string             `protobuf:"bytes,4,opt,name=to" json:"to,omitempty"`
	Content          []byte              `protobuf:"bytes,5,opt,name=content" json:"content,omitempty"`
	Unread           *bool               `protobuf:"varint,6,opt,name=unread" json:"unread,omitempty"`
	NeedHandle       *bool               `protobuf:"varint,7,opt,name=needHandle" json:"needHandle,omitempty"`
	UserID1          *string             `protobuf:"bytes,8,opt,name=userID1" json:"userID1,omitempty"`
	DisplayInfo1     *MsgClubDisplayInfo `protobuf:"bytes,9,opt,name=displayInfo1" json:"displayInfo1,omitempty"`
	ApprovalResult   *int32              `protobuf:"varint,10,opt,name=approvalResult" json:"approvalResult,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *MsgClubEvent) Reset()                    { *m = MsgClubEvent{} }
func (m *MsgClubEvent) String() string            { return proto.CompactTextString(m) }
func (*MsgClubEvent) ProtoMessage()               {}
func (*MsgClubEvent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *MsgClubEvent) GetEvtType() int32 {
	if m != nil && m.EvtType != nil {
		return *m.EvtType
	}
	return 0
}

func (m *MsgClubEvent) GetId() uint32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *MsgClubEvent) GetGeneratedTime() uint32 {
	if m != nil && m.GeneratedTime != nil {
		return *m.GeneratedTime
	}
	return 0
}

func (m *MsgClubEvent) GetTo() string {
	if m != nil && m.To != nil {
		return *m.To
	}
	return ""
}

func (m *MsgClubEvent) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *MsgClubEvent) GetUnread() bool {
	if m != nil && m.Unread != nil {
		return *m.Unread
	}
	return false
}

func (m *MsgClubEvent) GetNeedHandle() bool {
	if m != nil && m.NeedHandle != nil {
		return *m.NeedHandle
	}
	return false
}

func (m *MsgClubEvent) GetUserID1() string {
	if m != nil && m.UserID1 != nil {
		return *m.UserID1
	}
	return ""
}

func (m *MsgClubEvent) GetDisplayInfo1() *MsgClubDisplayInfo {
	if m != nil {
		return m.DisplayInfo1
	}
	return nil
}

func (m *MsgClubEvent) GetApprovalResult() int32 {
	if m != nil && m.ApprovalResult != nil {
		return *m.ApprovalResult
	}
	return 0
}

// 服务器回复请求事件列表
type MsgClubLoadEventsReply struct {
	Events           []*MsgClubEvent `protobuf:"bytes,1,rep,name=events" json:"events,omitempty"`
	Cursor           *int32          `protobuf:"varint,2,opt,name=cursor" json:"cursor,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *MsgClubLoadEventsReply) Reset()                    { *m = MsgClubLoadEventsReply{} }
func (m *MsgClubLoadEventsReply) String() string            { return proto.CompactTextString(m) }
func (*MsgClubLoadEventsReply) ProtoMessage()               {}
func (*MsgClubLoadEventsReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *MsgClubLoadEventsReply) GetEvents() []*MsgClubEvent {
	if m != nil {
		return m.Events
	}
	return nil
}

func (m *MsgClubLoadEventsReply) GetCursor() int32 {
	if m != nil && m.Cursor != nil {
		return *m.Cursor
	}
	return 0
}

// 俱乐部房间信息
type MsgClubRoomInfo struct {
	RoomType         *int32  `protobuf:"varint,1,req,name=roomType" json:"roomType,omitempty"`
	RoomRuleJSON     *string `protobuf:"bytes,2,opt,name=roomRuleJSON" json:"roomRuleJSON,omitempty"`
	PlayerNumber     *int32  `protobuf:"varint,3,opt,name=playerNumber" json:"playerNumber,omitempty"`
	RoomState        *int32  `protobuf:"varint,4,opt,name=roomState" json:"roomState,omitempty"`
	RoomNumber       *string `protobuf:"bytes,5,opt,name=roomNumber" json:"roomNumber,omitempty"`
	RoomUUID         *string `protobuf:"bytes,6,opt,name=roomUUID" json:"roomUUID,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MsgClubRoomInfo) Reset()                    { *m = MsgClubRoomInfo{} }
func (m *MsgClubRoomInfo) String() string            { return proto.CompactTextString(m) }
func (*MsgClubRoomInfo) ProtoMessage()               {}
func (*MsgClubRoomInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *MsgClubRoomInfo) GetRoomType() int32 {
	if m != nil && m.RoomType != nil {
		return *m.RoomType
	}
	return 0
}

func (m *MsgClubRoomInfo) GetRoomRuleJSON() string {
	if m != nil && m.RoomRuleJSON != nil {
		return *m.RoomRuleJSON
	}
	return ""
}

func (m *MsgClubRoomInfo) GetPlayerNumber() int32 {
	if m != nil && m.PlayerNumber != nil {
		return *m.PlayerNumber
	}
	return 0
}

func (m *MsgClubRoomInfo) GetRoomState() int32 {
	if m != nil && m.RoomState != nil {
		return *m.RoomState
	}
	return 0
}

func (m *MsgClubRoomInfo) GetRoomNumber() string {
	if m != nil && m.RoomNumber != nil {
		return *m.RoomNumber
	}
	return ""
}

func (m *MsgClubRoomInfo) GetRoomUUID() string {
	if m != nil && m.RoomUUID != nil {
		return *m.RoomUUID
	}
	return ""
}

// 服务器回复请求俱乐部房间列表
type MsgClubLoadRoomsReply struct {
	Rooms            []*MsgClubRoomInfo `protobuf:"bytes,1,rep,name=rooms" json:"rooms,omitempty"`
	Cursor           *int32             `protobuf:"varint,2,opt,name=cursor" json:"cursor,omitempty"`
	TotalRoomCount   *int32             `protobuf:"varint,3,opt,name=totalRoomCount" json:"totalRoomCount,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *MsgClubLoadRoomsReply) Reset()                    { *m = MsgClubLoadRoomsReply{} }
func (m *MsgClubLoadRoomsReply) String() string            { return proto.CompactTextString(m) }
func (*MsgClubLoadRoomsReply) ProtoMessage()               {}
func (*MsgClubLoadRoomsReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *MsgClubLoadRoomsReply) GetRooms() []*MsgClubRoomInfo {
	if m != nil {
		return m.Rooms
	}
	return nil
}

func (m *MsgClubLoadRoomsReply) GetCursor() int32 {
	if m != nil && m.Cursor != nil {
		return *m.Cursor
	}
	return 0
}

func (m *MsgClubLoadRoomsReply) GetTotalRoomCount() int32 {
	if m != nil && m.TotalRoomCount != nil {
		return *m.TotalRoomCount
	}
	return 0
}

// 俱乐部基金事件
type MsgClubFundEvent struct {
	EvtType          *int32  `protobuf:"varint,1,req,name=evtType" json:"evtType,omitempty"`
	GeneratedTime    *uint32 `protobuf:"varint,2,req,name=generatedTime" json:"generatedTime,omitempty"`
	UserID           *string `protobuf:"bytes,3,req,name=userID" json:"userID,omitempty"`
	Amount           *int32  `protobuf:"varint,4,req,name=amount" json:"amount,omitempty"`
	Total            *int32  `protobuf:"varint,5,req,name=total" json:"total,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MsgClubFundEvent) Reset()                    { *m = MsgClubFundEvent{} }
func (m *MsgClubFundEvent) String() string            { return proto.CompactTextString(m) }
func (*MsgClubFundEvent) ProtoMessage()               {}
func (*MsgClubFundEvent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *MsgClubFundEvent) GetEvtType() int32 {
	if m != nil && m.EvtType != nil {
		return *m.EvtType
	}
	return 0
}

func (m *MsgClubFundEvent) GetGeneratedTime() uint32 {
	if m != nil && m.GeneratedTime != nil {
		return *m.GeneratedTime
	}
	return 0
}

func (m *MsgClubFundEvent) GetUserID() string {
	if m != nil && m.UserID != nil {
		return *m.UserID
	}
	return ""
}

func (m *MsgClubFundEvent) GetAmount() int32 {
	if m != nil && m.Amount != nil {
		return *m.Amount
	}
	return 0
}

func (m *MsgClubFundEvent) GetTotal() int32 {
	if m != nil && m.Total != nil {
		return *m.Total
	}
	return 0
}

// 加载俱乐部基金事件的回复
type MsgClubLoadFundEventsReply struct {
	Events           []*MsgClubFundEvent `protobuf:"bytes,1,rep,name=events" json:"events,omitempty"`
	Cursor           *int32              `protobuf:"varint,2,opt,name=cursor" json:"cursor,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *MsgClubLoadFundEventsReply) Reset()                    { *m = MsgClubLoadFundEventsReply{} }
func (m *MsgClubLoadFundEventsReply) String() string            { return proto.CompactTextString(m) }
func (*MsgClubLoadFundEventsReply) ProtoMessage()               {}
func (*MsgClubLoadFundEventsReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *MsgClubLoadFundEventsReply) GetEvents() []*MsgClubFundEvent {
	if m != nil {
		return m.Events
	}
	return nil
}

func (m *MsgClubLoadFundEventsReply) GetCursor() int32 {
	if m != nil && m.Cursor != nil {
		return *m.Cursor
	}
	return 0
}

// 加载回播房间的回复
type MsgClubLoadReplayRoomsReply struct {
	GZipBytes        []byte `protobuf:"bytes,1,opt,name=gZipBytes" json:"gZipBytes,omitempty"`
	Cursor           *int32 `protobuf:"varint,2,opt,name=cursor" json:"cursor,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *MsgClubLoadReplayRoomsReply) Reset()                    { *m = MsgClubLoadReplayRoomsReply{} }
func (m *MsgClubLoadReplayRoomsReply) String() string            { return proto.CompactTextString(m) }
func (*MsgClubLoadReplayRoomsReply) ProtoMessage()               {}
func (*MsgClubLoadReplayRoomsReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *MsgClubLoadReplayRoomsReply) GetGZipBytes() []byte {
	if m != nil {
		return m.GZipBytes
	}
	return nil
}

func (m *MsgClubLoadReplayRoomsReply) GetCursor() int32 {
	if m != nil && m.Cursor != nil {
		return *m.Cursor
	}
	return 0
}

func init() {
	proto.RegisterType((*MsgClubReply)(nil), "club.MsgClubReply")
	proto.RegisterType((*MsgClubDisplayInfo)(nil), "club.MsgClubDisplayInfo")
	proto.RegisterType((*MsgClubMemberInfo)(nil), "club.MsgClubMemberInfo")
	proto.RegisterType((*MsgClubBaseInfo)(nil), "club.MsgClubBaseInfo")
	proto.RegisterType((*MsgCubOperGenericReply)(nil), "club.MsgCubOperGenericReply")
	proto.RegisterType((*MsgClubInfo)(nil), "club.MsgClubInfo")
	proto.RegisterType((*MsgClubLoadMyClubsReply)(nil), "club.MsgClubLoadMyClubsReply")
	proto.RegisterType((*MsgClubLoadUpdateReply)(nil), "club.MsgClubLoadUpdateReply")
	proto.RegisterType((*MsgClubLoadMembersReply)(nil), "club.MsgClubLoadMembersReply")
	proto.RegisterType((*MsgCreateClubReply)(nil), "club.MsgCreateClubReply")
	proto.RegisterType((*MsgClubEvent)(nil), "club.MsgClubEvent")
	proto.RegisterType((*MsgClubLoadEventsReply)(nil), "club.MsgClubLoadEventsReply")
	proto.RegisterType((*MsgClubRoomInfo)(nil), "club.MsgClubRoomInfo")
	proto.RegisterType((*MsgClubLoadRoomsReply)(nil), "club.MsgClubLoadRoomsReply")
	proto.RegisterType((*MsgClubFundEvent)(nil), "club.MsgClubFundEvent")
	proto.RegisterType((*MsgClubLoadFundEventsReply)(nil), "club.MsgClubLoadFundEventsReply")
	proto.RegisterType((*MsgClubLoadReplayRoomsReply)(nil), "club.MsgClubLoadReplayRoomsReply")
}

func init() { proto.RegisterFile("lobby_club.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 782 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x54, 0x51, 0x6f, 0xe3, 0x44,
	0x10, 0x96, 0x93, 0x3a, 0x8d, 0x27, 0x6e, 0x9a, 0x98, 0x6b, 0xcf, 0x82, 0x97, 0xc8, 0x20, 0x2e,
	0x2f, 0x54, 0xba, 0xbe, 0x01, 0x2f, 0xe8, 0x5a, 0x38, 0x82, 0xda, 0x3b, 0x29, 0x6d, 0x90, 0xe0,
	0x05, 0xad, 0xed, 0xa1, 0x44, 0x67, 0xef, 0x5a, 0xeb, 0x75, 0x68, 0xfe, 0x01, 0xaf, 0xfc, 0x3f,
	0x7e, 0x0c, 0x9a, 0xd9, 0x4d, 0x6a, 0x87, 0xab, 0x78, 0xf3, 0x8e, 0x66, 0xbe, 0xf9, 0xbe, 0x6f,
	0x66, 0x0c, 0x93, 0x42, 0xa5, 0xe9, 0xf6, 0xb7, 0xac, 0x68, 0xd2, 0x8b, 0x4a, 0x2b, 0xa3, 0xa2,
	0x23, 0xfa, 0x4e, 0x2e, 0x21, 0xbc, 0xad, 0x1f, 0xae, 0x8a, 0x26, 0x5d, 0x62, 0x55, 0x6c, 0xa3,
	0x29, 0x04, 0x9a, 0x3e, 0xae, 0x54, 0x8e, 0xb1, 0x37, 0xeb, 0xcd, 0xfd, 0xe8, 0x14, 0x8e, 0x33,
	0x25, 0x0d, 0x4a, 0x13, 0xf7, 0x66, 0xde, 0x3c, 0x4c, 0x7e, 0x86, 0xc8, 0xd5, 0x5c, 0xaf, 0xeb,
	0xaa, 0x10, 0xdb, 0x85, 0xfc, 0x5d, 0x45, 0x21, 0x1c, 0xc9, 0x75, 0xf6, 0x81, 0x8b, 0x82, 0x68,
	0x04, 0xfd, 0x1a, 0x1f, 0xb9, 0xe0, 0x24, 0xfa, 0x04, 0x46, 0x7f, 0xa0, 0xc8, 0x17, 0x99, 0x92,
	0xab, 0xe5, 0x4d, 0xdc, 0x9f, 0x79, 0xf3, 0x20, 0x9a, 0xc0, 0x50, 0x6c, 0x84, 0x11, 0x7a, 0x71,
	0x1d, 0x1f, 0xcd, 0xbc, 0xb9, 0x9f, 0xa4, 0x30, 0x75, 0xb8, 0xb7, 0x58, 0xa6, 0xa8, 0x19, 0x76,
	0x0c, 0x83, 0xa6, 0x46, 0x4a, 0xb2, 0xc0, 0x5f, 0xc1, 0x28, 0x7f, 0xea, 0xca, 0x0d, 0x46, 0x97,
	0xf1, 0x05, 0x0b, 0xfb, 0x08, 0xab, 0x31, 0x0c, 0x94, 0x2c, 0xd6, 0x12, 0xb9, 0xeb, 0x30, 0x79,
	0x0b, 0xa7, 0x2e, 0xeb, 0x8d, 0xa8, 0x91, 0x53, 0x22, 0x00, 0xaa, 0x7e, 0xd7, 0x50, 0x4f, 0xd7,
	0x65, 0x02, 0x43, 0x8e, 0x89, 0x12, 0xb9, 0x45, 0x40, 0x40, 0x14, 0x59, 0x5c, 0x5b, 0xfa, 0xc9,
	0x37, 0x70, 0x4e, 0x40, 0x4d, 0xfa, 0xbe, 0x42, 0xfd, 0x16, 0x25, 0xea, 0x75, 0xb6, 0xb7, 0x10,
	0xb5, 0x56, 0xba, 0x65, 0xe1, 0x09, 0xf8, 0xf8, 0x68, 0xb4, 0xb0, 0x58, 0xc9, 0xdf, 0x1e, 0x8c,
	0x1c, 0x0b, 0x66, 0xf0, 0x0a, 0x86, 0xa9, 0x63, 0x13, 0x7b, 0x2c, 0xe8, 0xac, 0x23, 0x68, 0x4f,
	0xf5, 0x0c, 0x4e, 0x32, 0x8d, 0xc2, 0x28, 0xbd, 0xb2, 0x9e, 0x58, 0x6e, 0x53, 0x08, 0x28, 0xfd,
	0x06, 0x37, 0x58, 0x30, 0x3d, 0xee, 0xf8, 0xa7, 0x90, 0x1f, 0x84, 0xb5, 0x96, 0x9e, 0x99, 0x90,
	0xf9, 0x36, 0xf6, 0xf9, 0x39, 0x85, 0xa0, 0x14, 0x8f, 0xd6, 0xe5, 0x78, 0xc0, 0xe6, 0x7f, 0x0b,
	0x2f, 0x5d, 0xb7, 0x1b, 0x25, 0xf2, 0xdb, 0x2d, 0x7d, 0xd5, 0x56, 0xd0, 0x0c, 0x7c, 0x82, 0xaf,
	0x63, 0x6f, 0xd6, 0x9f, 0x8f, 0x2e, 0xa7, 0x1d, 0x6e, 0xc4, 0x2b, 0xf9, 0xc5, 0x9a, 0xe1, 0x8a,
	0x57, 0x55, 0x2e, 0x0c, 0xda, 0xda, 0x57, 0x10, 0x72, 0xad, 0x8d, 0xe5, 0xcf, 0x42, 0x44, 0xe7,
	0x30, 0xb6, 0xfe, 0xd6, 0x4b, 0x2c, 0xd5, 0x06, 0xf3, 0xb8, 0x37, 0xeb, 0xcf, 0x83, 0xe4, 0xae,
	0xcb, 0x8b, 0x29, 0x3b, 0x5e, 0x73, 0x38, 0x2e, 0xed, 0xdb, 0xc1, 0xbe, 0xec, 0xc0, 0x76, 0x97,
	0x28, 0x6b, 0x74, 0xad, 0x34, 0x1b, 0xe6, 0x27, 0x5f, 0xdb, 0x0d, 0x26, 0x2b, 0xf1, 0x69, 0xf7,
	0x3f, 0xb7, 0x43, 0x6f, 0x8d, 0xe1, 0x23, 0x52, 0xff, 0xf1, 0xf6, 0x17, 0xf3, 0xfd, 0x06, 0xa5,
	0xa1, 0xf3, 0xc0, 0x8d, 0xb9, 0xdf, 0x56, 0xbb, 0x61, 0x03, 0xf4, 0x16, 0xc4, 0xbe, 0x37, 0x3f,
	0xa1, 0x81, 0x3d, 0xd0, 0x6e, 0x90, 0xf6, 0xfb, 0x75, 0x49, 0x5b, 0x48, 0x61, 0x80, 0x9e, 0x51,
	0x3c, 0x9a, 0xa0, 0x7d, 0x5e, 0x34, 0x9c, 0x90, 0x37, 0x5e, 0x6a, 0x14, 0x39, 0x4f, 0x66, 0x48,
	0xfb, 0x29, 0x11, 0xf3, 0x1f, 0x85, 0xcc, 0x0b, 0x8c, 0x8f, 0x39, 0x76, 0x0a, 0xc7, 0xf6, 0x2a,
	0x5e, 0xc7, 0x43, 0x46, 0xb9, 0x80, 0xb0, 0x75, 0x16, 0xaf, 0xe3, 0xe0, 0x7f, 0xee, 0xe2, 0x1c,
	0xc6, 0xa2, 0xaa, 0xb4, 0xda, 0x88, 0x62, 0x89, 0x75, 0x53, 0x98, 0x18, 0xd8, 0x99, 0x9b, 0xce,
	0x24, 0x59, 0xa1, 0x73, 0x3b, 0x81, 0x01, 0xf2, 0xd3, 0x99, 0x1d, 0x75, 0xb0, 0xad, 0x17, 0x87,
	0x3e, 0xff, 0xe5, 0xed, 0xcf, 0x6d, 0xa9, 0x54, 0xc9, 0x9d, 0x27, 0x30, 0xd4, 0x4a, 0x95, 0x2d,
	0xc3, 0x5e, 0x40, 0x48, 0x91, 0x65, 0x53, 0xe0, 0x4f, 0x77, 0xef, 0xdf, 0xb9, 0xa5, 0x7e, 0x01,
	0x21, 0xb1, 0x45, 0xed, 0x0e, 0xb3, 0xbf, 0xdb, 0x5c, 0xca, 0xbd, 0x33, 0xc2, 0xa0, 0xdb, 0xed,
	0x08, 0x80, 0x42, 0x2e, 0xcd, 0xdf, 0xfd, 0x5c, 0x28, 0xb6, 0x5a, 0x2d, 0xae, 0xd9, 0xc5, 0x20,
	0x41, 0x38, 0x6b, 0x09, 0x23, 0x36, 0x4e, 0xd7, 0x17, 0xe0, 0x53, 0xea, 0x4e, 0x56, 0xf7, 0xf2,
	0xf6, 0xac, 0x0f, 0x94, 0x91, 0x7f, 0x46, 0x19, 0x51, 0x50, 0xc2, 0x95, 0x6a, 0xa4, 0xb1, 0xfc,
	0x92, 0x35, 0x4c, 0x5c, 0xe9, 0x0f, 0x8d, 0xcc, 0x9f, 0xd9, 0x90, 0xff, 0x6c, 0x85, 0x5d, 0x96,
	0xa7, 0x5f, 0x5d, 0x9f, 0x7f, 0x42, 0x63, 0x18, 0x88, 0x92, 0xb1, 0x8f, 0x76, 0x7f, 0x11, 0xee,
	0x19, 0xfb, 0xf4, 0x4c, 0xee, 0xe1, 0xd3, 0x96, 0xa2, 0x7d, 0x3b, 0x27, 0xeb, 0xcb, 0x83, 0x71,
	0x9d, 0x77, 0x74, 0x3d, 0x91, 0x3b, 0x1c, 0xd9, 0x77, 0xf0, 0x59, 0xdb, 0x27, 0xa4, 0x19, 0xb4,
	0xdc, 0x9a, 0x42, 0xf0, 0xf0, 0xeb, 0xba, 0x7a, 0xb3, 0x35, 0x58, 0xf3, 0x91, 0x84, 0x87, 0x08,
	0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0x48, 0xc1, 0xed, 0x12, 0x6b, 0x06, 0x00, 0x00,
}
