//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: game_mahjong.proto
namespace mahjong
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GameMessage")]
  public partial class GameMessage : global::ProtoBuf.IExtensible
  {
    public GameMessage() {}
    
    private int _Ops;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Ops", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Ops
    {
      get { return _Ops; }
      set { _Ops = value; }
    }

    private byte[] _Data = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] Data
    {
      get { return _Data; }
      set { _Data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgMeldTile")]
  public partial class MsgMeldTile : global::ProtoBuf.IExtensible
  {
    public MsgMeldTile() {}
    
    private int _meldType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"meldType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int meldType
    {
      get { return _meldType; }
      set { _meldType = value; }
    }
    private int _tile1;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"tile1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int tile1
    {
      get { return _tile1; }
      set { _tile1 = value; }
    }

    private int _contributor = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"contributor", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int contributor
    {
      get { return _contributor; }
      set { _contributor = value; }
    }

    private int _chowTile = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"chowTile", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int chowTile
    {
      get { return _chowTile; }
      set { _chowTile = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgPlayerTileList")]
  public partial class MsgPlayerTileList : global::ProtoBuf.IExtensible
  {
    public MsgPlayerTileList() {}
    
    private int _chairID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"chairID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int chairID
    {
      get { return _chairID; }
      set { _chairID = value; }
    }
    private int _tileCountInHand;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"tileCountInHand", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int tileCountInHand
    {
      get { return _tileCountInHand; }
      set { _tileCountInHand = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _tilesHand = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(3, Name=@"tilesHand", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> tilesHand
    {
      get { return _tilesHand; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _tilesFlower = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(4, Name=@"tilesFlower", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> tilesFlower
    {
      get { return _tilesFlower; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _tilesDiscard = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(5, Name=@"tilesDiscard", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> tilesDiscard
    {
      get { return _tilesDiscard; }
    }
  
    private readonly global::System.Collections.Generic.List<mahjong.MsgMeldTile> _melds = new global::System.Collections.Generic.List<mahjong.MsgMeldTile>();
    [global::ProtoBuf.ProtoMember(6, Name=@"melds", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<mahjong.MsgMeldTile> melds
    {
      get { return _melds; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgDeal")]
  public partial class MsgDeal : global::ProtoBuf.IExtensible
  {
    public MsgDeal() {}
    
    private int _bankerChairID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"bankerChairID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int bankerChairID
    {
      get { return _bankerChairID; }
      set { _bankerChairID = value; }
    }
    private int _windFlowerID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"windFlowerID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int windFlowerID
    {
      get { return _windFlowerID; }
      set { _windFlowerID = value; }
    }
    private readonly global::System.Collections.Generic.List<mahjong.MsgPlayerTileList> _playerTileLists = new global::System.Collections.Generic.List<mahjong.MsgPlayerTileList>();
    [global::ProtoBuf.ProtoMember(3, Name=@"playerTileLists", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<mahjong.MsgPlayerTileList> playerTileLists
    {
      get { return _playerTileLists; }
    }
  
    private int _tilesInWall;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"tilesInWall", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int tilesInWall
    {
      get { return _tilesInWall; }
      set { _tilesInWall = value; }
    }

    private int _dice1 = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"dice1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int dice1
    {
      get { return _dice1; }
      set { _dice1 = value; }
    }

    private int _dice2 = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"dice2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int dice2
    {
      get { return _dice2; }
      set { _dice2 = value; }
    }

    private bool _isContinuousBanker = default(bool);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"isContinuousBanker", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isContinuousBanker
    {
      get { return _isContinuousBanker; }
      set { _isContinuousBanker = value; }
    }

    private int _markup = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"markup", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int markup
    {
      get { return _markup; }
      set { _markup = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgReadyHandTips")]
  public partial class MsgReadyHandTips : global::ProtoBuf.IExtensible
  {
    public MsgReadyHandTips() {}
    
    private int _targetTile;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"targetTile", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int targetTile
    {
      get { return _targetTile; }
      set { _targetTile = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _readyHandList = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"readyHandList", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> readyHandList
    {
      get { return _readyHandList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgAllowPlayerAction")]
  public partial class MsgAllowPlayerAction : global::ProtoBuf.IExtensible
  {
    public MsgAllowPlayerAction() {}
    
    private int _qaIndex;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"qaIndex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int qaIndex
    {
      get { return _qaIndex; }
      set { _qaIndex = value; }
    }
    private int _actionChairID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"actionChairID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int actionChairID
    {
      get { return _actionChairID; }
      set { _actionChairID = value; }
    }
    private int _allowedActions;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"allowedActions", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int allowedActions
    {
      get { return _allowedActions; }
      set { _allowedActions = value; }
    }

    private int _timeoutInSeconds = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"timeoutInSeconds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int timeoutInSeconds
    {
      get { return _timeoutInSeconds; }
      set { _timeoutInSeconds = value; }
    }
    private readonly global::System.Collections.Generic.List<mahjong.MsgReadyHandTips> _tipsForAction = new global::System.Collections.Generic.List<mahjong.MsgReadyHandTips>();
    [global::ProtoBuf.ProtoMember(5, Name=@"tipsForAction", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<mahjong.MsgReadyHandTips> tipsForAction
    {
      get { return _tipsForAction; }
    }
  
    private readonly global::System.Collections.Generic.List<mahjong.MsgMeldTile> _meldsForAction = new global::System.Collections.Generic.List<mahjong.MsgMeldTile>();
    [global::ProtoBuf.ProtoMember(6, Name=@"meldsForAction", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<mahjong.MsgMeldTile> meldsForAction
    {
      get { return _meldsForAction; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgAllowPlayerReAction")]
  public partial class MsgAllowPlayerReAction : global::ProtoBuf.IExtensible
  {
    public MsgAllowPlayerReAction() {}
    
    private int _qaIndex;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"qaIndex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int qaIndex
    {
      get { return _qaIndex; }
      set { _qaIndex = value; }
    }
    private int _actionChairID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"actionChairID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int actionChairID
    {
      get { return _actionChairID; }
      set { _actionChairID = value; }
    }
    private int _allowedActions;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"allowedActions", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int allowedActions
    {
      get { return _allowedActions; }
      set { _allowedActions = value; }
    }

    private int _timeoutInSeconds = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"timeoutInSeconds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int timeoutInSeconds
    {
      get { return _timeoutInSeconds; }
      set { _timeoutInSeconds = value; }
    }
    private readonly global::System.Collections.Generic.List<mahjong.MsgMeldTile> _meldsForAction = new global::System.Collections.Generic.List<mahjong.MsgMeldTile>();
    [global::ProtoBuf.ProtoMember(5, Name=@"meldsForAction", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<mahjong.MsgMeldTile> meldsForAction
    {
      get { return _meldsForAction; }
    }
  
    private int _victimTileID;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"victimTileID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int victimTileID
    {
      get { return _victimTileID; }
      set { _victimTileID = value; }
    }
    private int _victimChairID;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"victimChairID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int victimChairID
    {
      get { return _victimChairID; }
      set { _victimChairID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgPlayerAction")]
  public partial class MsgPlayerAction : global::ProtoBuf.IExtensible
  {
    public MsgPlayerAction() {}
    
    private int _qaIndex;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"qaIndex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int qaIndex
    {
      get { return _qaIndex; }
      set { _qaIndex = value; }
    }
    private int _action;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"action", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int action
    {
      get { return _action; }
      set { _action = value; }
    }

    private int _flags = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"flags", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int flags
    {
      get { return _flags; }
      set { _flags = value; }
    }

    private int _tile = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"tile", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int tile
    {
      get { return _tile; }
      set { _tile = value; }
    }

    private int _meldType = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"meldType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int meldType
    {
      get { return _meldType; }
      set { _meldType = value; }
    }

    private int _meldTile1 = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"meldTile1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int meldTile1
    {
      get { return _meldTile1; }
      set { _meldTile1 = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgActionResultNotify")]
  public partial class MsgActionResultNotify : global::ProtoBuf.IExtensible
  {
    public MsgActionResultNotify() {}
    
    private int _targetChairID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"targetChairID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int targetChairID
    {
      get { return _targetChairID; }
      set { _targetChairID = value; }
    }
    private int _action;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"action", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int action
    {
      get { return _action; }
      set { _action = value; }
    }

    private int _actionTile = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"actionTile", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int actionTile
    {
      get { return _actionTile; }
      set { _actionTile = value; }
    }

    private mahjong.MsgMeldTile _actionMeld = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"actionMeld", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public mahjong.MsgMeldTile actionMeld
    {
      get { return _actionMeld; }
      set { _actionMeld = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _newFlowers = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(5, Name=@"newFlowers", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> newFlowers
    {
      get { return _newFlowers; }
    }
  

    private int _tilesInWall = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"tilesInWall", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int tilesInWall
    {
      get { return _tilesInWall; }
      set { _tilesInWall = value; }
    }

    private bool _waitDiscardReAction = default(bool);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"waitDiscardReAction", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool waitDiscardReAction
    {
      get { return _waitDiscardReAction; }
      set { _waitDiscardReAction = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgRestore")]
  public partial class MsgRestore : global::ProtoBuf.IExtensible
  {
    public MsgRestore() {}
    
    private mahjong.MsgDeal _msgDeal;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"msgDeal", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public mahjong.MsgDeal msgDeal
    {
      get { return _msgDeal; }
      set { _msgDeal = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _readyHandChairs = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"readyHandChairs", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> readyHandChairs
    {
      get { return _readyHandChairs; }
    }
  

    private int _lastDiscaredChairID = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"lastDiscaredChairID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int lastDiscaredChairID
    {
      get { return _lastDiscaredChairID; }
      set { _lastDiscaredChairID = value; }
    }

    private bool _isMeNewDraw = default(bool);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"isMeNewDraw", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isMeNewDraw
    {
      get { return _isMeNewDraw; }
      set { _isMeNewDraw = value; }
    }

    private bool _waitDiscardReAction = default(bool);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"waitDiscardReAction", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool waitDiscardReAction
    {
      get { return _waitDiscardReAction; }
      set { _waitDiscardReAction = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _flyReadyHandChairs = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(6, Name=@"flyReadyHandChairs", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> flyReadyHandChairs
    {
      get { return _flyReadyHandChairs; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgPlayerScoreGreatWin")]
  public partial class MsgPlayerScoreGreatWin : global::ProtoBuf.IExtensible
  {
    public MsgPlayerScoreGreatWin() {}
    
    private int _baseWinScore;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"baseWinScore", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int baseWinScore
    {
      get { return _baseWinScore; }
      set { _baseWinScore = value; }
    }
    private int _greatWinType;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"greatWinType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int greatWinType
    {
      get { return _greatWinType; }
      set { _greatWinType = value; }
    }
    private int _greatWinPoints;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"greatWinPoints", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int greatWinPoints
    {
      get { return _greatWinPoints; }
      set { _greatWinPoints = value; }
    }
    private int _trimGreatWinPoints;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"trimGreatWinPoints", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int trimGreatWinPoints
    {
      get { return _trimGreatWinPoints; }
      set { _trimGreatWinPoints = value; }
    }

    private int _continuousBankerExtra = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"continuousBankerExtra", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int continuousBankerExtra
    {
      get { return _continuousBankerExtra; }
      set { _continuousBankerExtra = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgPlayerScoreMiniWin")]
  public partial class MsgPlayerScoreMiniWin : global::ProtoBuf.IExtensible
  {
    public MsgPlayerScoreMiniWin() {}
    
    private int _miniWinType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"miniWinType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int miniWinType
    {
      get { return _miniWinType; }
      set { _miniWinType = value; }
    }
    private int _miniWinBasicScore;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"miniWinBasicScore", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int miniWinBasicScore
    {
      get { return _miniWinBasicScore; }
      set { _miniWinBasicScore = value; }
    }
    private int _miniWinFlowerScore;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"miniWinFlowerScore", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int miniWinFlowerScore
    {
      get { return _miniWinFlowerScore; }
      set { _miniWinFlowerScore = value; }
    }
    private int _miniMultiple;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"miniMultiple", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int miniMultiple
    {
      get { return _miniMultiple; }
      set { _miniMultiple = value; }
    }
    private int _miniWinTrimScore;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"miniWinTrimScore", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int miniWinTrimScore
    {
      get { return _miniWinTrimScore; }
      set { _miniWinTrimScore = value; }
    }

    private int _continuousBankerExtra = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"continuousBankerExtra", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int continuousBankerExtra
    {
      get { return _continuousBankerExtra; }
      set { _continuousBankerExtra = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgPlayerScore")]
  public partial class MsgPlayerScore : global::ProtoBuf.IExtensible
  {
    public MsgPlayerScore() {}
    
    private int _targetChairID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"targetChairID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int targetChairID
    {
      get { return _targetChairID; }
      set { _targetChairID = value; }
    }
    private int _winType;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"winType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int winType
    {
      get { return _winType; }
      set { _winType = value; }
    }
    private int _score;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int score
    {
      get { return _score; }
      set { _score = value; }
    }
    private int _specialScore;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"specialScore", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int specialScore
    {
      get { return _specialScore; }
      set { _specialScore = value; }
    }

    private mahjong.MsgPlayerScoreGreatWin _greatWin = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"greatWin", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public mahjong.MsgPlayerScoreGreatWin greatWin
    {
      get { return _greatWin; }
      set { _greatWin = value; }
    }

    private mahjong.MsgPlayerScoreMiniWin _miniWin = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"miniWin", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public mahjong.MsgPlayerScoreMiniWin miniWin
    {
      get { return _miniWin; }
      set { _miniWin = value; }
    }

    private int _fakeWinScore = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"fakeWinScore", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int fakeWinScore
    {
      get { return _fakeWinScore; }
      set { _fakeWinScore = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _fakeList = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(8, Name=@"fakeList", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> fakeList
    {
      get { return _fakeList; }
    }
  

    private bool _isContinuousBanker = default(bool);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"isContinuousBanker", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isContinuousBanker
    {
      get { return _isContinuousBanker; }
      set { _isContinuousBanker = value; }
    }

    private int _continuousBankerMultiple = default(int);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"continuousBankerMultiple", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int continuousBankerMultiple
    {
      get { return _continuousBankerMultiple; }
      set { _continuousBankerMultiple = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgHandScore")]
  public partial class MsgHandScore : global::ProtoBuf.IExtensible
  {
    public MsgHandScore() {}
    
    private readonly global::System.Collections.Generic.List<mahjong.MsgPlayerScore> _playerScores = new global::System.Collections.Generic.List<mahjong.MsgPlayerScore>();
    [global::ProtoBuf.ProtoMember(1, Name=@"playerScores", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<mahjong.MsgPlayerScore> playerScores
    {
      get { return _playerScores; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgHandOver")]
  public partial class MsgHandOver : global::ProtoBuf.IExtensible
  {
    public MsgHandOver() {}
    
    private int _endType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"endType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int endType
    {
      get { return _endType; }
      set { _endType = value; }
    }
    private readonly global::System.Collections.Generic.List<mahjong.MsgPlayerTileList> _playerTileLists = new global::System.Collections.Generic.List<mahjong.MsgPlayerTileList>();
    [global::ProtoBuf.ProtoMember(2, Name=@"playerTileLists", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<mahjong.MsgPlayerTileList> playerTileLists
    {
      get { return _playerTileLists; }
    }
  

    private mahjong.MsgHandScore _scores = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"scores", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public mahjong.MsgHandScore scores
    {
      get { return _scores; }
      set { _scores = value; }
    }

    private bool _continueAble = default(bool);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"continueAble", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool continueAble
    {
      get { return _continueAble; }
      set { _continueAble = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"TileID")]
    public enum TileID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"enumTid_MAN1", Value=0)]
      enumTid_MAN1 = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"enumTid_MAN2", Value=1)]
      enumTid_MAN2 = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"enumTid_MAN3", Value=2)]
      enumTid_MAN3 = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"enumTid_MAN4", Value=3)]
      enumTid_MAN4 = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"enumTid_MAN5", Value=4)]
      enumTid_MAN5 = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"enumTid_MAN6", Value=5)]
      enumTid_MAN6 = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"enumTid_MAN7", Value=6)]
      enumTid_MAN7 = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"enumTid_MAN8", Value=7)]
      enumTid_MAN8 = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"enumTid_MAN9", Value=8)]
      enumTid_MAN9 = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"enumTid_PIN1", Value=9)]
      enumTid_PIN1 = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"enumTid_PIN2", Value=10)]
      enumTid_PIN2 = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"enumTid_PIN3", Value=11)]
      enumTid_PIN3 = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"enumTid_PIN4", Value=12)]
      enumTid_PIN4 = 12,
            
      [global::ProtoBuf.ProtoEnum(Name=@"enumTid_PIN5", Value=13)]
      enumTid_PIN5 = 13,
            
      [global::ProtoBuf.ProtoEnum(Name=@"enumTid_PIN6", Value=14)]
      enumTid_PIN6 = 14,
            
      [global::ProtoBuf.ProtoEnum(Name=@"enumTid_PIN7", Value=15)]
      enumTid_PIN7 = 15,
            
      [global::ProtoBuf.ProtoEnum(Name=@"enumTid_PIN8", Value=16)]
      enumTid_PIN8 = 16,
            
      [global::ProtoBuf.ProtoEnum(Name=@"enumTid_PIN9", Value=17)]
      enumTid_PIN9 = 17,
            
      [global::ProtoBuf.ProtoEnum(Name=@"enumTid_SOU1", Value=18)]
      enumTid_SOU1 = 18,
            
      [global::ProtoBuf.ProtoEnum(Name=@"enumTid_SOU2", Value=19)]
      enumTid_SOU2 = 19,
            
      [global::ProtoBuf.ProtoEnum(Name=@"enumTid_SOU3", Value=20)]
      enumTid_SOU3 = 20,
            
      [global::ProtoBuf.ProtoEnum(Name=@"enumTid_SOU4", Value=21)]
      enumTid_SOU4 = 21,
            
      [global::ProtoBuf.ProtoEnum(Name=@"enumTid_SOU5", Value=22)]
      enumTid_SOU5 = 22,
            
      [global::ProtoBuf.ProtoEnum(Name=@"enumTid_SOU6", Value=23)]
      enumTid_SOU6 = 23,
            
      [global::ProtoBuf.ProtoEnum(Name=@"enumTid_SOU7", Value=24)]
      enumTid_SOU7 = 24,
            
      [global::ProtoBuf.ProtoEnum(Name=@"enumTid_SOU8", Value=25)]
      enumTid_SOU8 = 25,
            
      [global::ProtoBuf.ProtoEnum(Name=@"enumTid_SOU9", Value=26)]
      enumTid_SOU9 = 26,
            
      [global::ProtoBuf.ProtoEnum(Name=@"enumTid_TON", Value=27)]
      enumTid_TON = 27,
            
      [global::ProtoBuf.ProtoEnum(Name=@"enumTid_NAN", Value=28)]
      enumTid_NAN = 28,
            
      [global::ProtoBuf.ProtoEnum(Name=@"enumTid_SHA", Value=29)]
      enumTid_SHA = 29,
            
      [global::ProtoBuf.ProtoEnum(Name=@"enumTid_PEI", Value=30)]
      enumTid_PEI = 30,
            
      [global::ProtoBuf.ProtoEnum(Name=@"enumTid_HAK", Value=31)]
      enumTid_HAK = 31,
            
      [global::ProtoBuf.ProtoEnum(Name=@"enumTid_HAT", Value=32)]
      enumTid_HAT = 32,
            
      [global::ProtoBuf.ProtoEnum(Name=@"enumTid_CHU", Value=33)]
      enumTid_CHU = 33,
            
      [global::ProtoBuf.ProtoEnum(Name=@"enumTid_PLUM", Value=34)]
      enumTid_PLUM = 34,
            
      [global::ProtoBuf.ProtoEnum(Name=@"enumTid_ORCHID", Value=35)]
      enumTid_ORCHID = 35,
            
      [global::ProtoBuf.ProtoEnum(Name=@"enumTid_BAMBOO", Value=36)]
      enumTid_BAMBOO = 36,
            
      [global::ProtoBuf.ProtoEnum(Name=@"enumTid_CHRYSANTHEMUM", Value=37)]
      enumTid_CHRYSANTHEMUM = 37,
            
      [global::ProtoBuf.ProtoEnum(Name=@"enumTid_SPRING", Value=38)]
      enumTid_SPRING = 38,
            
      [global::ProtoBuf.ProtoEnum(Name=@"enumTid_SUMMER", Value=39)]
      enumTid_SUMMER = 39,
            
      [global::ProtoBuf.ProtoEnum(Name=@"enumTid_AUTUMN", Value=40)]
      enumTid_AUTUMN = 40,
            
      [global::ProtoBuf.ProtoEnum(Name=@"enumTid_WINTER", Value=41)]
      enumTid_WINTER = 41,
            
      [global::ProtoBuf.ProtoEnum(Name=@"enumTid_MAX", Value=42)]
      enumTid_MAX = 42
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"MessageCode")]
    public enum MessageCode
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"OPInvalid", Value=0)]
      OPInvalid = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OPAction", Value=1)]
      OPAction = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OPActionResultNotify", Value=2)]
      OPActionResultNotify = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OPActionAllowed", Value=3)]
      OPActionAllowed = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OPReActionAllowed", Value=5)]
      OPReActionAllowed = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OPDeal", Value=6)]
      OPDeal = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OPHandOver", Value=7)]
      OPHandOver = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OPRestore", Value=8)]
      OPRestore = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OPPlayerLeaveRoom", Value=9)]
      OPPlayerLeaveRoom = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OPPlayerEnterRoom", Value=10)]
      OPPlayerEnterRoom = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OPDisbandRequest", Value=11)]
      OPDisbandRequest = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OPDisbandNotify", Value=12)]
      OPDisbandNotify = 12,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OPDisbandAnswer", Value=13)]
      OPDisbandAnswer = 13,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OPPlayerReady", Value=14)]
      OPPlayerReady = 14,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OPRoomDeleted", Value=15)]
      OPRoomDeleted = 15,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OPRoomUpdate", Value=16)]
      OPRoomUpdate = 16,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OPRoomShowTips", Value=17)]
      OPRoomShowTips = 17,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OPGameOver", Value=18)]
      OPGameOver = 18,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OPKickout", Value=19)]
      OPKickout = 19,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OPDonate", Value=20)]
      OPDonate = 20
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"MeldType")]
    public enum MeldType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"enumMeldTypeSequence", Value=0)]
      enumMeldTypeSequence = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"enumMeldTypeTriplet", Value=1)]
      enumMeldTypeTriplet = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"enumMeldTypeExposedKong", Value=2)]
      enumMeldTypeExposedKong = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"enumMeldTypeTriplet2Kong", Value=3)]
      enumMeldTypeTriplet2Kong = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"enumMeldTypeConcealedKong", Value=4)]
      enumMeldTypeConcealedKong = 4
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ActionType")]
    public enum ActionType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"enumActionType_SKIP", Value=1)]
      enumActionType_SKIP = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"enumActionType_DISCARD", Value=2)]
      enumActionType_DISCARD = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"enumActionType_DRAW", Value=4)]
      enumActionType_DRAW = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"enumActionType_CHOW", Value=8)]
      enumActionType_CHOW = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"enumActionType_PONG", Value=16)]
      enumActionType_PONG = 16,
            
      [global::ProtoBuf.ProtoEnum(Name=@"enumActionType_KONG_Exposed", Value=32)]
      enumActionType_KONG_Exposed = 32,
            
      [global::ProtoBuf.ProtoEnum(Name=@"enumActionType_KONG_Concealed", Value=64)]
      enumActionType_KONG_Concealed = 64,
            
      [global::ProtoBuf.ProtoEnum(Name=@"enumActionType_WIN_Chuck", Value=128)]
      enumActionType_WIN_Chuck = 128,
            
      [global::ProtoBuf.ProtoEnum(Name=@"enumActionType_WIN_SelfDrawn", Value=256)]
      enumActionType_WIN_SelfDrawn = 256,
            
      [global::ProtoBuf.ProtoEnum(Name=@"enumActionType_KONG_Triplet2", Value=512)]
      enumActionType_KONG_Triplet2 = 512,
            
      [global::ProtoBuf.ProtoEnum(Name=@"enumActionType_FirstReadyHand", Value=1024)]
      enumActionType_FirstReadyHand = 1024,
            
      [global::ProtoBuf.ProtoEnum(Name=@"enumActionType_ReadyHand", Value=2048)]
      enumActionType_ReadyHand = 2048,
            
      [global::ProtoBuf.ProtoEnum(Name=@"enumActionType_FlyReadyHand", Value=4096)]
      enumActionType_FlyReadyHand = 4096,
            
      [global::ProtoBuf.ProtoEnum(Name=@"enumActionType_AccumulateWin", Value=8192)]
      enumActionType_AccumulateWin = 8192
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"HandOverType")]
    public enum HandOverType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"enumHandOverType_None", Value=0)]
      enumHandOverType_None = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"enumHandOverType_Win_SelfDrawn", Value=1)]
      enumHandOverType_Win_SelfDrawn = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"enumHandOverType_Win_Chuck", Value=2)]
      enumHandOverType_Win_Chuck = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"enumHandOverType_Chucker", Value=3)]
      enumHandOverType_Chucker = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"enumHandOverType_Konger", Value=4)]
      enumHandOverType_Konger = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"enumHandOverType_Win_RobKong", Value=5)]
      enumHandOverType_Win_RobKong = 5
    }
  
}